### ISSUE TITLE
Support limiting of the hdd folder size

### ISSUE THREAD

**Issue by Tratoschek** [yacy/yacy_search_server#103]
If I see it right, the current settings only allow to disable certain things, if there is not enough free space anymore.

It would be nice, if there would be an option: "Limit the DATA folder to x megabytes."

Of course I can use quotas etc., but native support would be great.

**Comment by Velociraptor85** [comment]
Yes this is very good Idea! I want that too! 
And I even think that this would help grow the count of nodes, since people could set the size they want to contribute.

Please implement =)

**Comment by luccioman** [comment]
Hi I also agree on the usefulness of such a feature. 
Looking a bit closer, it appears that it has already been implemented almost [three years ago](https://github.com/yacy/yacy_search_server/commit/9eb668e95118267837f74ee6f0c861c2b6cf369c)!
The only problem is that as far as I understand it the related [configuration settings](https://github.com/yacy/yacy_search_server/blob/Release_1.92/defaults/yacy.init#L1130) are hidden in advanced settings or need manual yacy.conf edition. Unfortunately many users (including me) probably miss it...

I propose to add more user-friendly control over these settings in the existing Performance_p.html page.

**Comment by luccioman** [comment]
The Performance_p.html has been updated (see commit 68afe900d079219721180e769eea16a5a91aaa96)! Feedback will be welcome.

**Comment by luccioman** [comment]
I used the previously mentioned settings for a few months now, configured from Performance_p.html. Works rather fine, at least on my own peers.
