### ISSUE TITLE
<script> without `<!-- -->` scraped sometimes

### ISSUE THREAD

**Issue by sinkuu** [yacy/yacy_search_server#109]
```html
<script>
if (a<w&&w>b) { do_something(); }
</script>
```

This will generate snippet `b) { do_something(); }`.

**Comment by reger24** [comment]
I can't reproduce or confirm this, the html <script> tag is recognized fine in my tests, in header as well as in body part  of html and without any <!--
If you can provide a URL with a page I'll crawl it (for real world test).

**Comment by sinkuu** [comment]
Sorry, I haven't checked the fragment reproduces the problem. Probably more than one `<`s are needed.

https://ipfs.io/ipfs/QmWiwrfqjVXxvsSt7T4sVEgnDN8FuUPp9socBFgvBNFGFr

By crawling the link above, I get this parsed sentence:

```
a.h:1250==a.w)?C(k,"a-ws"):ca(k,"a-ws")):Q--&&(ea=setTimeout(D,16))}}function na(a){(E=void 0===a?!E:!!a)&&D()}function oa(){return E}"use strict";t=f.AmazonUIPageJS||f.P;var n=f.ue;n&&n.tag&&(n.tag("aui"),n.tag("aui:aui_build_date:3.17.1.6-2017-02-08"));var F=H.now=H.now||function(){return+new H},N=function(a){return a&&a.now?a.now.bind(a):F}(f.performance),J=[],K=!1,U;U=function(){for(var a=I(),b=F();J.length;)if(J.shift()(),50
```

**Comment by sinkuu** [comment]
A real world example: https://www.amazon.co.jp/%E3%83%95%E3%82%A1%E3%83%83%E3%82%B7%E3%83%A7%E3%83%B3-%E3%83%AC%E3%83%87%E3%82%A3%E3%83%BC%E3%82%B9-%E3%83%A1%E3%83%B3%E3%82%BA-%E3%82%AD%E3%83%83%E3%82%BA-%E9%80%9A%E8%B2%A9/b?ie=UTF8&node=2229202051
The script is reponded from this URL.

**Comment by reger24** [comment]
Thanks,
the links helped to reproduce the issue. I've now a test case to work with and will Analyse the causing code sequence for a fix.
