### ISSUE TITLE
Would there be a performance increase with these java options?

### ISSUE THREAD

**Issue by smokingwheels** [yacy/yacy_search_server#11]
See [url]http://www.minecraftforum.net/forums/support/server-support/server-administration/1937726-java-7-8-command-line-options-for-minecraft[/url]
My minecraft CPU usage was around 40% just at idle now 3-4%.
Not to sure what all of them do so someone would have to test it because my Yacy server in windows crawled much higher PPM than I have ever seen before.

Also setting up the program to run in a small RAM disk would take some doing to store the data some where else.
Settings.

Java 7:
-Xmn2G -Xss4M -Xms4G -Xmx4G -XX:+UseLargePages -XX:PermSize=256M -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -XX:+UseStringCache -XX:+OptimizeStringConcat -XX:+UseCompressedStrings -XX:+UseBiasedLocking -Xincgc -XX:MaxGCPauseMillis=10 -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:+CMSParallelRemarkEnabled -XX:ParallelGCThreads=10 -Djava.net.preferIPv4Stack=true

Java 8:
-Xmn2G -Xss4M -Xms4G -Xmx4G -XX:+UseLargePages -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:+UseBiasedLocking -Xincgc -XX:MaxGCPauseMillis=10 -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:+CMSParallelRemarkEnabled -XX:ParallelGCThreads=10 -Djava.net.preferIPv4Stack=true

What do you think?

**Comment by Orbiter** [comment]
Just recently there was a problem in the loklak project because of the usage of agressive jvm options which had not been available on [any-random-device]. The better way is, to have more devices and more users instead of tuning one single system version to the limit.
