### ISSUE TITLE
Please describe somewhere traffic requirements

### ISSUE THREAD

**Issue by Nashev** [yacy/yacy_search_server#112]
How many incoming and outgoing traffic it will use approximately?
How to control it?
Where to obtain average [API](http://www.yacy-websuche.de/wiki/index.php/Dev:API) usage statistic?

I can't find this information at all!

**Comment by smokingwheels** [comment]
Its really hard to say but if you have a good long list in your hosts file about 1-2 GB a day.
It does depend if you are crawling greatly.
I welcome other feedback.

**Comment by smokingwheels** [comment]
I have done more tests and about 500-600 MB a day.
Hope that helps.
I also have this [Block List](http://winhelp2002.mvps.org/hosts.htm) plus a few other IP's as well.

**Comment by smokingwheels** [comment]
Have done some more tests Crawling and have used 90 GB in 20 hours that is in the cloud with a 4 Core setup with the version 1.92/9232 running Debian Jessie x64 Headless.
The version 1.92/9231 the figure was 79 GB in 24 hours.
On my ADSL 2+ at home I used in the order of 22 GB a day Crawling.

**Comment by smokingwheels** [comment]
A short video with a iptraf monitor in linux on my home connection crawling with a rather long black list.
The values are in kbits/sec [https://youtu.be/hS4pVTqnlaI](url)

**Comment by frankenstein91** [comment]
no feedback from opener... I will close it
