### ISSUE TITLE
Unable to export.

### ISSUE THREAD

**Issue by Achaean** [yacy/yacy_search_server#116]
**Hi!** :-)

Yacy is unable to export.
Going to [http://localhost:8090/IndexExport_p.html](url) and pressing "Export", returns:
"Export to file -no export- failed: number of exported documents == 0".
I tried also other locations as well, but nothing changed. Of course no admin rights directories.

I'm on Win 10x64, with latest Yacy and Java versions (Yacy v.1.92/9000 and Oracle Java v.8U121 x64).

PS. I also have Yacy installed on Linux (Debian Jessie x64 KDE) and Export function, works properly.
This report, is for Yacy running on Windows **only**.
**Bye!** :-)
A.

**Comment by luccioman** [comment]
Hi @Achaean, thank you for reporting.
I just ran successful exports on similar YaCy installs (Windows 10 64bits with Java 1.8, YaCy v1.92/9000 and YaCy v1.92/9159).
Can you detail which exact export option did you use?
Maybe you can also check your YaCy logs and look for some export related error?

**Comment by Achaean** [comment]
Hi luccioman! :-)

I went to the export page and I pressed the export button (as the wiki prompts), without altering any parameters.
When that failed, I changed the export directory to somewhere else (eg. to C:\TEMPG).

I doubt If I can interpret the logs correctly. :-)
Which log needed to attach here?

**Comment by Achaean** [comment]
Here's the LOG directory:
[https://drive.google.com/file/d/0BzArF1GHbSHOZFYyVk1ocXQ4eGM/view?usp=sharing](url)

**Comment by luccioman** [comment]
Hi @Achaean , there is effectively an error reported in your yacy00.log :

> E 2017/04/10 13:32:50 org.apache.solr.handler.RequestHandlerBase java.lang.IllegalStateException: unexpected docvalues type NONE for field 'load_date_dt' (expected=NUMERIC). Use UninvertingReader or index with docvalues.

So it looks like this is the same error as reported in mantis 682 : http://mantis.tokeek.de/view.php?id=682
As you can see in the mantis notes, it was suggested to re-index...  Maybe you can also try to filter with the solr "query" or "maximum age" to exclude the documents producing the error...

Personally I won't have time too further dig the issue in the coming days, but I will check again when coming back. If you find a workaround in the meantime your feedback will be welcome.

**Comment by luccioman** [comment]
I just pushed a fix. @Achaean if you can test again with latest sources your feedback will be welcome.

**Comment by Achaean** [comment]
Yes indeed!
Problem solved. :-)
