### ISSUE TITLE
Enable non-admin public access to /CacheResource_p.html?url=foo URLs?

### ISSUE THREAD

**Issue by sideshowbarker** [yacy/yacy_search_server#120]
I’d like to allow users of search results from my Yacy instance to browse cache copies of indexed documents. Is there a way to make `/CacheResource_p.html?url=foo` URLs not require admin perms?

**Comment by Orbiter** [comment]
There is an unclear copyright situation with cache content, that's why the servlet needs authentication

_Sent from my HUAWEI ALE-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by sideshowbarker** [comment]
Makes sense—thanks for explaining
