### ISSUE TITLE
Can’t crawl https://drafts.csswg.org/

### ISSUE THREAD

**Issue by sideshowbarker** [yacy/yacy_search_server#121]
I’m trying to get my Yacy instance to crawl https://drafts.csswg.org/ but it times out:

> Crawling of "https://drafts.csswg.org/" failed. Reason: scraper cannot load URL: java.io.IOException: Client can't execute: connect timed out duration=30467 for url https://drafts.csswg.org//

I don’t have any problem connecting to https://drafts.csswg.org/ from any other clients—for example, from `curl` or from the W3C HTML Checker, which uses Java and Jetty on its backend:

https://validator.w3.org/nu/?doc=https://drafts.csswg.org/

**Comment by smokingwheels** [comment]
Where both these options selected? 
Obey html-robots-noindex:
Obey html-robots-nofollow: 
I crawled it no problem.
What Version are you using?

**Comment by sideshowbarker** [comment]
> Where both these options selected?
> Obey html-robots-noindex:
> Obey html-robots-nofollow:

Yep

> What Version are you using?

I’m running code from latest master of a repo clone—

```
YaCy version: 1.921/9239
Java version: 1.8.0_121
```

Maybe it’s just a problem with https://drafts.csswg.org/? Right now I’m seeing a delay of around 20+ seconds before I even get the start of the response.

I guess it’s possible that it may be tarpitting me.

**Comment by sideshowbarker** [comment]
Checking with `mtr` etc from the command line in the environment where the Yacy backend is running reveals the problem to be some kind of routing issue between there and drafts.csswg.org

**Comment by smokingwheels** [comment]
In the DATA/SETTINGS/yacy.conf just past half way down try increasing the value its in mS. 
crawler.clientTimeout=30000
Restart your peer.
The tarpitting is an issue for me at the moment to.  If leave the site alone for a while (24 hours) and try again maybe a different time of day?  
There is the Webportal Mode options, but not sure if that is what you want?

**Comment by 4nanook** [comment]
Similar issue with nih.gov, any tips?
Crawling of "https://nih.gov/" failed. Reason: scraper cannot load URL: Client can't execute: Connection pool shut down duration=1 for url https://nih.gov//
