### ISSUE TITLE
Regular Expressions

### ISSUE THREAD

**Issue by tank-crd** [yacy/yacy_search_server#123]
I am really having a hard time with advanced crawl and regular expressions in the admin back end. I follow the redirects to the regular expressions page that is linked from the wiki, but I just cannot get it down. Is there a better source for figuring out how to use the regular expressions? Or is there a different way that doesn't involve regular expressions?

**Comment by serprex** [comment]
[Here's an interactive page to test regex](http://java-regex-tester.appspot.com)

Have you since resolved your original issue?
