### ISSUE TITLE
Cannot open port - ubuntu

### ISSUE THREAD

**Issue by raspatan** [yacy/yacy_search_server#129]
Hi there. 

I know this is a task not specific to YaCy, but I am struggling with this. I am a newbie on this stuff. So, I went to my router and configured the port forwarding:

![untitled](https://user-images.githubusercontent.com/14203648/31047487-8b8b9a66-a603-11e7-9c1d-776b25e0419b.png)

The IPv4 address is correct. Then, I go to my localhost:8090 website, and I see the message "You cannot be reached from outside. A possible reason is that you are behind a firewall, NAT or Router." and etc. That means I cannot be seen in the network, and the port has not been properly open. In effect, I have the Firewall enabled, and the DMZ disabled. I tried with www.canyouseeme.org (using port 8090) but it says it is not open.

How can I enable the port? I am using Ubuntu.

**Comment by smokingwheels** [comment]
If you are using UFW try  `sudo ufw allow 8090`
Also there are some ISP's that share IP addresses between users which yacy wont become a senior peer from my memory, I guess you might have to rent a headless cloud and use that.

**Comment by smokingwheels** [comment]
Did you change the port from 8090?
Try a crawl see if it works.

**Comment by raspatan** [comment]
@smokingwheels Sorry! Busy these days. Yes, I solved it with your help. The UFW was blocking the port. Contributing to the global network now! :) 

Thanks!
