### ISSUE TITLE
LibreJS

### ISSUE THREAD

**Issue by 539h** [yacy/yacy_search_server#13]
LibreJS is blocking the javascript because no license is specified.
It'll be good if you release the javascript with a free license.
See https://www.gnu.org/software/librejs/free-your-javascript.html

**Comment by Orbiter** [comment]
Having a proper license to all code pieces is a valid requirement. I admit that LibreJS is a good way, but it should not be considered as the one and only way to present licenses. We are lacking resources to add each 'this is a nice thing, you must add it'-request. Your contribution would be very welcome if you decide to add license attribution the LibreJS-way yourself. Please re-open this issue and assign it to yourself if you want to contribute.
