### ISSUE TITLE
Activate Travis automated build

### ISSUE THREAD

**Issue by luccioman** [yacy/yacy_search_server#131]
Travis configuration is now [fixed](https://github.com/yacy/yacy_search_server/commit/5a67d0f46db35d0db374b3ebbf80512cb0a77148). 
One last interesting step would be to activate this repository on travis-ci.org so we could then add a Build Status button on the Readme.md like the one on [yacy/yacy_grid_mcp](https://github.com/yacy/yacy_grid_mcp).
This has to be done by someone having admin rights (@Orbiter , @reger24 ?)

For @mariobehling, as you can check again [there](https://travis-ci.org/yacy/yacy_search_server), Travis build is indeed currently not active for this repository.

**Comment by mariobehling** [comment]
Thank you. I activated this repo as well. However your earlier comments were in the Yacy Grid repository https://github.com/yacy/yacy_grid_mcp/commit/15240696cf20983951d15526f66ebe8e8f45adf4 

So, thank you for bringing this into the correct repository and directing us to the component that needed attention.

**Comment by luccioman** [comment]
Great, it looks like it is working fine. Thanks and sorry for the confusing comments.
