### ISSUE TITLE
Buttons missing on yacysearch.html

### ISSUE THREAD

**Issue by songproducer** [yacy/yacy_search_server#132]
For example:

http://leoyacy.myddns.me/yacysearch.html

I’m trying to get the buttons ‘search the peer network’ and ‘privacy mode’ to show.

**Comment by smokingwheels** [comment]
It could be because you set a password and the system now logs you out after a short time.
But its there if you are on localhost.

**Comment by songproducer** [comment]
You're right, logging in got the buttons back. How can I stop the system from logging out?

**Comment by luccioman** [comment]
Hi @songproducer , which YaCy version do you run? On latest sources from GitHub, this should now be fixed by commit 27ab733685930a8c967c3f28197fc34f98123010.

**Comment by reger24** [comment]
seems to be fixed
