### ISSUE TITLE
crashing; extreme cpu usage - any logs you want before I delete?

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [yacy/yacy_search_server#139]
Under Ubuntu 16.04 LTS, 64 bit, with Openbox, no further DE (think Lubuntu, but lighter), built from the mini.iso. After running it a while, Yacy pages became unavailable. I started it in a terminal, but since it daemonizes & returns a prompt, that didn't provide any useful debugging info. Is there a less demonic way to run it?  So I started it again & and it started working. I had been crawling so I assume it started crawling again where it left off. I never could find it by grepping ps -wweo output, nor in lxtask or htop, so I don't know if maybe I was running 2 instances, at that point. But after a while cpu usage maxed out making my system very slow (didn't crash again though). Both lxtask and htop confirmed the high cpu usage, but when ordering processes by cpu usage neither could show what was doing it. But since I haven't seen this in a while, and I just started running yacy, I assume it is the culprit. I did see a lot of "java" lines in one of those - I think it was htop - but no one process was admitting to using up my cpu.

At this point I'm inclined to uninstall it (that's just deleting the directory, right?) & wait and try the next version. But before I do that, are there any logs I should post? Or tests I should run? Or for that matter, something I should try before giving up on this version? Glad to hang on to it a while longer if it could help. I really would like to see this project succeed.

**Comment by luccioman** [comment]
@Lew-Rockwell-Fan , there are many questions here. I will try to give you some answers, but one first question I have, is which version of YaCy do you use and how did you install it : Debian package, tar.gz binary, compiled from latest sources... ?
Then :
- less demonic way to run : run `sh startYACY.sh -d`
- yacy prevent itself from running two instances at the same time on the same DATA folder by checking a lock file (DATA/yacy.running)
- how to find it in the processes list : a basic `ps aux | grep yacy` do the job (the listed command starts with /usr/bin/java)
- when using 'top' : the YaCy command name is `java`
- controlling cpu usage : of course it depends on what your are doing with YaCy : intensive crawling? Only p2p search? By the way, some settings controlling system load can be found at the /PerformanceQueues_p.html page, where you can also limit some threads (light processes inside the JVM) maximum numbers (in the Thread Pool Settings table). When you are crawling, you can also control the Speed / PPM
(Pages Per Minute) in the /Crawler_p.html page. In the end, if you never used YaCy before, I would advice you to first familiarize with it a little bit before trying to run all time at full load with many concurrent crawls.

**Comment by Lew-Rockwell-Fan** [comment]
Thank you.

> which version of YaCy do you use and how did you install it  
From the tar for generic linuxes, yacy_v1.92_20161226_9000.tar.gz  (so version 1.92) per the directions here:  
https://yacy.net/en/index.html
"Decompress, run the start script and open http://localhost:8090. This needs a OpenJDK8 runtime environment."

> ps aux | grep yacy
That works now. Oddly, so does the command that failed me before:
ps -wweo pid,args | grep yacy| grep -v grep
I have no idea why. I've rebooted since. Maybe that fixed it. Rebooting is the catholicon of IT.

Thanks for all your tips. I've gotten a better handle on the circumstances in which yacy eats my cpu - it happens when I do a search. Crawling doesn't seem to be the source of the problem. So I didn't uninstall it. Still crawling with no problems. I'll report more on cpu usage when I figure out more. Right now, I'm running it heavily niced but that doesn't seem to make any difference in yacy search performance although it presumably stops if from interfering with whatever else I'm doing.

Any further suggestions on tools to figure out why cpu usage goes through the roof when I do a yacy search or what, if anything, I can do to ameliorate or fix it, would be welcome.

**Comment by luccioman** [comment]
Ok, you also have to take in consideration that it is normal behaviour to have a higher CPU usage when performing searches on a freshly installed YaCy, as there is nothing yet in its own local index, and everything has to be fetched from other peers. With time, more results will be found directly from your own index filled with your own crawls, by previous results, and by background peer-to-peer index distribution rules.

To go further on CPU monitoring : from a developer-oriented point of view, I recommend VisualVM (available as visualvm package on Ubuntu or Debian). This is definitely a useful free software tool to monitor in details both CPU and Memory usage in YaCy but also in any Java based application. From a user perspective it might seem a bit technical, but at least you easily can take snapshots of CPU or memory usage and transmit them to someone who will be able to interpret them.

**Comment by Lew-Rockwell-Fan** [comment]
Looking better.  I cut the thread numbers in half & started running the script niced to 19. That helped. Haven't gotten the pages per minute setting to work yet. I installed visualvm but haven't had a chance to play with it yet. But the thing that helped the most was the untimely demise of my laptop, forcing me to get one with a modern cpu.  Transplanted my HD and got this running an hour ago. I'll close this tomorrow if it keeps up like this.
