### ISSUE TITLE
stopYACY.sh gives apparently misleading error message when yacy isn't running

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [yacy/yacy_search_server#140]
Error message seems to imply some part of yacy is still running, but it doesn't seem to be:

$ ps -wweo pid,args | grep -i yacy | grep -v grep
$ ~/yacy/stopYACY.sh
Please wait until the YaCy daemon process terminates [wget]
You can monitor this with 'tail -f DATA/LOG/yacy00.log' and 'fuser log/yacy00.log'
$ tail -f DATA/LOG/yacy00.log
tail: cannot open 'DATA/LOG/yacy00.log' for reading: No such file or directory
tail: no files remaining
$ fuser log/yacy00.log
Specified filename log/yacy00.log does not exist.
$ ps -wweo pid,args | grep -i wget | grep -v grep
$ ~/yacy/stopYACY.sh
Please wait until the YaCy daemon process terminates [wget]
You can monitor this with 'tail -f DATA/LOG/yacy00.log' and 'fuser log/yacy00.log'
$ ps -wweo pid,args | grep -i java | grep -v grep
$ ~/yacy/stopYACY.sh
Please wait until the YaCy daemon process terminates [wget]
You can monitor this with 'tail -f DATA/LOG/yacy00.log' and 'fuser log/yacy00.log'
$ 

Am I missing something?

**Comment by luccioman** [comment]
You are right, on YaCy 1.92/9000 release, when launching the stopYACY.sh script while YaCy is not running the message appears while it should not. But this is no more the case with latest sources available on GitHub : now the stop script reports failure to connect to the server.

About the log files, the mentioned path is relative to your install folder. Is it better with something like `tail -f ~/yacy/DATA/LOG/yacy00.log` and `fuser ~/yacy/DATA/LOG/yacy00.log `?

**Comment by Lew-Rockwell-Fan** [comment]
> About the log files . . .

Mea culpa. Of course, I should have seen that.

> this is no more the case with latest sources available on GitHub

So presumably it will work it's way to the generic linux tar soon.  Should this issue be closed or should that wait until the new tar is posted?

Thank you much.

**Comment by luccioman** [comment]
I would say once a bug fix has been published, one can close the issue, as this policy has been roughly applied until now on YaCy Mantis bug tracker (http://mantis.tokeek.de/).

By the way, if you installed from the generic tar.gz binary, you should be able to already update your YaCy version if you wish with the /ConfigUpdate_p.html page (menu RAM/Disk Usage & Updates > Download System Update). More recent "Available Releases" are marked there as developer versions, for example the latest is currently "dev 1.921/9342 (signed)". 
Efforts are done to make developer versions as stable as the latest official release so I would recommend to preferably use them when possible, as the main official release is not updated so often.
I would say once a bug fix has been published, one can close the issue, as this policy has been roughly applied until now on YaCy Mantis bug tracker (http://mantis.tokeek.de/).

By the way, if you installed from the generic tar.gz binary, you should be able to already update your YaCy version if you wish with the /ConfigUpdate_p.html page (menu RAM/Disk Usage & Updates > Download System Update). More recent "Available Releases" are marked there as developer versions, for example the latest is currently "dev 1.921/9342 (signed)". 
Efforts are done to make developer versions as stable as the latest official release so I would recommend to preferably use them when possible, as the main official release is not updated so often.

**Comment by Lew-Rockwell-Fan** [comment]
Thanks again. I'll close this then. I presume I'm more likely to be useful running the latest dev version than the stable, so I'll switch to that later today after I've run this as-is a few hours to test the effect of my latest tinkering.
