### ISSUE TITLE
Yacy opens Firefox on starting. Doesn't need to as far as I can see. Probably shouldn't.

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [yacy/yacy_search_server#142]
Low priority annoyance, whether you count it as a bug or a feature request:

I'm starting yacy, niced to 19, in a script that is run after my  window manager (Openbox) starts, so it will crawl in the bg most of the time. It always pops up Firefox.  Which isn't a major problem but is kind of annoying & not of much value as far as I can see. It probably wouldn't bother someone who has days of uptime but I tinker  a lot & I'm rebooting all the time. It would be nice if this were at least an option to stop this.

For that matter, couldn't I start Yacy earlier, even before I run startx? When Ffx couldn't run anyway? Sometimes I spend a while doing stuff in bash before before I start  X. No reason Yacy couldn't be crawling then is there?

Also, & this is probably not a Yacy issue, but more likely something I have misconfigured re default apps. I still have Firefox installed but I use Pale Moon now, & if Yacy just HAS to pop up a web browser I'd rather it use that, if there is a place I could change that.

**Comment by luccioman** [comment]
> It would be nice if this were at least an option to stop this.

A configuration setting exists for this : "Auto-popup on start-up" can be disabled in the /Status.html page, which is backed by the `browserPopUpTrigger` key in your DATA/SETTINGS/yacy.conf file.

> couldn't I start Yacy earlier, even before I run startx?

Yes you can run YaCy without any X Server. Indeed it is explicitly instructed as the Java argument `-Djava.awt.headless=true` in the startYACY.sh script (or in the yacy.sh script within the Parabola package).

Finally regarding the default browser launched, on Linux platforms, it is likely to be launched using the `xdg-open` util, which is part of the freedesktop [xdg-utils](https://www.freedesktop.org/wiki/Software/xdg-utils/) tools. The command "`xdg-settings get default-web-browser`" may help you to check your configuration.

**Comment by Lew-Rockwell-Fan** [comment]
Thank you much.  I did all that. My xdg was set to a bad desktop file for Pale Moon & I guess it has some fallback mechanism for picking a browser. Fixed it. I think that's going to make my crawler start more reliably. I think Firefox was using so much RAM starting up, that the crawler stopped and had to be restarted.
