### ISSUE TITLE
"Error 404 Not Found" when using navigation buttons

### ISSUE THREAD

**Issue by Scre13** [yacy/yacy_search_server#146]
In version 1.921/09485 after performing a search, it is not possible to access further result pages.
Clicking on the navigations buttons for the search results gives error:

```
HTTP ERROR 404

Problem accessing /0&startRecord=100. Reason:

    Not Found


YaCy 1.921 - powered by Jetty -
```

As I can see, the linked URL "/0&startRecord=100" is mssing some important parts, like "/yacysearch.html?query=.....".

**Comment by luccioman** [comment]
Hello @Scre13 , for me these navigation buttons are correct, either running a build from latest sources or with the latest docker image. I just tested with Chrome 62 and Firefox 57.
How do you run YaCy version 1.921/09485 : did you build yourself from latest sources? And do you get some errors in your browser console?

**Comment by Scre13** [comment]
Using the latetest source from, the error disappeared. I can no longer reproduce it.
