### ISSUE TITLE
Java version not detected correctly

### ISSUE THREAD

**Issue by Scre13** [yacy/yacy_search_server#147]
In 1.921/9485 the version of Java is not detected correctly.

On the status page the following warning is displayed, although Java 9 is installed.

`Your Java version is old. YaCy currently needs Java 1.7 but we want to migrate to Java 1.8 in the future. Migration to 1.8 won't happen until end of 2016, but we want to join code with YaCy's sister project loklak.org and with a possible re-construction of YaCy in the kaskelix architecture which will be using Java 1.8 `

On my ubutu box java 9 is installed
```
# java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)
```

**Comment by luccioman** [comment]
Thanks @Scre13 for reporting . This is now fixed by commit 640fed2.
