### ISSUE TITLE
Remove deprecated uses of org.eclipse.jetty.continuation

### ISSUE THREAD

**Issue by luccioman** [yacy/yacy_search_server#148]
The UrlProxyServlet class uses some deprecated classes from the org.eclipse.jetty.continuation package. According to documentation, javax.servlet.AsyncContext should be used instead.

But is this code still relevant as current code base seems to make no usage at all of jetty continuations : `if (!continuation.isInitial()) {
   response.sendError(HttpServletResponse.SC_GATEWAY_TIMEOUT); // Need better test that isInitial
   return;
}` ?

Maybe @reger24 you would have some advice as you produced most of the code in UrlProxyServlet?

**Comment by reger24** [comment]
No advice, was carried over from older versions.
removed cc7a93e6b6d981acf368da2ff1f35ea5b7078b70

**Comment by luccioman** [comment]
Thanks @reger24 for your quick reply.
