### ISSUE TITLE
Manual indexing of websites with Yacy

### ISSUE THREAD

**Issue by 234578** [yacy/yacy_search_server#153]
Hello,

I am currently testing with Yacy as a intranet search engine and have problems with some https sites to crawl. I get sometimes this error:
scraper can not load URL: java.io.IOException: Client can not execute: Received fatal alert: internal_error duration =.
I use Yacy on Win 10 Pro.
I know that it has to do with the TLS handshake. So far I have not found a solution. On my own website, I can configure the Cypher myself, but on other sites i have no influence.
Is it somehow possible to manually enter a website into the Yacy Index without the crawler taking action?
I search some days for a solution but I found nothing appropriate.

**Comment by luccioman** [comment]
Hi @234578 ,
are you using the main stable version (1.92/9000) with Java 1.7 ? 
If so I suggest you to at least upgrade your Java version to 1.8, as by default TLSv1.2 and TLSv1.1 are disabled in the JDK 1.7 on client connections, while the JDK 1.8 uses TLSv1.2 as default.

If you still encounter crawl issues, it is indeed possible to workaround the crawler, for example by using the surrogate input directory (DATA/SURROGATES/in). You can place there xml Solr dumps, or xml files containing Dublin Core Metadata entries that will be imported by a background job.  Or even warc archives (produced for example by a crawl with wget) if you upgrade your YaCy install to a more recent developer release or to latest sources from GitHub.

**Comment by 234578** [comment]
Thank you!
My version is 1.92009000 and i make an update for java to 1.8. then in reboot my pc. Nothing has changed. I get the same error: scraper cannot load URL: java.io.IOException: Client can't execute: Received fatal alert: internal_error duration=31 for url.  strange, I find this error occurs only on https sites hosted at 1 & 1. Is it possible that they use a virtual SSL to save costs?
I try the version von GitHub, but it will not start by press the start.bat. There is no install routine for windows inklude. With Dublin Core i find this generator https://nsteffel.github.io/dublin_core_generator/generator_nq.html there is no field to input url :-). Mabye Yacy is better working on linux than on windows.

**Comment by luccioman** [comment]
Ok, when you download latest sources from GitHub you have first to compile them (see [instructions](https://github.com/yacy/yacy_search_server#how-to-get-the-source-code-and-how-to-compile-yacy-yourself) on Readme) before using the start script.
Alternatively, you can also easily update to latest developer version using the /ConfigUpdate_p.html page on your running YaCy server.

Do you have an example public URL to provided so one can try to reproduce your issue, or is it only occurring on your Intranet sites?

**Comment by 234578** [comment]
Thank you, actually i run Yacy with windows 10. How can i compile the app on windows? I run Yacy only locally. The Standard version runs fine. I have no problem except for this error with some https pages. Is the dev version only for linux?

**Comment by luccioman** [comment]
The compile instructions I mentioned are relevant for any OS, including Windows. 
The so called "developer" releases are also cross-platform, so it will run on the same OS than the one you already run your YaCy peer on. By upgrading, you benefit from many bug fixes, libraries upgrades, performances and security improvements.
By the way, if you have some examples of failing public https URLs to provide, it can be really useful as it can help to reproduce, analyse and eventually fix potential issues in the crawl process.

**Comment by 234578** [comment]
No chance to get this version started with Windows. I have the Yacy service installed (installYaCyWindowsService.bat). This is also displayed under the services, but can not be started. Hm No idea how to make this version of Yacy working on windows.

**Comment by Scarfmonster** [comment]
@234578 
All developer versions definitely work under Windows. I just got the latest source code, compiled it and tried running it and it's fine.
When you say it's not working, do you mean the source code download, or the precompiled dev release?
The source code has to be compiled using ANT (http://ant.apache.org/manual/install.html) and if you don't want to do this you can also manually download the latest version from here: https://github.com/luccioman/yacy_search_server/releases
unpack it manually and try running it.

Another possibility is that there is some error during startup, possibly with the service. Can you try running `startYACY_debug.bat` to see if it starts that way or throws some error in the log?

**Comment by 234578** [comment]
Great, thank you, this dev version runs absolutely perfect. No problems with https sites :-))

**Comment by luccioman** [comment]
Good to know it finally works fines for you @234578!

**Comment by 234578** [comment]
I am very thankful for your help. If I have good experience under Windows I will try to run Yacy on a root server.
