### ISSUE TITLE
Shown snippet contains ignored classes

### ISSUE THREAD

**Issue by Quix0r** [yacy/yacy_search_server#158]
In my crawl profiles I use `&ignoreclassname=nocontent` for not having such tags being indexed. Still when I search for a phrase that is contained within the ignored class' tag, the snippet shows text with that ignored tag.

Example:
````
<div class="nocontent" id="menu">
<ul>
<li><a href="foo.html">Example</a>
</ul>
</div>
````
Search for `example` gives me that snippet back which is unwanted. Snippets should only contain text that are wanted (not ignored).

Example: http://sichere-kita.rmsportal.de/suche.htm <-- Enter `klettern` as search word and you can see the supposed to be ignored menu (the large snippets).

Is this a bug or feature? (I hope first one as the 2nd one would kill YaCy here.

**Comment by luccioman** [comment]
Hi @Quix0r , are you sure of your test case? For example the page http://sichere-kita.rmsportal.de/aussengelaende/klettern_balancieren/balanciergelegenheit/02.htm looks like one of your unwanted results for the klettern search word. But indeed on this page, the keyword is both in "nocontent" sections AND in "content" sections.
If instead we search for a word such as "Eingangsbereich" which appears only in the "nocontent" section of this same page, the page does not appear in the search results...

**Comment by luccioman** [comment]
Ok it looks like I read your search results a little bit to rapidly. 
Even if that is true that your test search term is both in "nocontent" and in "content" sections, that's right that the content of the Snippet contains text from a "noncontent" section. So I guess there is likely a bug to track here...

**Comment by Quix0r** [comment]
Yes, the snippet shows text from `nocontent` which should not happen. Thank you for taking time.

**Comment by Quix0r** [comment]
Are the unit tests working? I'm getting 3 failures.

````
Running net.yacy.document.parser.htmlParserTest
ScraperTagTest: [test text] = [test text]
htmlParser.parse
parse file: test/parsertest/umlaute_html_iso.html
detected charset = ISO-8859-1
parse file: test/parsertest/umlaute_html_utf8.html
detected charset = UTF-8
parse file: test/parsertest/umlaute_html_namedentities.html
detected charset = ISO-8859-1
ScraperScriptTagTest: [test text] = [test text]
testGetRealCharsetEncoding: null -> null | Supported: false
testGetRealCharsetEncoding: windows1250 -> windows-1250 | Supported: true
testGetRealCharsetEncoding: windows_1250 -> windows-1250 | Supported: true
testGetRealCharsetEncoding: ISO-8859-1 -> ISO-8859-1 | Supported: true
testGetRealCharsetEncoding: ISO8859-1 -> ISO-8859-1 | Supported: true
testGetRealCharsetEncoding: ISO-88591 -> ISO-8859-1 | Supported: true
testGetRealCharsetEncoding: ISO88591 -> ISO-8859-1 | Supported: true
testGetRealCharsetEncoding: iso_8859_1 -> ISO-8859-1 | Supported: true
testGetRealCharsetEncoding: cp-1252 -> windows-1252 | Supported: true
testGetRealCharsetEncoding: gb_2312 -> GB2312 | Supported: true
testGetRealCharsetEncoding: gb_2312-80 -> GB2312 | Supported: true
testGetRealCharsetEncoding: UTF-8; -> UTF-8 | Supported: true
htmlParser.parse
Tests run: 10, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.172 sec <<< FAILURE!
````

**Comment by Quix0r** [comment]
Any progress?

**Comment by luccioman** [comment]
Yes @Quix0r , I analyzed the involved code a bit further and did some debugging on my own peer. 
So I think this recently added feature... is simply not yet finished.
I don't know why @Orbiter pushed modifications to the crawl start page/API at this stage, but I suggest to wait a little bit for him to tell us whether or not he is still currently working on it. Otherwise, it will be up to us to complete this ;)

**Comment by Quix0r** [comment]
If he is not replying until tomorrow, let's start on weekend, okay? Sorry to ask, it is a bit pressing here.

**Comment by luccioman** [comment]
I talked a bit with Orbiter on Gitter, and he is indeed currently too busy with the YaCy grid.

I don't know if I will have much time for YaCy until next Monday, but I have already started to fix this issue and my first manual and new JUnit tests are encouraging. Stay tuned!

**Comment by luccioman** [comment]
@Quix0r , if you update to latest sources, this feature should now work properly. Feedback is welcome of course.
Happy testing.

**Comment by Quix0r** [comment]
Will test it soon.

**Comment by Quix0r** [comment]
Test case is failing:
````
  <testcase classname="net.yacy.document.parser.htmlParserTest" name="testParseHtmlDivClassFilter" time="0.047">
    <failure message="expected:&lt;0&gt; but was:&lt;1&gt;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: expected:&lt;0&gt; but was:&lt;1&gt;
        at junit.framework.Assert.fail(Assert.java:57)
        at junit.framework.Assert.failNotEquals(Assert.java:329)
        at junit.framework.Assert.assertEquals(Assert.java:78)
        at junit.framework.Assert.assertEquals(Assert.java:234)
        at junit.framework.Assert.assertEquals(Assert.java:241)
        at junit.framework.TestCase.assertEquals(TestCase.java:409)
        at net.yacy.document.parser.htmlParserTest.testParseHtmlDivClassFilter(htmlParserTest.java:229)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at junit.framework.TestCase.runTest(TestCase.java:176)
        at junit.framework.TestCase.runBare(TestCase.java:141)
        at junit.framework.TestResult$1.protect(TestResult.java:122)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at junit.framework.TestResult.run(TestResult.java:125)
        at junit.framework.TestCase.run(TestCase.java:129)
        at junit.framework.TestSuite.runTest(TestSuite.java:255)
        at junit.framework.TestSuite.run(TestSuite.java:250)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
        at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
        at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
        at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
</failure>
  </testcase>
````

**Comment by luccioman** [comment]
@Quix0r , are you sure to be up to date with all latest sources? How do you launch the test?
All JUnits are passing on my own machine, either running them manually in Eclipse or with maven.
Travis [automated build](https://travis-ci.org/yacy/yacy_search_server/jobs/340295341) including JUnit tests launch also report a successful build...

Your own fork seems to include quite a number of your own modifications. Maybe it is conflicting with latest changes on this master branch. 
I don't know exactly which one you would like to include in the master, but please create a distinct branch including only a single subject and open a pull request : it is a common way to proceed and makes it far easier to check and merge changes.

**Comment by Quix0r** [comment]
That is now nearly impossible unless I want to redo all my changes.

**Comment by Quix0r** [comment]
So far I have done the following (common) things:

1. More usage of `this.` and `final`
2. White-spaces removed
3. More usage of curly braces
4. Updated in-line documentation
5. Sorted imports (automatically done by any good IDE, like NetBeans)
6. Lesser "generic catch" by not catching `Exception` but explicit exceptions
7. Using multi-catch blocks instead of multiple single-catch all doing the same
8. Usage of diamond type, which is with Java since 6.0 as I remember correctly: `Set<Foo> = new HashSet<>(x);` is since then the proper way
9. Do **not** use `clone()` when you have `Collections.unmodifiableFoo(foo)` around!

But these are only the cleanups I have done. Else I have made it possible to have distinct protocols (SMB is not crawlable in Internet) being turned off. @Orbiter suggested me some blacklisting for this but that it is not what is wanted. FTP and SMB should **never** be crawled in my use-case. So it is much more straightforward to have them disabled in the first place.

Then it is possible to have the search results with lesser "complex" stuff in it like peer-mode/stealth-mode and many other navigators. For us geeks/freaks it is okay but not for ordinary/average people.

So I have made it possible to disable ...

1. Whether to show ranking (sorting) buttons in search results
2. Whether to show RSS feed (only hides it)
3. Whether to show sidebar in search results
4. Whether to load search suggestions

I cannot make now distinct branches for them. This requires me to redo everything ... :-(

**Comment by Quix0r** [comment]
Okay, it was my fault. Sorry for the noise. I forgot to include a change on my side, too. Need to `git reset upstream/master` or so and then re-commit + force-push all.

**Comment by Quix0r** [comment]
Re-doing my changes on master with separate feature/bugfix branches (where possible to split). Also I created a `develop` branch to make `master` stable.

**Comment by luccioman** [comment]
No problem @Quix0r , your modifications are certainly valuable, but will become even more if clearly identified. Good luck with your refactoring!

**Comment by Quix0r** [comment]
Still the same search word `klettern` is causing content being shown in snippets that is within a ignored CSS class: http://34.252.32.67:8090/yacysearch.html?query=klettern&Enter=&contentdom=text&strictContentDom=true&former=&maximumRecords=10&startRecord=0&verify=ifexist&resource=local&nav=none&prefermaskfilter=&urlmaskfilter=.*&depth=99&constraint=&meanCount=0&timezoneOffset=-60 On some search results "Stand:" is visible which is a word in left navigation which should be entirely ignored for indexing.

Here is my crawl profile:

> /Crawler_p.html?indexText=on&deleteold=age&crawlingDepth=99&directDocByURL=on&reloadIfOlderUnit=day&range=domain&snapshotsMaxDepth=-1&cachePolicy=iffresh&deleteIfOlderUnit=day&snapshotsReplaceOld=on&obeyHtmlRobotsNoindex=on&timezoneOffset=-60&recrawl=reload&storeHTCache=on&crawlingURL=http://sichere-kita.rmsportal.de&countryMustMatchSwitch=0&reloadIfOlderNumber=14&ignoreclassname=nocontent&agentName=YaCy  Internet (cautious)&collection=siki-dev&bookmarkTitle=Sichere  Kita - Internetportal der Unfallkasse NRW&intention=Sichere Kita  (Dev)&crawlingstart=1&snapshotsMustnotmatch=&snapshotsLoadImage=false&indexmustnotmatch=.*.(pdf\|doc\|docx).*&crawlOrder=on&crawlingQ=on&deleteIfOlderNumber=14&crawlingMode=url

**Comment by Quix0r** [comment]
Maybe you can reproduce this with a unit-test somehow?

**Comment by luccioman** [comment]
Hi @Quix0r , as I explained in issue #49 [comment](https://github.com/yacy/yacy_search_server/issues/49#issuecomment-365333711), 

> The main current limitation is that only `<div>` elements and their content can be filtered.

And in your examples, the "Stand:" term is embedded in a `<nav>` element... It would be properly ignored if you added "hover" to your list of ignored CSS classes.

**Comment by Quix0r** [comment]
Okay, I'm retesting it.

**Comment by Quix0r** [comment]
Seems to work with this. Would be good to not have limitations on tags.
