### ISSUE TITLE
Trying to run YaCy from git on OpenBSD: "Error: Could not find or load main class net.yacy.yacy"

### ISSUE THREAD

**Issue by dertuxmalwieder** [yacy/yacy_search_server#16]
... when running `./startYACY.sh -d` as root. :(

**Comment by smokingwheels** [comment]
I get that with win  2000 1.82 it used to run. Its been awhile sine I have had it on.

**Comment by bshouse** [comment]
Does the yacycore.jar file exist in the "lib" folder?

**Comment by dertuxmalwieder** [comment]
Np.

**Comment by bshouse** [comment]
I am not sure which package you downloaded, but I had to run 'ant' (from Apache Ant) in the directory where build.xml was located to have it create that file. Might be worth a shot.

**Comment by dertuxmalwieder** [comment]
Hmm, I didn't have to do that on FreeBSD ... :(

**Comment by bshouse** [comment]
When I downloaded the zip from github, I had to run ant. I downloaded the Linux package from the official website yesterday and just did: ./startYACY.sh 

In both cases it worked. 

I do not know how familiar you are with Java, but this error means that the file it needs in not in the classpath (either the command line or the environment variable). Do you have a yacycore.jar file anywhere in your install path? Maybe try to install the package from the website and see if it works any better.

Please let me know how it goes and I will dig some more.  Thank you.

**Comment by dertuxmalwieder** [comment]
The package from the website works indeed. I wonder why. Is there an Apache Ant on OpenBSD anyway?

**Comment by bshouse** [comment]
I am not sure if there is a package available, but I am confident it can be compiled from source. 

Thank you for fighting through and not giving up.

**Comment by sudheesh001** [comment]
@dertuxmalwieder Were you able to compile from source ?

**Comment by dertuxmalwieder** [comment]
Sorry, I was busy with things.

Meanwhile, I found `ant` (`pkg_add apache-ant`) to be working. I can't get a web connection over port 8090 though. :(

**Comment by sudheesh001** [comment]
@dertuxmalwieder I am not sure if there's an `ant` by default on OpenBSD. If you're cloning from the github repo, you need to build the source using `ant` before running `./startYACY.sh`

I think this issue can be closed with an update to the documentation.
