### ISSUE TITLE
The administrator is unable to log in

### ISSUE THREAD

**Issue by YouP2P** [yacy/yacy_search_server#162]
I am a Linux beginner who is interested in the great project of YaCy. I installed 1.92 editions in Ubuntu YaCy administrator can not log in, so I can not control YaCy, I tried to use passwd.sh to modify the password, the problem has not been solved. I hope you can answer my ignorance.

**Comment by luccioman** [comment]
Hi @YouP2P , which method did you use for your install? Did you use the Debian package provided at http://debian.yacy.net/ ?

**Comment by YouP2P** [comment]
@luccioman ，I use https://yacy.net/release/yacy_v1.92_20161226_9000.tar.gz package, now use Debian package, has been able to use. Thank you for your reply.
