### ISSUE TITLE
BUG: No search results shown

### ISSUE THREAD

**Issue by yacy-user-987126671243656** [yacy/yacy_search_server#165]
OS: Debian Testing (buster) x86_64
Java Runtime: Tested both openjdk-9-jre-headless and openjdk-8-jre-headless
yacy_search_server version: 1.921/9299 

**Problem**

Running a search in yacy returns results but none are shown. 

![yacy](https://user-images.githubusercontent.com/37067326/36968179-abdf5fe8-2059-11e8-8d0c-031e9c0aa35a.png)

As you can see, results are returned but not shown. The JS console errors reports to 

```
#(jsResort)#                                                                                                                                                    
            statistics(rsp.offset, rsp.itemscount, rsp.itemsperpage, rsp.totalcount, rsp.localIndexCount, ... (cut)
```

- I've tried commenting out the code resulting in the JS error and it fixes the error but results are still not shown. 
- I does not work in multiple browsers.
- Clicking on the RSS feed shows the results of the search.
- I don't get any results when searching from http://search.yacy.net with the error - `The search service is not available right now. Please try again.`

**Comment by yacy-user-987126671243656** [comment]
@luccioman From github source. However a more pressing issue is that your test search doesn't seem to work. Is it an issue that only effects me?

http://search.yacy.net/yacysearch/index.html returns `The search service is not available right now. Please try again.`

**Comment by luccioman** [comment]
Ok @yacy-user-987126671243656 , I just tried to reproduce your problem, performing the following steps :
 - fresh Debian testing (Buster) install in a Virtual Machine
 - `apt-get install openjdk-9-jre-headless ant` as root
 - `wget https://github.com/yacy/yacy_search_server/master.zip`
 - `unzip master.zip`
 - `cd yacy_search_server-master`
 - `ant compile`
 - `sh startYACY.sh`
 - Firefox ESR 52.6.0 automatically opens up URL `http://localhost:8090/index.html`
 - Then I search for `test` or some other terms... and everything works fine.

Do you have an idea of what differ in your setup? Some specific YaCy settings, or browser settings/add ons, etc. ?

About the demo search portal at http://search.yacy.net/, you are indeed not the only one affected, and as far as I know it has not been working for some time now. Maybe you could ask @Orbiter about it on [gitter](https://gitter.im/yacy/yacy_search_server).

**Comment by luccioman** [comment]
@yacy-user-987126671243656 do you still encounter the empty results issue, or did you found some additional clues to reproduce it?

**Comment by yacy-user-987126671243656** [comment]
@luccioman Building the project with `ant clean all` solved the issue. Thanks.
