### ISSUE TITLE
unintuitive consequence of "Protection of all pages"

### ISSUE THREAD

**Issue by etam** [yacy/yacy_search_server#171]
Enabling "Protection of all pages" makes it impossible to accept incoming connections from other YaCy nodes.

**Comment by luccioman** [comment]
Hi @etam , do you run YaCy version 1.92/9000? 
If you upgrade to a more recent one, the issue you describe should be fixed by commit bd7411a53af4f1e54bf27498f95b4f0f7934f090.

**Comment by etam** [comment]
> Hi @etam , do you run YaCy version 1.92/9000?

Yes, that's the latest stable version.

> If you upgrade to a more recent one, the issue you describe should be fixed by commit bd7411a.

Great!
