### ISSUE TITLE
Port changing is not available (Port already in use: 9999)

### ISSUE THREAD

**Issue by thima2017** [yacy/yacy_search_server#172]
On my system port 9999 is used by approx through openbsd-inetd. 
When I try to start yacy with -d option I get this message:
"
****************** YaCy Web Crawler/Indexer & Search Engine *******************
**** (C) by Michael Peter Christen, usage granted under the GPL Version 2  ****
****   USE AT YOUR OWN RISK! Project home and releases: http://yacy.net/   ****
**  LOG of       YaCy: DATA/LOG/yacy00.log (and yacy<xx>.log)                **
**  STOP         YaCy: execute stopYACY.sh and wait some seconds             **
**  GET HELP for YaCy: see http://wiki.yacy.net and http://forum.yacy.de     **
*******************************************************************************
Error: Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 9999; nested exception is: 
	java.net.BindException: Address already in use (Bind failed)
"
After that yacy_v1.92_20161226_9000 opens default browser. Web gui works, but I can't get any search results.
Current master yacy version even doesn't open browser.

**Comment by luccioman** [comment]
Hi @thima2017 , when you use the `-d` option, YaCy starts as a foreground process, but also tries to enable the JVM remote debugger on port 9999. So if you have another process already bound to this same port, this is normal than you get this error message.

Also the method to open browser at startup on Unix plaforms changed between the 1.92 release and latest sources : in 1.92 it tried to open firefox (synchronously), and in lastest it tries to open the desktop default browser using the [xdg-open](https://portland.freedesktop.org/doc/xdg-open.html) util (asynchronously).

**Comment by luccioman** [comment]
@thima2017 , using the latest sources, you can now start YaCy as a foreground process with the `-f` option, but with no remote JMX monitoring bound on the 9999 port.
Please let us know if you still encounter startup issues.

**Comment by thima2017** [comment]
Hello! Thank you for answer!
I still can't start current master version on my Lubuntu 16.04. Nobody listens 8090 port and firefox shows "Unable to connect". And I don't know how to know why.
Maybe it is relevant: when I try to stop yacy (current master) I get this:
yacy_search_server-master$ ./stopYACY.sh 
grep: ../DATA/SETTINGS/yacy.conf: No such file or directory
grep: ../DATA/SETTINGS/yacy.conf: No such file or directory
grep: ../DATA/SETTINGS/yacy.conf: No such file or directory
Enter host password for user '':curl: (7) Failed to connect to 127.0.0.1 port 80: Connection refused
curl: (7) Failed to connect to 127.0.0.1 port 80: Connection refused

I've tried to start yacy with -f option with same result.

Anyway yacy_v1.92_20161226_9000 works fine. I can see search results, all works.

**Comment by luccioman** [comment]
@thima2017 your last stack trace suggests the DATA folder used by YaCy when it runs was even not created. Just to be sure : after getting latest sources from GitHub master didn't you forget to compile the project?

**Comment by thima2017** [comment]
I didn't even know that I should do it :D. Now all works. I'm sorry.. Thank you.

**Comment by luccioman** [comment]
Ok @thima2017, no problem, you are not the first one to forget this step (including me), and probably not the last!
