### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by Velociraptor85** [yacy/yacy_search_server#175]
Hi!
I just wanted to know if a Release is planed in near future? Since 1.92 is from 12.2016

Thanks

**Comment by Perflyst** [comment]
Any news around here?

**Comment by luccioman** [comment]
Developer release 1.921/9701 is available for update through  the /ConfigUpdate_p.html page, or for Debian/Ubuntu users on the https://dl.bintray.com/luccioman/yacy_search_server Debian repository.

**Comment by Perflyst** [comment]
Thanks, will try this tag. Please release a new version @Orbiter, we wanna make yacy great again.

**Comment by luccioman** [comment]
I packaged a new developer release [1.921/9788](https://github.com/luccioman/yacy_search_server/releases/tag/Release_1.921.9788-dev). It is available for update through the `/ConfigUpdate_p.html` page, or for Debian/Ubuntu users on the https://dl.bintray.com/luccioman/yacy_search_server Debian repository.

**Comment by Perflyst** [comment]
Any updates here, please?

**Comment by Velociraptor85** [comment]
Ping

**Comment by danrobi11** [comment]
Please release new commits.
Please release as flatpak. Flatpak are popular and easy to install for non-technical users.
Releasing YaCy as flatpak would be a good way for YaCy to be advertised/exposed. 
Thanks!

**Comment by okybaca** [comment]
version 1.940 released 2024-06, <https://download.yacy.net/>
