### ISSUE TITLE
Crawling wikipedia problem

### ISSUE THREAD

**Issue by kromkachleba** [yacy/yacy_search_server#176]
I have problem with indexing wikipedia - my computer don't have enough RAM memory, and YaCy isn't working properly. Is there a way to stop crawling new subpages, without losing what I've crawled so far? I have about 9 million pages pending in crawler, and if I understand it correctly, pressing "terminate" button will just delete everything. Turning off network connection causes amount of pages pending in crawler decreasing, but it is too slow (10 pages / s) and giving peer no Internet connection makes it useless. If saving pending in crawler pages is impossible, it should be added as a new feature.
I can't register on the forum, so writing here.

**Comment by luccioman** [comment]
Hi @kromkachleba , you can safely use the "terminate" button on a running crawl, it will not remove the already crawled documents from your index.
Additionally, if you don't want to terminate your running crawl you can also adjust memory settings for example, restart your YaCy server and the crawl will be resumed as pending crawler URLs are indeed saved in filesystem.
You may also for example want to delete only a part of running crawl pending URLs using the Local Queues page (at /IndexCreateQueues_p.html?stack=LOCAL ).

One last point:  index deletion is not done in the Crawler monitor page, but rather with the "URL Database Administration" page (at /IndexControlURLs_p.html) or with the "Index Deletion" page (at /IndexDeletion_p.html).

**Comment by luccioman** [comment]
I close this issue, do not hesitate to ask questions on [Gitter](https://gitter.im/yacy/yacy_search_server) while the forum is down, or to open another issue here if necessary.
