### ISSUE TITLE
I can't get it to work on Mac.

### ISSUE THREAD

**Issue by Nic-Wow** [yacy/yacy_search_server#177]
I download YaCy on my Macbook and tried to download it like the video said but found that you need a specific version of Java. I downloaded that here: "https://support.apple.com/kb/DL1572?locale=en_US" and that message went away but whenever I try to go to localhost:8090 it shows this: 
<img width="1274" alt="localhost" src="https://user-images.githubusercontent.com/39070663/39844746-91afb07a-53a6-11e8-90c2-1a0f1d871aca.png">
Has anyone else had this issue? Is there a solution?

**Comment by luccioman** [comment]
Hi @Nic-Wow , the download link you provide seems to be for Java 1.6, which has been deprecated for quite a long time now.
YaCy release 1.92/9000 needs at least a Java 1.7 or higher to run properly. Java 1.7 is also no more supported by Oracle, so to benefit from latest security updates, I recommend you to install a Java 1.8.
At https://java.com you should be able to get an installer for Mac OS X.

**Comment by Nic-Wow** [comment]
@luccioman 

<img width="1278" alt="java" src="https://user-images.githubusercontent.com/39070663/39969976-d373d2ee-5698-11e8-89d8-6a0b7bfeffc8.png">

 Still fails to load.

<img width="1279" alt="errorwwww" src="https://user-images.githubusercontent.com/39070663/39969988-f12e688a-5698-11e8-89f7-ddf303f8d4f7.png">

**Comment by Nic-Wow** [comment]
Update: Still not working. I tried listening to port with the help of some people in the Gitter chat. it came back with no response. I redownloaded it to no avail. I also restarted my computer and it still doesn't work. Am I literally the only person who has had this problem?

**Comment by Nic-Wow** [comment]
Update: Still not working. I tried listening to port with the help of some people in the Gitter chat. it came back with no response. I redownloaded it to no avail. I also restarted my computer and it still doesn't work. Am I literally the only person who has had this problem?

I accidentally closed this issue btw sorry. If it helps at all here is my computer specs:

<img width="582" alt="mac" src="https://user-images.githubusercontent.com/39070663/40203798-3fcc4ff8-59db-11e8-9064-d847423bd12a.png">

**Comment by luccioman** [comment]
Hi @Nic-Wow I just (re)tried installing the YaCy 1.92 dmg on an old Mac OS X (El Capitan) and it started nicely.
I am not sure you are looking for the YaCy DATA folder in the right place... If created when YaCy started, it is supposed to be at <yourUserHome>/Library/Application\ Support/net.yacy.YaCy/DATA. You can search for it through the 'Finder', or for example open the 'Terminal' and type `ls /Library/Application\ Support/`.
If this folder is not there, it is indeed likely the YaCy app failed to start very early.
In the Terminal you can also type `java -version`to do another check of your installed Java version.

Then to get more details about the YaCy startup, still in the Terminal :
* Go inside your YaCy app : `cd <your install directory>/YaCy.app/Contents/MacOS/`
* Start from the terminal :  `./startYACY.sh -d -s "'Library/Application Support/net.yacy.YaCy'"`and check for errors in the messages that are displayed, and eventually share here.

**Comment by okybaca** [comment]
Does it work for you now, in the latest github version? The startup script problem in mac os #574 was fixed  in #597. Did it solve your issue?
