### ISSUE TITLE
Is there a way to properly handle allographs?

### ISSUE THREAD

**Issue by funkyfuture** [yacy/yacy_search_server#180]
allographs are a phenomenon where two different glyphs represent the same phoneme, this depends on typefaces and languages. e.g. gothic typefaces have a 'long s' (`ſ`) that is used for the same phoneme as `s`.

hence, let's say a german user is looking for `erstes` with yacy, s/he will miss occurances of `erſtes` in documents that represent historical sources where this was the valid orthographic form.

is there a way to configure yacy, so it normalizes `ſ` to `s` on indexing and searching?

**Comment by luccioman** [comment]
@funkyfuture you may have a look at the Solr documentation to customize your YaCy peer Solr settings.
There is notably a documentation section dedicated to [Language Analysis](https://lucene.apache.org/solr/guide/6_6/language-analysis.html#language-analysis), or an schema [example](https://github.com/apache/lucene-solr/blob/releases/lucene-solr/6.6.0/solr/example/example-DIH/solr/db/conf/managed-schema#L801) for a German only text field.

**Comment by funkyfuture** [comment]
thanks!
