### ISSUE TITLE
Choose collection in query

### ISSUE THREAD

**Issue by Starkmann** [yacy/yacy_search_server#184]
I want to create a query that only uses one or more specified collection, as far as i understood this can be done via the "site" parameter.
See here:
http://www.yacy-websearch.net/wiki/index.php/Dev:APICrawler

But this works only with gsa api like this:
http://domain.net/gsa/search?q=something&site=collectionFooBar

The problem is i don't want to use gsa i use the opensearch api to get my results. I might change that but for now the results also differ a lot between the two api's given the same search word.

So is it possible to control which collection should be used via opensearch api, or something else *not* gsa?

**Comment by luccioman** [comment]
Hi @Starkmann , on the yacysearch API, you have to use the `collection:` search parameter in you search query to restrict on some collection.
This gives for example : `http://yourdomain/yacysearch.json?query=something+collection:someCollection1+collection:someCollection2`

This search parameter is indeed missing from the Search Parameters [Wiki page](http://www.yacy-websearch.net/wiki/index.php/En:SearchParameters), but you could have found it by using the yacysearch.html search page, and by ticking some Collection check box on left panel on the results page (note that the Collection navigator is only visible in the html results page if it is enabled in your /ConfigSearchPage_p.html).

**Comment by luccioman** [comment]
@Starkmann , I close this issue as I think the proposed solution is sufficient, but don't hesitate to ask if you still need some help.

**Comment by Starkmann** [comment]
Oh yeah. Thank you you helped me. I forgot to answer, sorry.

**Comment by Starkmann** [comment]
I tried it today and it is working, but i see a different behavior between rss and json.
```
/yacysearch.rss?query=test+collection:user+collection:presse
2045 results
/yacysearch.rss?query=test+collection:user
2040 results
Works as expected.
/yacysearch.json?query=test+collection:user+collection:presse
5 results
/yacysearch.json?query=test+collection:user
2040 results
```
It seems that the json interface is only using the last collection parameter:
```
/yacysearch.json?query=test+collection:presse+collection:user
2040 results
```
So basically multiple collections in query are only working with rss interface

Also i have to mention that the rss interface is handling + and ' ' the json don't:
<pre>
/yacysearch.json?query=test collection:presse collection:user
Not working.
/yacysearch.rss?query=test collection:presse collection:user
Working.
</pre>

But that is no big deal because it should be with '+'.

**Comment by paigeadelethompson** [comment]
doesn't work there's no collection: parameter its useless, I can see its a schema field:

collection_sxt [mycollection]

but its not enumerable in a search string using "collection:mycollection" idk who actually tried that but it doesn't work so

**Comment by paigeadelethompson** [comment]
~ah ok, if you search for `collection_sxt:mycollection` that does indeed work~
EDIT: 
it yields results but its not results from the collection.

EDIT:

my mistake you can't search for just "collection:mycollection" you have to specify some other search criteria (other than just filetype:) 

EDIT: somebody should add the field to the advanced search page otherwise nobody will know that they can do that unless they looked at the schema through the index browser and guessed it much be enumerable...
