### ISSUE TITLE
I cannot run Yacy by running startYacy.bat in windows7?

### ISSUE THREAD

**Issue by tangdou1** [yacy/yacy_search_server#185]

**Comment by luccioman** [comment]
Hi @tangdou1 I just retried to launch YaCy on a Windows 7 32 bits virtual machine and it worked fine using the startYacy.bat. 
Can you provide more details on the YaCy and Java versions you have, your installation method, and the eventual errors you may find in your yacy_install_dir/DATA/LOG/yacy00.log?

**Comment by tangdou1** [comment]
I just download the software named "yacy_search_server-master.zip" in github.
My Java version is 8.0.1510.12 in my Window 7(64bit).
DATA floder only has a "yacy.noconsole" file.

**Comment by tangdou1** [comment]
I found there is no yacycore.jar in lib in the project.

**Comment by luccioman** [comment]
Ok @tangdou1 , when you download the zip of the project on GitHub, what you get contains only the sources. To run it, you have then to compile it (see for example the [instructions](https://github.com/yacy/yacy_search_server#how-to-get-the-source-code-and-how-to-compile-yacy-yourself) in the readme.

If you are rather looking for a binary more recent than the 1.92 version, you can take a tar.gz archive from http://kaskelix.de/update/ or from https://github.com/luccioman/yacy_search_server/releases . These archives are not windows installers, but are cross-platform, so once extracted you have everything needed to run on Windows.

**Comment by tangdou1** [comment]
Thanks!
