### ISSUE TITLE
Wix.com sites have # in Url and I am unable to crawl

### ISSUE THREAD

**Issue by smokingwheels** [yacy/yacy_search_server#19]
I think this got closed on mantis bug tracker some time ago.
I would like to crawl www.justiceparty.com.au .
All yacy picks up is the main Url and thats it.
http://www.justiceparty.com.au/#!issues/nxmta is one of the website links which wont crawl.
Thanks in advance.

**Comment by reger24** [comment]
what do you expect as text crawl result of a page with this content ?

<body>
                <div id="SITE_CONTAINER"></div>    
    

    
</body>

**Comment by reger24** [comment]
The Google proposal of the use of hash-bang URLs (as this site does)
to allow g.xx..bot to crawl Ajax sites has been depreciated  
see https://developers.google.com/webmasters/ajax-crawling/

**Comment by reger24** [comment]
crawling of main URL content improved 
9252e36aeb3765ba06d4dcf5543ad2e64c70bd4e

P.S. the official bug tracking is still the mantis site
