### ISSUE TITLE
Crawling minds.com doesn't crawl any pages

### ISSUE THREAD

**Issue by songproducer** [yacy/yacy_search_server#190]
> I 2018/07/27 09:48:40 LoaderDispatcher waited 5000 ms for https://minds.com/
> I 2018/07/27 09:48:42 LOADER CRAWLER Redirection detected ('HTTP/1.1 301 Moved Permanently') for URL https://minds.com/
> I 2018/07/27 09:48:42 LOADER CRAWLER ..Redirecting request to: https://www.minds.com/
> I 2018/07/27 09:48:42 REJECTED https://minds.com/ - cannot load: load error - CRAWLER Redirect of URL=https://minds.com/ aborted. Reason : double in: local index, recrawl rejected. Document date = 2018-07-26T20:14:40Z is not older than crawl profile recrawl minimum date = 2018-07-24T01:48:22Z
>

**Comment by luccioman** [comment]
Hi @songproducer , the log trace you report is not an issue, you will see the same kind of messages when crawling a website with a redirection on its home page.

The real issue with www.minds.com is that all its content is generated with JavaScript (check what is rendered by your browser when JavaScript is disabled). 

You can also check what is found by the YaCy crawler and parsers by using the YaCy /ViewFile.html page : almost no text and only a few links to some icons.

Unfortunately (or not...), the current YaCy internal crawler has no JS rendering engine, so to index this kind of website with YaCy you would for example have to use an external tool to do the crawling and parsing, and then inject the parsed documents to YaCy index (see /api/push_p.json).

**Comment by songproducer** [comment]
Hi @luccioman , thanks for the explanation. I will look into how to crawl and parse using another tool. Is there any guide how to inject the results using /api/push_p.json?

**Comment by luccioman** [comment]
Ok @songproducer , the only guide I am aware of for this api is the related [Wiki page](http://www.yacy-websearch.net/wiki/index.php/Dev:APIpush).
