### ISSUE TITLE
Do you use the chinese word segmentation technique for chinese search?

### ISSUE THREAD

**Issue by tangdou1** [yacy/yacy_search_server#192]
I found that there are few results when I search some long sentence .

**Comment by luccioman** [comment]
Hi @tangdou1 , as far as I know there are currently no language specific word segmentation techniques applied for YaCy search query terms, and I am not 100% sure of the implementation details, but I would say this is the same at indexing time.
 
But would you like to provide some more detailed examples?

**Comment by tangdou1** [comment]
Thanks. I am just a bit curious about it.  It seems that there is no segmentation techinque in YaCy query phase, so I should search by using more key words rather than a sentence.
For chinese word segmentation, there are some good github source.
https://github.com/huaban/jieba-analysis
https://github.com/fxsjy/jieba
