### ISSUE TITLE
blacklist regex expressions not working

### ISSUE THREAD

**Issue by songproducer** [yacy/yacy_search_server#195]
For example when I put in:

epoqonybyn.zeblog.com

It goes in as:
.*.*/.*.*epoqonybyn.zeblog.com.*/.*.*

And the url still shows up in local search results.

**Comment by songproducer** [comment]
I found out what I was doing wrong.
I needed to go like this:
*epoqonybyn.zeblog.com/*

The examples shown:

> 
> The right '*', after the '/', can be replaced by a regular expression.
> 
>     domain.net/fullpath
>     domain.net/*
>     *.domain.net/*
>     *.sub.domain.net/*
>     sub.domain.*/*
>     domain.*/*
>     domain and path regular expressions separated by a '/' (slow)

mislead me. Would be nice to only be shown working examples.

**Comment by luccioman** [comment]
Hi @songproducer , what's wrong with the provided examples? If you enter an entry such as `epoqonybyn.zeblog.com/*` inspired from the examples it is working as expected...

**Comment by songproducer** [comment]
Hi @luccioman ,

the example pattern:
url.domain.com/*

works as expected but I can't get any other regular expressions to work. Eg:
https://github.com/yacy/yacy_search_server/issues/199
