### ISSUE TITLE
Are there no porn blacklists being shared?

### ISSUE THREAD

**Issue by songproducer** [yacy/yacy_search_server#197]
I'm happy to share mine

**Comment by luccioman** [comment]
@songproducer , there is a "Share/don't share this list" button in the /Blacklist_p.html page. So if you share your blacklist, other peers will be able to import it using the /BlacklistImpExp_p.html page.

**Comment by songproducer** [comment]
Thanks. For anyone who wants to import my porn blacklist so far:
https://pastebin.com/QagQU8hi
