### ISSUE TITLE
How to block this url?

### ISSUE THREAD

**Issue by songproducer** [yacy/yacy_search_server#199]
https://www.rbls.org/porn.seks.com

In the blacklist, I've tried:
*porn.seks.com*
but it doesn't get it.

**Comment by luccioman** [comment]
@songproducer , did you try to add the entry `porn.seks.com/*` to your blacklist? It looks like it is working fine.
You may also want to clean up your local index from entries on this host added before blacklisting. You can use for this the Index Deletion (/IndexDeletion_p.html) admin page.

**Comment by songproducer** [comment]
hI @luccioman  I tried that regex, porn.seks.com/* but unfortunately it didn't work. I just manually deleted the https://www.rbls.org/porn.seks.com in the index browser

**Comment by luccioman** [comment]
Ok @songproducer , I was thinking that it was the domain `porn.seks.com` you wanted to block. If you want to block that exact URL `https://www.rbls.org/porn.seks.com`, your blacklist entry can be for example `www.rbls.org/porn.seks.com/*`
