### ISSUE TITLE
Rename repository to yacy-search-server

### ISSUE THREAD

**Issue by krichter722** [yacy/yacy_search_server#20]
It looks much more familiar and is closer to the UNIX standard. Yet it's a lot of work and necessary actions might be postponed until a good occasion.

**Comment by smokingwheels** [comment]
My 2 cents worth
I just recently memorised _ ....
Have you tried it on your server?

**Comment by krichter722** [comment]
>  Have you tried it on your server?

I had a running instance until some weeks ago. Now I'm having trouble starting it. How is that related to my issue?

**Comment by smokingwheels** [comment]
Not sure what you could do but I know you can install it the current version where ever you like and it starts.
I have only been learning #Linux since Apr this year.

**Comment by krichter722** [comment]
Still... How is this related to this issue?

**Comment by smokingwheels** [comment]
I just had A Look at your Git Hub and cant see a Fork for The yacy_search_server.
Why dont you Make a fork and have a go at it your self.
I could help out when I have some spare time.

**Comment by krichter722** [comment]
Because a fork or pull request can't rename the repository.

**Comment by Orbiter** [comment]
not a bug, just an opinion
