### ISSUE TITLE
Docker Image Password Not Working

### ISSUE THREAD

**Issue by Nic-Wow** [yacy/yacy_search_server#207]
I keep using "docker" as the password and "admin" as the username but it just shows the same message. Has anyone else had this issue? I am using Fedora 26 and switched to the docker image as "yacy" wouldn't download. The search engine works but I can't login into administrator.

**Comment by luccioman** [comment]
Hi @Nic-Wow I just checked running new YaCy Docker containers from the images luccioman/yacy:latest and luccioman/yacy:latest-alpine... and admin authentication with the default password just works fine.

Would you like to detail a bit more which command(s) you used to run your container?

And also, what did you mean by "yacy" wouldn't download?

**Comment by frankenstein91** [comment]
as there is no feedback... I will close it

If you still woul like to use docker and yacy... have a look at the docker readme https://github.com/yacy/yacy_search_server/tree/master/docker
