### ISSUE TITLE
lib missing

### ISSUE THREAD

**Issue by linkerlin** [yacy/yacy_search_server#22]
[INFO] ------------------------------------------------------------------------
[INFO] Building YaCy 1.83
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for net.yacy.extlib:J7Zip-modified:jar:1.02 is missing, no dependency information available
[WARNING] The POM for net.yacy.extlib:webcat:jar:0.1 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.811 s
[INFO] Finished at: 2015-11-05T15:45:08+08:00
[INFO] Final Memory: 14M/180M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project yacycore: Could not resolve dependencies for project net.yacy:yacycore:jar:1.83: The following artifacts could not be resolved: net.yacy.extlib:J7Zip-modified:jar:1.02, net.yacy.extlib:webcat:jar:0.1: Failure to find net.yacy.extlib:J7Zip-modified:jar:1.02 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

After I run "mvn install" in the libbuild dir.

**Comment by linkerlin** [comment]
J7Zip-modified is missing from libbuild dir.

**Comment by reger24** [comment]
please run goal
clean install

**Comment by linkerlin** [comment]
mvn clean install
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building YaCy 1.83
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.6.1/maven-clean-plugin-2.6.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.6.1/maven-clean-plugin-2.6.1.pom (5 KB at 1.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/26/maven-plugins-26.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/26/maven-plugins-26.pom (12 KB at 9.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/25/maven-parent-25.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/25/maven-parent-25.pom (37 KB at 32.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.6.1/maven-clean-plugin-2.6.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.6.1/maven-clean-plugin-2.6.1.jar (29 KB at 24.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/net/yacy/extlib/J7Zip-modified/1.02/J7Zip-modified-1.02.pom
[WARNING] The POM for net.yacy.extlib:J7Zip-modified:jar:1.02 is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/net/yacy/extlib/webcat/0.1/webcat-0.1.pom
[WARNING] The POM for net.yacy.extlib:webcat:jar:0.1 is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/net/yacy/extlib/J7Zip-modified/1.02/J7Zip-modified-1.02.jar
Downloading: https://repo.maven.apache.org/maven2/net/yacy/extlib/webcat/0.1/webcat-0.1.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.469 s
[INFO] Finished at: 2015-11-09T15:16:10+08:00
[INFO] Final Memory: 17M/177M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project yacycore: Could not resolve dependencies for project net.yacy:yacycore:jar:1.83: The following artifacts could not be resolved: net.yacy.extlib:J7Zip-modified:jar:1.02, net.yacy.extlib:webcat:jar:0.1: Could not find artifact net.yacy.extlib:J7Zip-modified:jar:1.02 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by reger24** [comment]
**mvn clean**

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building YaCy 1.83
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ yacycore ---
[INFO] Deleting C:\src\maven\yacy-rc1\htroot (includes = [**/*.class], excludes = [])
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install-file (install-webcat-jar) @ yacycore ---
[INFO] pom.xml not found in webcat-0.1-swf.jar
[INFO] Installing yacy-rc1\lib\webcat-0.1-swf.jar to .m2\repository\net\yacy\extlib\webcat\0.1\webcat-0.1.jar
[INFO] Installing mvninstall4951779150574989411.pom to .m2\repository\net\yacy\extlib\webcat\0.1\webcat-0.1.pom
\repository\net\yacy\extlib\J7Zip-modified\1.02\J7Zip-modified-1.02.jar
[INFO] Installing mvninstall7332313264680431681.pom to .m2\repository\net\yacy\extlib\J7Zip-modified\1.02\J7Zip-modified-1.02.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

**Comment by linkerlin** [comment]
I got a new error as below:

[linkerlin@MBA yacy_search_server]$ mvn clean


[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building YaCy 1.83
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ yacycore ---
[INFO] Deleting /Users/linkerlin/gits/yacy_search_server/htroot (includes = [**/*.class], excludes = [])
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install-file (install-webcat-jar) @ yacycore ---
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-utils/0.4/maven-shared-utils-0.4.pom
^C[linkerlin@MBA yacy_search_server]$ pc4 mvn clean
[proxychains] config file found: /Users/linkerlin/.proxychains/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.dylib



[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building YaCy 1.83
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ yacycore ---
[INFO] Deleting /Users/linkerlin/gits/yacy_search_server/htroot (includes = [**/*.class], excludes = [])
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install-file (install-webcat-jar) @ yacycore ---
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-utils/0.4/maven-shared-utils-0.4.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-utils/0.4/maven-shared-utils-0.4.pom (4 KB at 0.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-utils/0.4/maven-shared-utils-0.4.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-utils/0.4/maven-shared-utils-0.4.jar (152 KB at 107.6 KB/sec)
[INFO] pom.xml not found in webcat-0.1-swf.jar
[INFO] Installing /Users/linkerlin/gits/yacy_search_server/lib/webcat-0.1-swf.jar to /Users/linkerlin/.m2/repository/net/yacy/extlib/webcat/0.1/webcat-0.1.jar
[INFO] Installing /var/folders/ys/fsjk2q996wg10nv7365nz0_w0000gn/T/mvninstall9167095049775227153.pom to /Users/linkerlin/.m2/repository/net/yacy/extlib/webcat/0.1/webcat-0.1.pom
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install-file (install-J7Zip-jar) @ yacycore ---
[INFO] pom.xml not found in J7Zip-modified.jar
[INFO] Installing /Users/linkerlin/gits/yacy_search_server/lib/J7Zip-modified.jar to /Users/linkerlin/.m2/repository/net/yacy/extlib/J7Zip-modified/1.02/J7Zip-modified-1.02.jar
[INFO] Installing /var/folders/ys/fsjk2q996wg10nv7365nz0_w0000gn/T/mvninstall7289359530479509634.pom to /Users/linkerlin/.m2/repository/net/yacy/extlib/J7Zip-modified/1.02/J7Zip-modified-1.02.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.736 s
[INFO] Finished at: 2015-11-13T16:44:52+08:00
[INFO] Final Memory: 10M/140M
[INFO] ------------------------------------------------------------------------
[linkerlin@MBA yacy_search_server]$ 
[linkerlin@MBA yacy_search_server]$ 
[linkerlin@MBA yacy_search_server]$ 
[linkerlin@MBA yacy_search_server]$ mvn install
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building YaCy 1.83
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-plugin-gitrevisionnumber:1.0:create (default) @ yacycore ---
[info] GitrevMavenTask: set property branch=''
[info] GitrevMavenTask: set property releaseNr=9495
[info] GitrevMavenTask: set property DSTAMP=20151113
[INFO] 
[INFO] --- templating-maven-plugin:1.0-alpha-3:filter-sources (filter-src) @ yacycore ---
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-plugin-api/2.0.1/maven-plugin-api-2.0.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-plugin-api/2.0.1/maven-plugin-api-2.0.1.jar (9 KB at 2.6 KB/sec)
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 9 resources
[INFO] Source directory: /Users/linkerlin/gits/yacy_search_server/target/generated-sources/java/net/yacy/peers/operation added.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ yacycore ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/linkerlin/gits/yacy_search_server/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ yacycore ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 622 source files to /Users/linkerlin/gits/yacy_search_server/target/classes
[INFO] /Users/linkerlin/gits/yacy_search_server/source/net/yacy/kelondro/data/meta/URIMetadataNode.java: Some input files use or override a deprecated API.
[INFO] /Users/linkerlin/gits/yacy_search_server/source/net/yacy/kelondro/data/meta/URIMetadataNode.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- maven-antrun-plugin:1.8:run (compile-htroot) @ yacycore ---
Downloading: https://repo.maven.apache.org/maven2/org/apache/ant/ant/1.9.4/ant-1.9.4.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/ant/ant/1.9.4/ant-1.9.4.pom (10 KB at 12.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/ant/ant-parent/1.9.4/ant-parent-1.9.4.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/ant/ant-parent/1.9.4/ant-parent-1.9.4.pom (6 KB at 7.4 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/ant/ant-launcher/1.9.4/ant-launcher-1.9.4.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/ant/ant-launcher/1.9.4/ant-launcher-1.9.4.pom (3 KB at 3.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/ant/ant/1.9.4/ant-1.9.4.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/ant/ant-launcher/1.9.4/ant-launcher-1.9.4.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/ant/ant/1.9.4/ant-1.9.4.jar (1972 KB at 490.3 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/apache/ant/ant-launcher/1.9.4/ant-launcher-1.9.4.jar (18 KB at 2.8 KB/sec)
[INFO] Executing tasks

main:
    [javac] Compiling 187 source files
    [javac] warning: [path] bad path element "/Users/linkerlin/.m2/repository/com/drewnoakes/metadata-extractor/2.8.1/xmpcore-5.1.2.jar": no such file or directory
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/Blog.java:81: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]         final String address = sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP());
    [javac]                                                                                    ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/Blog.java:195: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]                 prop.putWiki(sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP()), "mode_page", post.get("content", ""));
    [javac]                                                                                  ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/Blog.java:330: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]             prop.putWiki(sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP()), "mode_entries_" + number + "_page", entry.getPage());
    [javac]                                                                              ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/BlogComments.java:179: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]             prop.putWiki(sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP()), "mode_page", post.get("content", ""));
    [javac]                                                                              ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/BlogComments.java:195: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]                 prop.putWiki(sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP()), "mode_page", page.getPage());
    [javac]                                                                                  ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/BlogComments.java:238: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]                         prop.putWiki(sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP()), "mode_entries_"+count+"_page", entry.getPage());
    [javac]                                                                                          ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/Bookmarks.java:107: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]     	prop.put("address", sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP()));
    [javac]     	                                                                        ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/ConfigBasic.java:154: warning: [deprecation] myPublicLocalIP() in Domains has been deprecated
    [javac]                 host = Domains.myPublicLocalIP().getHostAddress();
    [javac]                               ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/ConfigPortal.java:225: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]         String myaddress = (sb.peers == null) || sb.peers.mySeed() == null || sb.peers.mySeed().getIP() == null ? null : sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP());
    [javac]                                                                                                ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/ConfigPortal.java:225: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]         String myaddress = (sb.peers == null) || sb.peers.mySeed() == null || sb.peers.mySeed().getIP() == null ? null : sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP());
    [javac]                                                                                                                                                                              ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/ConfigRobotsTxt_p.java:47: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]         prop.put("clientname", sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP()));
    [javac]                                                                                    ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/ConfigSearchBox.java:37: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]         String myaddress = sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP());
    [javac]                                                                                ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/CrawlStartScanner_p.java:98: warning: [deprecation] myPublicLocalIP() in Domains has been deprecated
    [javac]                 ip = Domains.myPublicLocalIP();
    [javac]                             ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/CrawlStartScanner_p.java:100: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]                     ip = Domains.dnsResolve(sb.peers.mySeed().getIP());
    [javac]                                                              ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/Load_MediawikiWiki.java:41: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]         String a = sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP());
    [javac]                                                                        ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/Load_PHPBB3.java:41: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]         String a = sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP());
    [javac]                                                                        ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/Messages_p.java:62: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]         final String peerAddress = sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP());
    [javac]                                                                                        ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/Messages_p.java:165: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]             prop.putWiki(sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP()), "mode_message", theMessage);
    [javac]                                                                              ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/Network.java:368: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]                             String ip = seed.getIP();
    [javac]                                             ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/Network.java:409: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]                             prop.put(STR_TABLE_LIST + conCount + "_ssl_ip", seed.getIP());
    [javac]                                                                                 ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/News.java:160: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]                     	link = (seed == null)? "" : "http://" + seed.getPublicAddress(seed.getIP()) + "/Wiki.html?page=" + record.attribute("page", "");
    [javac]                     	                                                                  ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/News.java:164: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]                     	link = (seed == null)? "" : "http://" + seed.getPublicAddress(seed.getIP()) + "/Blog.html?page=" + record.attribute("page", "");
    [javac]                     	                                                                  ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/News.java:183: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]         prop.put("address", sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP()));
    [javac]                                                                                 ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/Status.java:238: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]                 prop.put("peerAddress_address", sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP()));
    [javac]                                                                                                     ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/Surftips.java:280: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]                     url = "http://" + seed.getPublicAddress(seed.getIP()) + "/Wiki.html?page=" + record.attribute("page", "");
    [javac]                                                                 ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/Surftips.java:295: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]                     url = "http://" + seed.getPublicAddress(seed.getIP()) + "/Blog.html?page=" + record.attribute("page", "");
    [javac]                                                                 ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/Table_API_p.java:316: warning: [deprecation] myPublicIP() in serverSwitch has been deprecated
    [javac]                 prop.putHTML("showtable_list_" + count + "_inline_url", "http://" + sb.myPublicIP() + ":" + sb.getPublicPort("port", 8090) + UTF8.String(row.get(WorkTables.TABLE_API_COL_URL)));
    [javac]                                                                                       ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/Table_YMark_p.java:277: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]         prop.put("address", sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP()));
    [javac]                                                                                 ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/ViewProfile.java:172: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]                         prop.putWiki(sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP()),
    [javac]                                                                                          ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/Wiki.java:150: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]             prop.putWiki(sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP()), "mode_page", post.get("content", ""));
    [javac]                                                                              ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/Wiki.java:240: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]                     prop.putWiki(sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP()), "mode_versioning_page", oentry.page());
    [javac]                                                                                      ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/Wiki.java:255: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]             prop.putWiki(sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP()), "mode_page", page.page());
    [javac]                                                                              ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/api/bookmarks/get_bookmarks.java:70: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]         prop.put("display_address", sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP()));
    [javac]                                                                                         ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/api/bookmarks/get_folders.java:35: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]     	prop.put("display_address", sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP()));
    [javac]     	                                                                                ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/api/ynetSearch.java:35: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]                     searchaddress = "http://" + sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP()) + ((searchaddress.length() > 0 && searchaddress.charAt(0) == '/') ? "" : "/") + searchaddress;
    [javac]                                                                                                     ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/goto_p.java:59: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]                 String peersUrl = seed.getPublicAddress(seed.getIP());
    [javac]                                                             ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/mediawiki_p.java:73: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]         prop.putWiki(sb.peers.mySeed().getPublicAddress(sb.peers.mySeed().getIP()), "page", page);
    [javac]                                                                          ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/sharedBlacklist_p.java:121: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]                         final String IP = seed.getIP();
    [javac]                                               ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/yacysearch.java:901: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]         final String hostIP = sb.peers.mySeed().getIP();
    [javac]                                                ^
    [javac] /Users/linkerlin/gits/yacy_search_server/htroot/yacysearch_location.java:76: warning: [deprecation] getIP() in Seed has been deprecated
    [javac]                 String ip = sb.peers.mySeed().getIP();
    [javac]                                              ^
    [javac] 42 warnings
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ yacycore ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/linkerlin/gits/yacy_search_server/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ yacycore ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 21 source files to /Users/linkerlin/gits/yacy_search_server/target/test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/linkerlin/gits/yacy_search_server/test/ViewImagePerfTest.java:[164,52] cannot find symbol
  symbol:   variable ViewImage
  location: class ViewImagePerfTest
[ERROR] /Users/linkerlin/gits/yacy_search_server/test/ViewImageTest.java:[240,47] cannot find symbol
  symbol:   variable ViewImage
  location: class ViewImageTest
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:01 min
[INFO] Finished at: 2015-11-13T16:45:59+08:00
[INFO] Final Memory: 49M/494M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:testCompile (default-testCompile) on project yacycore: Compilation failure: Compilation failure:
[ERROR] /Users/linkerlin/gits/yacy_search_server/test/ViewImagePerfTest.java:[164,52] cannot find symbol
[ERROR] symbol:   variable ViewImage
[ERROR] location: class ViewImagePerfTest
[ERROR] /Users/linkerlin/gits/yacy_search_server/test/ViewImageTest.java:[240,47] cannot find symbol
[ERROR] symbol:   variable ViewImage
[ERROR] location: class ViewImageTest
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by Orbiter** [comment]
can you please tell if the problem still exist. If not, please close the issue.

**Comment by reger24** [comment]
additionally bound install-file to validate phase (for automatic execution without clean)
in case of failure   mvn validate  will explicite execute the validation phase (including install-file)
