### ISSUE TITLE
Binding Properties HTML - java

### ISSUE THREAD

**Issue by hurrgadev** [yacy/yacy_search_server#222]
Hello. I'm embarrassed but I have a question about binding HTML with Java code. How can I bind properties? With which framework is this realized with YaCy? I try to output new properties to the User.html via User.java.
I hope you can help me.

**Comment by luccioman** [comment]
Hi @hurrgadev , in the current YaCy implementation there is no framework involved in automatically binding plain Java objects with HTML pages/templates.

Instead, there is a custom template engine with its own syntax (see the related wiki [page](http://www.yacy-websearch.net/wiki/index.php/Dev:Templates)).

Every html, json, rss or xml file in the `/htroot` folder is indeed a template, fed with the related Java class. So you if you want to modify what is rendered in the User.html page, you have to modify the html itself or eventually the User.java class if necessary (there is also a very simple [sample](http://www.yacy-websearch.net/wiki/index.php/Dev:Samples) in the wiki).

**Comment by hurrgadev** [comment]
Thank you @luccioman , it never worked because I have to make a new build after every change in the Java code. I use Eclipse as my IDE.

**Comment by luccioman** [comment]
Yes the need for an explicit rebuild on any Java code change is a drawback of the current sources configuration. I also use Eclipse and I launch the Apache ant tasks to compile and run/debug YaCy. So except that manually triggering the ant build is a bit annoying, it should also works for you.

**Comment by hurrgadev** [comment]
Thanks, @luccioman . Here is a good video for all people who have problems with the Ant configuration ore to clone from Github. (https://vimeo.com/33071088)
