### ISSUE TITLE
Advanced Config seedScpPassword is visible

### ISSUE THREAD

**Issue by vikulin** [yacy/yacy_search_server#228]
Advanced Config seedScpPassword is visible

**Comment by luccioman** [comment]
@vikulin if I understand you correctly, you mean that when selecting the property "seedScpPassword" in the Advanced Config page at /ConfigProperties_p.html, the problem is that the password appears in clear text in the form value field?

**Comment by vikulin** [comment]
Yes

пт, 14 сент. 2018 г. в 9:18, luccioman <notifications@github.com>:

**Comment by luccioman** [comment]
Fix embedded in developer release 1.921/9788
