### ISSUE TITLE
Why not create lite nodes?

### ISSUE THREAD

**Issue by raisty** [yacy/yacy_search_server#232]
Why you not consider create some more complex database structure to better support network?
I have idea put out some type of "light nodes" to support your network and process more informations.
This nodes can support different structures: onion, eth, etc.
This can be done nicely in our Blockchain era...

**Comment by luccioman** [comment]
@raisty would like to elaborate a bit more your idea? Maybe with an example? I am not sure to tryly understand the features of the nodes you imagine and the eventual relationship with Blockchain technology.

**Comment by raisty** [comment]
Moved to #231
