### ISSUE TITLE
YaCy looks abandoned

### ISSUE THREAD

**Issue by Vort** [yacy/yacy_search_server#236]
Hello.
I have clicked on "BUGS" link at https://yacy.net/, last fix there is from 2017.
Next clicked on "Change Log" link and see that last release was at 2013.
I'm glad all that information is fake, but someone may think other way.
Please guide potential contributors to correct places.

**Comment by r4dh4l** [comment]
Since https://github.com/yacy/yacy_search_server/issues/124 is not fixed for quite a long time now YaCy unfortunately looks very inactive for me.

So the question is: How can we help? Community can not contribute information to the yacy.net main page I think.

**Comment by r4dh4l** [comment]
https://flattr.com/@Orbiter 

> 404
> Sorry, this page isn't available

Hm...

**Comment by r4dh4l** [comment]
Thx @luccioman for this report. Because as far as I noticed there is no other project like YaCy: What about nominating a few people in the community to keep yacy.net up to date?

**Comment by ehehdada** [comment]
it seems for keeping the project moving, the project should be forked until the official maintenance is back and merge from the forked projects, what is the plan or roadmap for the next release? the last one was on December of 2016, 2 years ago.

**Comment by Orbiter** [comment]
The project was heavily moved on with the YaCy Grid re-design - while @luccioman was heavily supporting the 'legacy YaCy' release. It was just not released. YaCy Grid was also not released.
We suggest to check out the latest version from github. "Not having a release" is not a valid sign that the project is not supported any more. Please see for yourself:

legacy YaCy:
https://github.com/yacy/yacy_search_server/commits/master

YaCy Grid:
https://github.com/yacy/yacy_grid_mcp/commits/master
https://github.com/yacy/yacy_grid_parser/commits/master
https://github.com/yacy/yacy_grid_loader/commits/master
https://github.com/yacy/yacy_grid_search/commits/master
https://github.com/yacy/yacy_grid_cluster/commits/master

**Comment by Vort** [comment]
It is not hard to look at latest commit date.
But first of all, user should know where to look.
For example, neither yacy.net nor wiki.yacy.net have any mention of "grid".
It means that (almost) nobody will know about it.
And nobody will help with development.

It looks like @ehehdada is right and only fork can make things moving here.
