### ISSUE TITLE
Blocklist failure for non-english URLs

### ISSUE THREAD

**Issue by Vort** [yacy/yacy_search_server#237]
Hello.
I can't block URLs with Russian characters.
Example: ```en.wikipedia.org/wiki/Special.*``` blocks ```https://en.wikipedia.org/wiki/Special:Search``` fine.
But ```ru.wikipedia.org/wiki/Служебная.*``` fails to block ```https://ru.wikipedia.org/wiki/Служебная:Поиск```.

**Comment by luccioman** [comment]
Hi @Vort I also reproduced your issue.
Waiting for a fix, you can enter the path in its percent-encoded flavor (`ru.wikipedia.org/wiki/%D0%A1%D0%BB%D1%83%D0%B6%D0%B5%D0%B1%D0%BD%D0%B0%D1%8F.*`) and it will work properly.

**Comment by luccioman** [comment]
@Vort , with latest commits, non ASCII characters in blacklist path patterns are now handled more properly. If you wish, you can test it running YaCy from latest sources.

**Comment by Vort** [comment]
Thanks. Looks like it works fine now:
Blacklist: ```uk.wikipedia.org/wiki/Користувач:.*```
Log: ```I 2018/10/10 10:09:36 REJECTED https://uk.wikipedia.org/wiki/Користувач:Леонід_Панасюк - url in blacklist```

URLs are still unreadable in crawl log, but that is another problem:
![yacype](https://user-images.githubusercontent.com/1242858/46718768-e8466400-cc74-11e8-8ca2-ce9fb6f51025.png)
