### ISSUE TITLE
Semi-random crash with OpenJDK 11

### ISSUE THREAD

**Issue by Vort** [yacy/yacy_search_server#241]
When I updated Java from JDK 1.8.0_131 to OpenJDK 11 (build 11+28, 2018-09-25), YaCy started crashing.
Right after restart, YaCy web pages opens fine, but some time later (~ after 10 minutes), opening of http://localhost:8090/ leads to crash.
If I leave it running without opening of pages, it will crash too, but slightly later.

OS: Windows 7 SP1 x64
Version: dev 1.921/9788
Crash log: [hs_err_pid69864.log](https://github.com/yacy/yacy_search_server/files/2437274/hs_err_pid69864.log)

**Comment by luccioman** [comment]
Thanks for reporting this @Vort . 

I also reproduced this issue when running YaCy from latest sources with Oracle JDK 11 64bits on MS windows 10.
Looks like it does not occur when running with Oracle JDK11 on Debian Stretch.

**Comment by luccioman** [comment]
After further analysis, it appears to be a concurrency issue (this explains why that error is quite random) with the custom class loader used to load YaCy template classes. With the JDK 8, the same scenario lead to a graceful exception handling, while with the JDK 11 it unfortunately crashes the whole JVM.

I need more tests on various platforms, but a fix should probably be available soon.

**Comment by luccioman** [comment]
@Vort if you want to test again with latest sources, I pushed a fix.

For your information, in the end I could also reproduce the issue and successfully test the fix when running with JDK 11 on Mac OS and also on Debian Gnu/Linux.

**Comment by Vort** [comment]
No crash after 5 restarts. Thank you.
