### ISSUE TITLE
Server hangs while refreshing Host Browser page

### ISSUE THREAD

**Issue by Vort** [yacy/yacy_search_server#246]
Hello.

There is a problem with saved pages listing: [example link](http://localhost:8090/HostBrowser.html?admin=true&path=https%3A%2F%2Fru.wikipedia.org%2F).
First of all, I have noticed that link count at that page is changing with every refresh.
Next, out of memory exception popped out.
That was happening with 768 MB of Java memory.
Attempt of making server restart failed.

I have terminated Java process, started server, changed memory amount to 1024 MB and tried to reproduce problem once more. Hang happened again.
Here is the video of page refreshes and corresponding memory consumption values.
Looks like we have a memory leak: [video](https://www.youtube.com/watch?v=d_lRPxVdBK0).
_(CPU usage was at 100%, so last minute of recording is lagging)_

Version tested: v1.921_20181026_9812
Log file: [yacy_hang.log](https://github.com/yacy/yacy_search_server/files/2521577/yacy_hang.log)

**Comment by Vort** [comment]
Dump statistics:
![yacy_dump](https://user-images.githubusercontent.com/1242858/47637399-3956c300-db64-11e8-8d0f-0b45ecd88fab.png)

**Comment by luccioman** [comment]
Thanks for the detailed report @Vort

**Comment by luccioman** [comment]
> First of all, I have noticed that link count at that page is changing with every refresh.

@Vort , the link count may vary when you are running a crawl, as URLs waiting in the crawl stack on the domain you are browsing are also counted.

Were you running a crawl each time the error occurred? If so, does it occurs also when you are not running a crawl?

**Comment by Vort** [comment]
> Were you running a crawl each time the error occurred?

No, but I have noticed that this error not happens when URL count is low.
Also it may depends on how many of that URLs are cached.
That's why I used Wikipedia links for test, it usually contains many URLs.
Available memory count is also important.
768 or 1024 MB is a good number for reproducing.

**Comment by luccioman** [comment]
Indeed, URL counts in the Host Browser page are gathered from a dedicated thread within a time frame of 10 seconds maximum. In your example that timeout is probably reached : because of threads interleaving, this can explain why you don't get the same counts on successive calls. And when selecting hosts with less indexed URLs, the timeout is not reached, so the result is deterministic in that case.

I also found an involved code path that may lead to some resource leak. But I will need more tests to conclude if this can trigger out of memory errors, which I did not reproduce for now.

**Comment by luccioman** [comment]
@Vort in the details of your dump, the leak relies in the 20 threads named `AbstractSolrConnector:concurrentDocumentsByQueryNoPrefetch(host_s:"ru.wikipedia.org")"`, each one holding a SolrDocumentList that can not been garbage collected.

On my own tests, the pushed fix solves this. Your feedback on this will be welcome.

**Comment by Vort** [comment]
Refreshed HostBrowser page 30 times and server is still alive.
Memory consumption looks stable:
![performancegraph](https://user-images.githubusercontent.com/1242858/48057722-6b4bd300-e1bd-11e8-81fa-9e6b04599957.png)
Thanks for the fix.
