### ISSUE TITLE
Review of the current opened PRs

### ISSUE THREAD

**Issue by ivanhercaz** [yacy/yacy_search_server#247]
Hi everyone,
I am not part of the core team, just a contributor, but there are some PRs with inactivity from many time ago, some of them probably have conflicts with the current code. So I want to propose this issue in order to help to have a good and clean environment to collaborate. It isn't directly related with the search server, but I think the issue and PR tracker are important too.

At this moment there are 8 pull requests opened. I consider the next six PRs might be reviewed to clean PRs that should be closed or to encourage the reactivation of them with some interested to someone yet.

- #159. Easy to solve and probably necessary if the core team of YaCy wants to use Gitter to communicate with the collaborators and other people interested in YaCy.
- #157. I understand by the last message of @luccioman that the PR might be closed, unless the idea is to keep it as a reminder for a future application of what the PR would change.
- #151. Idem as 157.
- #91. Many time without the answer of any interested in the point 1 of this PR.
- #77. Seems old and inactive, the same as the repository related with the PR, [pyYaCySim](https://github.com/JeremyRand/pyYaCySim).
- #60. Seems old, inactive and never has an answer nor feedback by anybody. Now it has conflicts with current code.

Please, keep in mind my main intention with this issue. I'm not requesting the close of the PRs mentioned, just to discuss if it should be closed or not in order to keep clean the PR tracker. I don't know what is the methodology of the core team of YaCy with this cases, and this is another reason of this issue.

**Comment by luccioman** [comment]
Hi @ivanhercaz , you are right this is time for some cleaning in Pull Requests (but personally I won't have time for this immediately).

About the methodology : as far as I now, contrary to what one can see on some other free software projects, there are no formal rules about the lifetime of a PR here. I am not sure this is really necessary considering the rate of PR openings and the number of currently regularly active contributors.

**Comment by ivanhercaz** [comment]
> but personally I won't have time for this immediately

Don't worry! I understand that everyone, myself included, collaborate in this project and in many others everything we can according to our free time. For that, again, don't worry!

> as far as I now, contrary to what one can see on some other free software projects, there are no formal rules about the lifetime of a PR here.

No, I didn't claimed to set the lifetime of a PR, I only want to comment the periods of inactivity to value the PR and decide if it should be closed or encourage its reactivation. 

> I am not sure this is really necessary considering the rate of PR openings and the number of currently regularly active contributors.

No, I don't suggest a rate of PR openings, with "At this moment there are 8 pull requests opened. I consider the next six PRs" what I did is to count and give the stats.

I understand you say "and the number of currently regularly active contributors" due what I commented about #77; if it is due my comment, excuse me because I may explained incorrectly. What I wanted to say it is that the PR seems to be made to accomplish with a feature that needs another repository for an enhancement. I am not a java developer and probably I won't contribute to the YaCy code, so my comments aren't based on if the PR will be useful to merge, to reactive or something else. For that I decided to make this issue, because what I feel I can do is to encourage to review this because I feel it needs to be reviewed. In my opinion, only the developers involved in the YaCy development can decide about the PRs. If I will know more java or if I would be involved in its development, I will suggest the closing or whatever, but it isn't the case.

Excuse me if I didn't explain fine what I wanted to say. I hope at least the issue will be useful when you or someone have time to check the PRs.

**Comment by luccioman** [comment]
No problem, for me that's great you took some time to read and synthesize the situation of opened PRs.

**Comment by okybaca** [comment]
Closing as solved, as all the mentioned PRs are closed.
