### ISSUE TITLE
Weird glitch at NetworkPicture

### ISSUE THREAD

**Issue by Vort** [yacy/yacy_search_server#248]
Opened Network.html today and saw that peer chart have a glitch.
Right clicked it and opened in new tab:
![networkpicture_bad](https://user-images.githubusercontent.com/1242858/47953818-38ba9400-df8b-11e8-9e0f-0ae72287a949.png)
After ~1 minute it became correct:
![networkpicture_good](https://user-images.githubusercontent.com/1242858/47953826-5daf0700-df8b-11e8-8c2b-b62edd33b8a4.png)

**Comment by Vort** [comment]
Similar thing again:
![gl](https://user-images.githubusercontent.com/1242858/48073500-90edd200-e1e7-11e8-9620-103eabdd73b6.png)

**Comment by luccioman** [comment]
@Vort I found and fixed a concurrency issue affecting images rendering. Not 100% sure this was the only possible cause of glitch you describe here, so don't hesitate to report if it happens again.

**Comment by Vort** [comment]
Thank you.
As this glitch is random, I will close issue and reopen if bug show up again.
