### ISSUE TITLE
Corrupted database?

### ISSUE THREAD

**Issue by GitHubGeek** [yacy/yacy_search_server#25]
After a power outage, my yacy instance can no longer start. The CPU usages would max out at 100% and unable to connect to web admin. Is there a way to repair the database?

Happy to provide log files but not sure which one to upload.

**Comment by sixcooler** [comment]
Hi,
There should be some information at DATA/LOG/yacy00.log why your peer doesn't come up correctly.
I guess you have a better chance pasting that into the forum http://forum.yacy-websuche.de/, having more eyes watching at it.
Cu, sixcooler.

**Comment by Orbiter** [comment]
seems outdated. To fix anything, at least the log extract is required. As long as no log is proveded, this won't fix.
