### ISSUE TITLE
unable to set admin password on yacy-search snap

### ISSUE THREAD

**Issue by popey** [yacy/yacy_search_server#254]
I was super excited to see the [yacy-search snap](https://snapcraft.io/yacy-search) in the snap store. I installed it on my home server and ran it. I am able to perform searches :tada:

However I'm unable to access the admin page as I cannot set the password via `/bin/passwd.sh`. I suspect you may need to expose the passwd.sh binary outside the snap via an `apps:` `command:` stanza, which has the necessary environment setup to be able to poke the right API in yacy to set the admin password.

I work on Snaps for Canonical and would love to help @luccioman or anyone else on the team out to debug and sort this issue out. I would love to be able to install a fully functional yacy snap, and indeed promote it for Linux users too.

**Comment by luccioman** [comment]
Hi @popey , thank you very much for your feedback. 

I am aware of the issue with admin password setting in this YaCy snap (as far as I know only when accessing your YaCy server remotely and not through localhost), indeed that is why I let it in the edge channel until now. And recently I was a little busy with other issues that had a higher priority to my mind (notably JDK11 compatibility and gzip encoding issue on index transfer api).

But I did not forget the yacy snap, and the solution you suggest is probably what should to be applied. I will probably have some time to check this in the coming days, but if you wish to create a pull request with your own solution you are welcome.

**Comment by luccioman** [comment]
Hi @popey , if you wish you can refresh your yacy-search snap, a working passwd command is now included.

One more thing : YaCy data is currently written to `$SNAP_USER_DATA`. As you are experienced with snaps, and considering that YaCy data can quickly grow to more than 1 GByte but the structure do not often change, would you advise to store it in `$SNAP_USER_COMMON` instead, even if by doing so rollback of data would be no more available?

**Comment by luccioman** [comment]
Additionally a Snap configuration key (`data.versioned`) is now available to control whether the YaCy snap should use versioned data (default) or not.
