### ISSUE TITLE
Links to local kiwix instance not parsed correctly

### ISSUE THREAD

**Issue by bugsug** [yacy/yacy_search_server#256]
Kiwix (https://kiwix.org) serves a few wikis in a local network from my Raspberry Pi.  To make them generally searchable, I downloaded YaCy Version 1.92/9000 and it runs using Java Version 1.8.0_181 on top of Raspbian on the same Raspberry Pi. I set YaCy to the intranet indexing mode and started a crawl on this url: http://[IP ADRESS]/archlinux_en_all/A/Wget.html .

This does not work because YaCy does not parse the containing urls correctly. It leaves out the protocol and the IP address, and the outputted local addresses are after the following scheme: file:///path/to/the/document which is wrong.

![yacy link parser error](https://user-images.githubusercontent.com/38018690/49029235-6cf92d00-f1a4-11e8-9445-640d966263e1.png)

This causes two problems:
* the extracted urls cannot be visited because they are wrong (there is no document at these paths)
* YaCy denies to crawl the subpages because they do not have the same origin: FINAL_LOAD_CONTEXT url does not match must-match filter (smb|ftp|https?)://(www.)?(\Q[IP ADDRESS]\E.*)

Thanks in advance for processing my issue!

**Comment by bugsug** [comment]
And here is the code of http://[IP ADRESS]/archlinux_en_all/A/Wget.html:

<html><head><link type="text/css" href="/skin/jquery-ui/jquery-ui.min.css" rel="Stylesheet" />
<link type="text/css" href="/skin/jquery-ui/jquery-ui.theme.min.css" rel="Stylesheet" />
<link type="text/css" href="/skin/taskbar.css" rel="Stylesheet" />
<script type="text/javascript" src="/skin/jquery-ui/external/jquery/jquery.js"></script>
<script type="text/javascript" src="/skin/jquery-ui/jquery-ui.min.js"></script>
<script>
  var jk = jQuery.noConflict();
  jk(function() {
  jk( "#kiwixsearchbox" ).autocomplete({

  source: "/suggest?content=archlinux_en_all",
  dataType: "json",
  cache: false,

  select: function(event, ui) {
  jk( "#kiwixsearchbox" ).val(ui.item.value);
  jk( "#kiwixsearchform" ).submit();
  },

  });
  });

  /* cybook hack */
  if (navigator.userAgent.indexOf("bookeen/cybook") != -1) {
  	jk("html").addClass("cybook");
  }
</script>
<base href="/archlinux_en_all/A/Wget.html" />
    <meta charset="UTF-8">
    <title>Wget</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script>
        function importScript(){return 1} // this is to avoid the error from site.js
    </script>
    <link rel="stylesheet" href="../-/s/style.css">
    
  </head>
  <body class="mw-body mw-body-content mediawiki mw-parser-output" style="background-color: white; margin: 0; border-width: 0px; padding: 0px;"><span class="kiwix">
  <span id="kiwixtoolbar" class="ui-widget-header">
    <div class="kiwix_centered">
      <div class="kiwix_button_wrapper">
        <a id="kiwix_serve_taskbar_library_button" href="/"><button>&#x1f3e0;</button></a>
        <a id="kiwix_serve_taskbar_home_button" href="/archlinux_en_all/"><button>ArchWiki</button></a>
        <a id="kiwix_serve_taskbar_random_button" href="/random?content=archlinux_en_all"><button>&#x1F3B2;</button></a>
      </div>
      <div class="kiwix_searchform">
        <form class="kiwixsearch" method="GET" action="/search" id="kiwixsearchform">
          <input type="hidden" name="content" value="archlinux_en_all" />
          <input autocomplete="off" class="ui-autocomplete-input" id="kiwixsearchbox" name="pattern" type="text">
          <input type="submit" value="&#x1f50d;">
        </form>
      </div>
    </div>
  </span>
</span>
<div style="display: block; height: 5em;"></div>

    <div id="content" class="mw-body" style="padding: 1em; border-width: 0px; max-width: 55.8em; margin: 0 auto 0 auto">
      <a id="top"></a>
      <h1 id="titleHeading" style="background-color: white; margin: 0;">Wget</h1>
      <div id="mw-content-text" style="direction: ltr;">



<p id="mwBQ"><a href="http://www.gnu.org/software/wget/" id="mwBg">GNU Wget</a> is a free software package for retrieving files using HTTP, HTTPS and FTP. It is a non-interactive commandline tool, so it may easily be called from scripts.</p>

<h2 id="Installing">Installing</h2>
<p id="mwBw">Install the <span class=" archwiki-template-pkg" id="mwCA"><a href="https://www.archlinux.org/packages/?name=wget">wget</a></span> package. The git version is present in the AUR by the name <span class=" archwiki-template-pkg" id="mwCQ"><a href="https://aur.archlinux.org/packages/wget-git/">wget-git</a></span><sup id="mwCg"><small>AUR</small></sup>.</p>

<h2 id="Configuring">Configuring</h2>
<p id="mwCw">Configuration is performed in <code id="mwDA">/etc/wgetrc</code>. Not only is the default configuration file well documented; altering it is seldom necessary. See the man page for more intricate options.</p>

<h3 id="FTP_automation">FTP automation</h3>
<p id="mwDQ">Normally, <a href="SSH.html" title="SSH" id="mwDg">SSH</a> is used to securely transfer files among a network. However, FTP is lighter on resources compared to scp and <a href="Rsync.html" title="Rsync" id="mwDw">rsyncing</a> over SSH. FTP is not secure, but when transfering large amounts of data inside a firewall protected environment on CPU-bound systems, using FTP can prove beneficial.</p>
<pre id="mwEA">wget ftp://root:somepassword@10.13.X.Y//ifs/home/test/big/"*.tar"

3,562,035,200 74.4M/s   in 47s
</pre>
<p id="mwEQ">In this case, Wget transfered a 3.3 G file at 74.4MB/second rate.</p>

<p id="mwEg">In short, this procedure is:</p>
<ul id="mwEw"><li id="mwFA">scriptable</li>
<li id="mwFQ">faster than ssh</li>
<li id="mwFg">easily used by languages than can substitute string variables</li>
<li id="mwFw">globbing capable</li></ul>

<h3 id="Proxy">Proxy</h3>
<p id="mwGA">Wget uses the standard proxy environment variables. See: <a href="Proxy_settings.html" title="Proxy settings" id="mwGQ">Proxy settings</a></p>

<p id="mwGg">To use the proxy authentication feature:</p>
<pre id="mwGw">$ wget --proxy-user "DOMAIN\USER" --proxy-password "PASSWORD" URL</pre>

<p id="mwHA">Proxies that use HTML authentication forms are not covered.</p>

<h3 id="pacman_integration">pacman integration</h3>
<p id="mwHQ">To have <a href="Pacman.html" title="Pacman" id="mwHg">pacman</a> automatically use Wget and a proxy with authentication, place the Wget command into <code id="mwHw">/etc/pacman.conf</code>, in the <code id="mwIA">[options]</code> section:</p>
<pre id="mwIQ">XferCommand = /usr/bin/wget --proxy-user "domain\user" --proxy-password="password" --passive-ftp -q --show-progress -c -O %o %u</pre>
<div class="archwiki-template-box archwiki-template-box-warning" id="mwIg"><strong>Warning:</strong> be aware that storing passwords in plain text is not safe. Make sure that only root can read this file with <code>chmod 600 /etc/pacman.conf</code>.</div>

<h2 id="Usage">Usage</h2>
<p id="mwIw">This section explains some of the use case scenarios for Wget.</p>

<h3 id="Basic_usage">Basic usage</h3>

<p id="mwJA">One of the most basic and common use cases for Wget is to download a file from the internet.</p>

<pre id="mwJQ">$ wget &lt;url&gt;</pre>

<p id="mwJg">When you already know the URL of a file to download, this can be much faster than the usual routine downloading it on your browser and moving it to the correct directory manually. Needless to say, just from the simplest usage, you can probably see a few ways of utilising this for some automated downloading if that's what you want.</p>

<h3 id="Archive_a_complete_website">Archive a complete website</h3>
<p id="mwJw">Wget can archive a complete website whilst preserving the correct link destinations by changing absolute links to relative links.</p>

<pre id="mwKA"><span id="mwKQ">$ wget -np -r -k 'http://your-url-here'</span></pre><div><div style="clear:both; background-image:linear-gradient(180deg, #E8E8E8, white); border-top: dashed 2px #AAAAAA; padding: 0.5em 0.5em 0.5em 0.5em; margin-top: 1em; direction: ltr;">
    This article is issued from
    <a class="external text" title="last edited on 2018-07-14" href="https://wiki.archlinux.org/index.php/Wget?oldid=529595">Archlinux</a>.
    The text is licensed under <a class="external text" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons - Attribution - Sharealike</a>.
    Additional terms may apply for the media files.
</div>
</div></div>
    </div>
    <script src="../-/j/js_modules/jsConfigVars.js"></script>
    <script src="../-/j/js_modules/startup.js"></script>
<script src="../-/j/js_modules/jquery.js"></script>
<script src="../-/j/js_modules/mediawiki.js"></script>
<script src="../-/j/js_modules/site.js"></script>
  

</body></html>

**Comment by bugsug** [comment]
Thanks for the fast response, I will answer it later or tomorrow because I have no time at the moment

**Comment by bugsug** [comment]
The local links in these webpages are mainly relative links (see the code posted above). Here I will give you an example:

`<a href="SSH.html" title="SSH" id="mwDg">SSH</a>`

When I click on it, it forwards me to "http://[IP ADDRESS / HOSTNAME]/archlinux_en_all/A/SSH.html" so everything works well in the browser (in my case, Firefox 63.0.3).

The problem is not that the crawling is limited to the same origin, but that YaCy makes errors in parsing the relative links. YaCy does not convert `<a href="SSH.html"` ... to "http://[IP ADDRESS / HOSTNAME]/archlinux_en_all/A/SSH.html", but converts it to "file:///archlinux_en_all/A/SSH.html" which is not correctly parsed and not a valid path. It adds the two folders "archlinux_en" and "A" to the relative link which is correct, but it misses the protocol (in this case: http) and the domain (int his case: IP address / hostname).

Thanks for your help!

**Comment by bugsug** [comment]
There is no problem crawling a static webpage (does also contain relative links) hosted on the same Rapberry Pi using apache2 as webserver.

Maybe the problem lies in the interaction between YaCy's website parser and the webserver implementation of Kiwix, integrated using the C library libmicrohttpd (https://www.gnu.org/software/libmicrohttpd/).

**Comment by luccioman** [comment]
Ok @bugsug , I had a try with [Kiwix-serve](http://wiki.kiwix.org/wiki/Kiwix-serve/fr) instructions, a YaCy server running from latest sources and the French WikiVoyage zim archive... and I reproduce exactly the same issue as you.
It looks like the origin of the problem is that in each wiki page a base tag is provided with an URL without scheme, for example : `<base href="/wikivoyage_fr_all_nopic_2018-06/A/Accueil.html" />`. YaCy currently does not properly interpret it and adds the `file://` scheme to the base URL when following relative links...

**Comment by bugsug** [comment]
Thank you very much for helping me!

How difficult would it be to fix the error?

**Comment by luccioman** [comment]
@bugsug the fix itself is probably rather simple : in the [ContentScraper](https://github.com/yacy/yacy_search_server/blob/master/source/net/yacy/document/parser/html/ContentScraper.java#L748) class, when a `<base>` tag is encountered with a relative `href` attribute, the base URL should be resolved against its fallback base URL already found in the `root` attribute.
But sufficient tests and careful HTML specs checking should be done for a proper and long term fix. I plan to do this soon but had not enough time for now. I you want to contribute you are welcome.

**Comment by bugsug** [comment]
Thank you very much! I think I would have tried to solve it if nobody else had done it, but I'm also satisfied when somebody else fixes the error.

I think you could do it way faster than me because you are already familiar with the project structure and the source code. But if you need some help you could reach out to me, maybe I can manage to support you if I find some spare time alongside the other projects I'm working on.

**Comment by luccioman** [comment]
@bugsug if you want to have a look the fix is available on latest GitHub sources, and packaged on that Docker [image](https://hub.docker.com/r/luccioman/yacy/).

**Comment by bugsug** [comment]
Great, thank you very much! I will test the fix during the next time and report about my results in this thread.

**Comment by bugsug** [comment]
It works! Thanks you very much! You can close this issue now.

I built YaCy on my machine (it finished within 39 seconds) and now it's indexing my local Kiwix instance on my Raspberry Pi (YaCy is also running on the pi).
