### ISSUE TITLE
doubt of privacy

### ISSUE THREAD

**Issue by John3** [yacy/yacy_search_server#263]
Sorry to ask this question here, but not sure where to ask, I'm new using yacy.

If I search with yacy all my search go through yacy nodes over text plane? Everyone would know what I are searching for?

What features have yacy to have a better privacy for user? Is it possible can be tracked you through your search?

**Comment by luccioman** [comment]
Hi @John3,
here are some answers from my own knowledge of YaCy.

When you install YaCy it is set as a default to run in peer to peer mode ("Community-based web search" option in the `/ConfigBasic.html` administration page).

In this mode, each time you search for something, your search terms are sent only to a selection of YaCy peers (not all peers). 

Your search requests are encoded, but not strongly encrypted as a default. So if someone is sniffing your network it may monitor what you are searching for. 

When a search request reaches a YaCy peer, some information about it is logged on that peer (see administration page `/AccessTracker_p.html?page=4` on your own peer), but not the clear text search terms. Of course nothing prevent someone to hack its own YaCy peer and track more of each incoming request that reach it. But no single peer is able to monitor and track all requests from another given peer.

To get a higher level of privacy on your search requests, here are a few things you can do :
 - activate the "Remote search encryption" setting (`/ConfigPortal_p.html` administration page), to prevent passive eavesdropping. Effect is limited to communications with YaCy peers that have enabled SSL/TLS. You need to upgrade to a more recent version thant 1.92/9000.
 - check the referer policy settings (`/Settings_p.html?page=referrer` administration page), to prevent leaking search requests through the Referer http header when opening results links. You need to upgrade to a more recent version thant 1.92/9000.
 - clear your browser history when closing your session especially if you share your computer with other users, as search terms are passed as GET parameters of the yacysearch.html URL and consequently appear in your history
 - search only your own peer local index if you really don't want your search terms to go on the network. For that use the "only the local index" option on the index page or the "Privacy"/"Stealth mode" switch on the search results page. Of course this only makes sense if you already have something indexed on your own peer. For that you must for example have run YaCy for some time to get some parts of the globally distributed index, or crawled some websites, or imported an index dump.

**Comment by yegortimoshenko** [comment]
> activate the "Remote search encryption" setting (/ConfigPortal_p.html administration page), to prevent passive eavesdropping. Effect is limited to communications with YaCy peers that have enabled SSL/TLS. You need to upgrade to a more recent version thant 1.92/9000.

I mean, that only affects a completely passive eavesdropper, such as ISP. Anyone can still host a YaCy node that will listen on people's queries.

**Comment by yegortimoshenko** [comment]
Unless I'm misunderstanding how YaCy works, I think it's important to communicate these implications [in the FAQ](https://wiki.yacy.net/index.php/En:FAQ#Will_running_YaCy_jeopardize_my_privacy.3F) so that users are aware of the risks of making search queries over clearnet.

**Comment by luccioman** [comment]
> It seems as if anyone can host a YaCy node that will listen on people's queries

@yegortimoshenko , a given YaCy node can only monitor the search queries that reach it, and this is only a small part (the fraction depends on the size of the network) of all the search queries performed over the YaCy network.

But to my mind, if privacy on search activities really really matters, one should not blindly trust YaCy or any other privacy enhancing technology : in that case unplug your network on search only you local data. And even in that case, you still have to trust your OS for not hiding some backdoor and your hardware for not embedding some spy chip...

**Comment by luccioman** [comment]
As far as I know the peers selection algorithm, the presence of popular search terms in a given peer does not increase its chances to be reached by other searches. Indeed the selection algorithm even includes some amount of randomness. 
But in the end, of course a peer increases its chances to be reached by running 24 hours a day with a fast network connection. And by running more than one peer you also increase chances to be reached.
