### ISSUE TITLE
Connect to community

### ISSUE THREAD

**Issue by Perflyst** [yacy/yacy_search_server#268]
As some of you may noticed we created some bridges to bring community together.
The gitter channel is bridged to matrix at `#yacy:yuhu.ddns.net`. Than we also have a bridge to freenode on `#snopyta-yacy`. 

There we also have a release and commit bot. Feel free to join these rooms, lets push YaCy more! @luccioman maybe we can add the matrix room to the readme? You can also use the matrix.org link for it: `#yacy:matrix.org` (the room itself has much more local addresses).

P.S.: 
If anyone knows the owner of `#yacy` on freenode please contact and redirect to this issue, would be better if we can bridge also this channel because some people are still in `#yacy`.

**Comment by luccioman** [comment]
@Perflyst what URL would you suggest for a matrix room link in the readme? `https://matrix.to/#/#yacy:matrix.org`?

**Comment by Perflyst** [comment]
Yes, this should be the best url.

**Comment by luccioman** [comment]
Added to the Contact section of the Readme.
