### ISSUE TITLE
Silently exits when crawling after 1-2 minutes

### ISSUE THREAD

**Issue by brantg** [yacy/yacy_search_server#270]
If you just use it for searching peers it works indefinitely (or at least I left it overnight and had no trouble).  But as soon as I crawl anything it runs great for between 1-2 minutes and then just simply terminates as if it has been asked to gracefully exit.  Nothing abnormal noted in the logs, nothing anywhere I can find.

Java:
```
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-2~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```

Machine:
```
 OS: Debian 9.6 stretch
 Kernel: x86_64 Linux 4.9.0-8-amd64
 Uptime: 16h 39m
 Packages: 489
 Shell: zsh 5.3.1
 CPU: Intel Xeon CPU E5-2620 v4 @ 2.1GHz
 RAM: 141MiB / 996MiB
```

git status:
```
 % git status
On branch master
Your branch is up-to-date with 'origin/master'.
```

Last few lines of the yacy00.log:
```
I 2019/01/17 14:07:51 LOADER CRAWLER Redirection detected ('HTTP/1.1 301 Moved Permanently') for URL https://99u.com/robots.txt
I 2019/01/17 14:07:51 LOADER CRAWLER ..Redirecting request to: http://99u.adobe.com/robots.txt
I 2019/01/17 14:07:51 org.apache.solr.core.QuerySenderListener QuerySenderListener sending requests to Searcher@56574954[collection1] main{ExitableDirectoryReader(UninvertingDirectoryReader(Uninverting(_1f(6.6.5):C615) Uninverting(_1e(6.6.5):C10) Uninverting(_1g(6.6.5):C21) Uninverting(_1h(6.6.5):C42) Uninverting(_1i(6.6.5):C62) Uninverting(_1j(6.6.5):C12) Uninverting(_1k(6.6.5):C13) Uninverting(_1l(6.6.5):C5)))}
I 2019/01/17 14:07:51 org.apache.solr.core.QuerySenderListener QuerySenderListener done.
```

**Comment by luccioman** [comment]
Hi @brantg , if you start your YaCy server as a foreground process (`-f` option with the `startYACY.sh` script) maybe you have some additional messages in your console before the termination?

**Comment by brantg** [comment]
Brilliant, thank you @luccioman, that worked and let me catch the root cause, the output now ends on the console with this:
```
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007f3ad7440000, 65536, 1) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 65536 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /mnt/yacy/yacy_search_server/hs_err_pid25701.log
[thread 139889959687936 also had an error]
[thread 139889961793280 also had an error]
#
# Compiler replay data is saved as:
# /mnt/yacy/yacy_search_server/replay_pid25701.log
```
I'll see what I can do about reconfiguring the VM to provide more memory and try again.  Puzzled why it didn't simply log an out of memory error, though.

**Comment by brantg** [comment]
Thank you @luccioman, I can confirm root cause was running out of memory.  I hadn't bothered with adding swap to the VM and that appears to have been my mistake - I added a swap volume and now YaCy is working just fine.  I appreciate the advice!

**Comment by luccioman** [comment]
Great @brantg and thank you for reporting the root cause. I also encountered this kind of issue when running on a virtual machine without enough memory. And the error does not appear in YaCy logs as these ones are written only when the JVM is still alive, and in that case the crash is likely too abrupt.
