### ISSUE TITLE
problems in crawling in yacy

### ISSUE THREAD

**Issue by remyagrr** [yacy/yacy_search_server#272]
i try to crawl "https://www.tpbazaar.com" , but get error
Unable to download resource content.
error loading resource: java.io.IOException: Client can't execute: Received fatal alert: handshake_failure duration=191 for url https://www.tpbazaar.com/
can you help me

**Comment by luccioman** [comment]
Hi @remyagrr , to properly crawl that website it looks like TLS [Server Name Indication - SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) must be enabled on your YaCy node.
This is configured by a JVM wide parameter : `-Djsse.enableSNIExtension=true`. If for example you run YaCy on a Unix, you can set it in the [JAVA_ARGS](https://github.com/yacy/yacy_search_server/blob/d3a114c7a9942edfb2e53af4e35e6597f520d633/startYACY.sh#L9) of `startYACY.sh` script.

**Comment by luccioman** [comment]
How do you start your YaCy server? I tested with a Java 8 JVM, on Windows 10 and Debian Stretch. With the option set to false I get the same error as you, while the crawl is successful when set to true.

**Comment by remyagrr** [comment]
i want a json like this {
"Parsed Text":{
 
"Text":"Posts - TPBazaar.com - Technopark Classifieds Forum - Buy&#124;Sell&#124;Discuss anything in Technopark/Infopark/Technocity!",
"Text":"Welcome to the new version of tpbazaar.com, for older data, please.",
"Text":"click Here for any help /support - mail to.",
"Text":"[email protected] Toggle navigation.",

......,
"Text":""
}}

and code of json is 
{
"Parsed Text":{
#(viewMode)# 
#{sentences}#"Text":"#[text]#",
#{/sentences}#  
#(/viewMode)#
}
}

how to remove the comma of last line

**Comment by luccioman** [comment]
With commit a5771b1, Server Name Indication extension support can be configured without the need for YaCy server restart, in the new admin page at /Settings_p.html?page=httpClient.
