### ISSUE TITLE
Does YaCy support plugins?

### ISSUE THREAD

**Issue by lonnieOST** [yacy/yacy_search_server#279]
Hello,

This is really more of a question, but I am wondering if YaCy has the ability to support plugins?

The reason that I ask is because I was wondering if YaCy can take the query from the user, sent it off to another data source like a JSON/XML search (or metasearch) engine, receive the results that are aggregated as well as stored in the YaCy database and then return the results to the user.

I think that a plugin could be written to handle some of this, but did not know if YaCy already may have some of this functionality in its current state.

Any thoughts on this would be helpful.

**Comment by luccioman** [comment]
Hi @lonnieOST , yes indeed there is even a specification to integrate search systems more easily : [OpenSearch](http://www.opensearch.org). 

Yacy already has some support for it, through the Heuristics configuration page at `/ConfigHeuristics_p.html` (see notably the "opensearch load external search result list from active systems below " checkbox and the table below). 

There are however some limitations :
- the target system must accept crawl of its search results by YaCy or bots in general (check its robots.txt configuration)
- YaCy currently only supports RSS as response format, not JSON or XML (HTML responses may eventually be supported with an additional mapping configuration file such as the example provided for [npmjs](https://github.com/yacy/yacy_search_server/blob/master/defaults/federatecfg/npmjs.html.map.properties).

**Comment by lonnieOST** [comment]
Thanks,

What I had in mind is being able to make a query that would be sent to an external data feed that would return results which would then be added to the YaCy data store. In this way, YaCy would also act as a cache to store trending searches.

Just a thought though :)

**Comment by lonnieOST** [comment]
Just so that you will know, I was thinking in terms of something that would allow me to inject fields right into the YaCy data store that were coming from a type of metasearch server so that the query sent to that server would produce some URL, Title, Description, etc.. fields that could be loaded, in real-time into YaCy and returned to the calling node.

This would provide nodes a way to directly "import" website data without having to "crawl" each website as the metasearch server has already done this in many cases.

Any ideas on this would be greatly appreciated.

**Comment by luccioman** [comment]
@lonnieOST what you describe is roughly what happens in YaCY when results are fetched from a search URL configured in `ConfigHeuristics_p.html`. What is probably mainly missing for you is support for more data formats. If you don't want to write code, a tool like [RSS-Bridge](https://github.com/RSS-Bridge/rss-bridge) may help you.

**Comment by lonnieOST** [comment]
Thanks for the feedback on this and I will look into it.

Actually, what I have is a JSON/XML feed coming from an external type of metasearch engine with results from any query that I send it.

I was hoping to be able to take the query given the the YaCy frontend and pipe it to the external metasearch engine to receive the JSON/XML results back to the YaCy node and then store them directly in the data P2P data store so that they could be utilized in future similar searches as YaCy would aggregate any existing internal results with those coming from the external metasearch engine while storing anything new as well as to send the first page back to the YaCy frontend.

In this way, the external metasearch engine could be called from any YaCy nodes and the results would be aggregated back into the YaCy P2P storage for later use thereby effectively removing, or reducing, the need to crawl many sites that have already been returned as results from the external metasearch engine.

Something along these lines is what I was shooting for in looking to see how I might be able to augment, or enhance YaCy with a plugin or some code modifications.

Cheers, :)
