### ISSUE TITLE
Is YaCy Enterprise level

### ISSUE THREAD

**Issue by lonnieOST** [yacy/yacy_search_server#281]
Can you please tell me if YaCy could be considered stable enough and fast enough to be looked at as Enterprise level software?

Just wondering.
Thanks

**Comment by Orbiter** [comment]
YaCy has been used for a long time now as in-drop replacements for google search appliances.
For example: http://land.nrw has used a GSA and is now using YaCy Grid.

**Comment by lonnieOST** [comment]
Great to hear as I was really wondering about this since I have been watching, and using YaCy a little, for a long time now, but wanted to see about the stability, speed, and scalability.

Was not sure how it would work under heavy loading per node.
Thanks :)
