### ISSUE TITLE
https://yacy.net/en/Tutorials.html doesn't use https to connect to youtube

### ISSUE THREAD

**Issue by kotenok2000** [yacy/yacy_search_server#289]
https://yacy.net/en/Tutorials.html doesn't use https to connect to youtube.

10Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure resource '<URL>'. This request has been blocked; the content must be served over HTTPS.
Tutorials.html:47 Mixed Content: The page at 'https://yacy.net/en/Tutorials.html' was loaded over HTTPS, but requested an insecure resource 'http://www.youtube.com/embed/o3-v2oaXSa0?list=UUvy0FJxqOAlSZ2VXskej79Q'. This request has been blocked; the content must be served over HTTPS.
Tutorials.html:51 Mixed Content: The page at 'https://yacy.net/en/Tutorials.html' was loaded over HTTPS, but requested an insecure resource 'http://www.youtube.com/embed/hGwjllUdjU0?list=UUvy0FJxqOAlSZ2VXskej79Q'. This request has been blocked; the content must be served over HTTPS.
Tutorials.html:55 Mixed Content: The page at 'https://yacy.net/en/Tutorials.html' was loaded over HTTPS, but requested an insecure resource 'http://www.youtube.com/embed/UUAylWYqzac?list=UUvy0FJxqOAlSZ2VXskej79Q'. This request has been blocked; the content must be served over HTTPS.
Tutorials.html:61 Mixed Content: The page at 'https://yacy.net/en/Tutorials.html' was loaded over HTTPS, but requested an insecure resource 'http://www.youtube.com/embed/t5y5MmnmraA?list=UUvy0FJxqOAlSZ2VXskej79Q'. This request has been blocked; the content must be served over HTTPS.
Tutorials.html:65 Mixed Content: The page at 'https://yacy.net/en/Tutorials.html' was loaded over HTTPS, but requested an insecure resource 'http://www.youtube.com/embed/iqJuf_EA1UE?list=UUvy0FJxqOAlSZ2VXskej79Q'. This request has been blocked; the content must be served over HTTPS.
Tutorials.html:69 Mixed Content: The page at 'https://yacy.net/en/Tutorials.html' was loaded over HTTPS, but requested an insecure resource 'http://www.youtube.com/embed/XDoVNzOMoIo?list=UUvy0FJxqOAlSZ2VXskej79Q'. This request has been blocked; the content must be served over HTTPS.
Tutorials.html:73 Mixed Content: The page at 'https://yacy.net/en/Tutorials.html' was loaded over HTTPS, but requested an insecure resource 'http://www.youtube.com/embed/CFwebavBU0s?list=UUvy0FJxqOAlSZ2VXskej79Q'. This request has been blocked; the content must be served over HTTPS.
Tutorials.html:81 Mixed Content: The page at 'https://yacy.net/en/Tutorials.html' was loaded over HTTPS, but requested an insecure resource 'http://player.vimeo.com/video/18742908?portrait=0'. This request has been blocked; the content must be served over HTTPS.
Tutorials.html:88 Mixed Content: The page at 'https://yacy.net/en/Tutorials.html' was loaded over HTTPS, but requested an insecure resource 'http://player.vimeo.com/video/16817564?portrait=0'. This request has been blocked; the content must be served over HTTPS.
Tutorials.html:95 Mixed Content: The page at 'https://yacy.net/en/Tutorials.html' was loaded over HTTPS, but requested an insecure resource 'http://player.vimeo.com/video/17535160?portrait=0'. This request has been blocked; the content must be served over HTTPS.

**Comment by frankenstein91** [comment]
we do not serve https://yacy.net/en/Tutorials.html anymore

But thank you for the hint.
