### ISSUE TITLE
How to rewrite a url in the server side?

### ISSUE THREAD

**Issue by agnelvishal** [yacy/yacy_search_server#293]
I want to rewrite www.abc.com to www.xyz.com in the server side. Which file should I modify? Is it this file https://github.com/yacy/yacy_search_server/blob/master/htroot/yacysearch.java

**Comment by luccioman** [comment]
@agnelvishal it really depends on what you want to do exactly. By the way you will see that the /yacysearch interface results URLs are not directly processed in the yacysearch.java class, but in the [yacysearchitem.java](https://github.com/yacy/yacy_search_server/blob/master/htroot/yacysearchitem.java) class.

**Comment by luccioman** [comment]
I guess you found what you were looking for @agnelvishal. Don't hesitate to reopen this issue or open a new one if necessary.
