### ISSUE TITLE
auto support for let's encrypt https certificate.

### ISSUE THREAD

**Issue by raykai** [yacy/yacy_search_server#295]
Would be nice to have built-in support for let's encrypt https certificate. [https://letsencrypt.org/](https://letsencrypt.org/)

**Comment by frankenstein91** [comment]
could you please explain to us what speaks against the use of Certbot?

**Comment by frankenstein91** [comment]
Since creating certificates via the Certbot is very easy and a very good guide is available at https://certbot.eff.org/, I will close this one year old problem.

**Comment by onlyjob** [comment]
[dehydrated](https://dehydrated.io/) is another very good Let’s Encrypt client: https://github.com/dehydrated-io/dehydrated
