### ISSUE TITLE
PDF parser

### ISSUE THREAD

**Issue by openmatl** [yacy/yacy_search_server#30]
Hello,

I want to use YaCy as a document (word, pdf) parser and index lots of documents.
I found in the wiki something about possible parsers for it, but i am not able to find and 

activate them in the settings: http://localhost:8090/Settings_p.html?page=parser

How can I download, install and active the parser? (http://www.yacy-websuche.de/wiki/index.php/De:Parsers) and which libx do I really need?

Thanks for your help.

Kind regards
![missingparser](https://cloud.githubusercontent.com/assets/5571947/11642872/b233b9aa-9d40-11e5-94a0-f48894725895.png)

**Comment by Orbiter** [comment]
Hi, you can find the parser configuration page at http://localhost:8090/ConfigParser.html
The pdf and word parser is already integrated and activated by default. You don't need to install anything extra.

**Comment by openmatl** [comment]
aahh great, thanks for your fast answer.
