### ISSUE TITLE
Learning: Api Wiki is down..

### ISSUE THREAD

**Issue by pjatinsight** [yacy/yacy_search_server#306]
Hi,
Trying to evaluate Yacy for possible use in a project I want to do.
But when I try to go to https://wiki.yacy.net/ I see an internal server error...

All the api links in the interface such as:

 http://www.yacy-websearch.net/wiki/index.php/Dev:APICrawler

are also not working..

Is the Api documented anywhere else?

Thanks

**Comment by Orbiter** [comment]
The wiki is a bit broken but still alive! Your link is wrong, correct is:
https://wiki.yacy.net/index.php/Dev:APICrawler
