### ISSUE TITLE
Scraper cannot load URL

### ISSUE THREAD

**Issue by mat-l** [yacy/yacy_search_server#31]
Hello,

now as my YaCy is in general able to parse and index pdf document, I have sometime some issues with some documents. For example, I want to parse a book, then I get the following error:

`Crawling von "http://localhost:8090/repository/Linux.pdf" schlug fehl. Grund: scraper cannot load URL: java.io.IOException: REJECTED EMPTY RESPONSE BODY 'HTTP/1.1 200 OK' for URL 'http://localhost:8090/repository/Linux.pdf'$/
`

I searched already the web, but I didn't find a solution. Currently I am using jdk8-openjdk and stuff like this, is this maybe a problem for YaCy and the parser?

Thanks in advance and kind regards.

**Comment by bshouse** [comment]
I am curious if your web browser can load the PDF where the Scraper fails. When you see one of these errors can you access the content by copy-and-pasting the URL into your web browser?

The error message and source code indicate that the requested PDF was not returned by the web server. However, the "200 OK" means the web server thinks it is/can return it. Is it possible the PDF is bigger then the largest allowed HTTP file size?

Please let me know what you find.

**Comment by Quix0r** [comment]
No longer attended bug. Should be closed.
