### ISSUE TITLE
supplementing yacy results with results from an additional search engine

### ISSUE THREAD

**Issue by chaosmonk1** [yacy/yacy_search_server#319]
Hi.  YaCy seems very promising to me.  The search engine I currently use and recommend is Searx, because it is the best-performing search engine whose frontend and backend are both free software.  However, without an independent index of the web it can never be a real replacement for the non-free search engines it relies on to obtain search results.  For this reason, I see YaCy as a better long-term option.

Unfortunately, YaCy seems to suffer from a bit of a chicken-and-egg problem.  It relies on its users to index the web, so it needs more users before it can provide high-quality search results.  However, until it provides higher-quality results it will be difficult to attract more users.

I think a possible solution would be a configuration which supplements YaCy results with results from at least one other search engine.  This would make YaCy more usable in the short term, making it easier to expand the user base.  Once YaCy reaches a point where it's own results are good enough on their own, the temporary crutch of the additional search engine(s) will no longer be necessary.

I have looked through the issue tracker to see if this possibility has been discussed before, and came across https://github.com/yacy/yacy_search_server/issues/35.  I set up a private Searx instance to experiment with, and configured it to aggregate results from YaCy and DuckDuckGo.  Unfortunately, the timing doesn't work out:

Whereas when used on its own YaCy can gradually load and present results as it connects to more and more peers, Searx needs to get all results from all search engines it aggregates from before displaying anything to the user.  Each search engine is given a timeout value, after which Searx stops waiting for results.  If YaCy is given a reasonable timeout value, it does not have time to connect to peers and produce (m)any search results, so Searx ends up only using results from DuckDuckGo.  A timeout value high enough to get a substantial number of results from YaCy stalls Searx for an unacceptably long time before anything is displayed.

I wonder if it is possible to do the opposite:  to use YaCy as the frontend, and have it aggregate its own results with results from Searx (or another search engine).  Is this possible with YaCy?  If not, would it be possible to implement something like this, either by integrating additional search queries directly or perhaps by performing an external search query and injecting the results into the user's local index?

Thanks.

**Comment by virtadpt** [comment]
YaCy works pretty well with Searx, but in the opposite direction: Searx aggregates the responses from all of the search engines it's configured with.

**Comment by chaosmonk1** [comment]
> YaCy works pretty well with Searx, but in the opposite direction:
> Searx aggregates the responses from all of the search engines it's
> configured with.

Like I said, I tried this but it did not work well.  If you have had a
better experience, can you please tell me which Searx instance you used
and what timeout value was set for YaCy?  Thanks.

**Comment by chaosmonk1** [comment]
I cannot tell whether the settings at the bottom of http://localhost:8090/ConfigHeuristics_p.html are what I am looking for.  Enabling the example search engines does not seem to affect the search results I get, but it could be that these search engines just don't have any/enough relevant results to provide.  I tried adding and enabling https://duckduckgo.com/?q={searchTerms} as a general-purpose search engine, but even this did not seem to make a difference.  Perhaps DuckDuckGo does not produce results in the right format, but I don't see any errors.  Is it possible to add a general-purpose search engine and have results from this search engine appear when I search using YaCy?

**Comment by virtadpt** [comment]
@chaosmonk1 I use my own YaCy node, running on the same hardware:
```
  - name : Yacy
    engine : yacy
    shortcut : ya
    base_url : 'http://localhost:8090'
    number_of_results : 40
    timeout : 60.0
```
You can easily set the timeout to 120.0 or 180.0 seconds and it'll work just as well, I've been optimizing things a bit so I got it down to 60 seconds.

**Comment by chaosmonk1** [comment]
> @chaosmonk1 I use my own YaCy node, running on the same hardware:

Do you mean on the same hardware as the computer you search from, or the
same hardware as the server running the Searx instance (if you run your
own Searx instance as well)?

> ```
>   - name : Yacy
>     engine : yacy
>     shortcut : ya
>     base_url : 'http://localhost:8090'
>     number_of_results : 40
>     timeout : 60.0
> ```

Does a 60-second timeout value not cause Searx to be unresponsive for 60
seconds while it waits for YaCy?  That's how I remember it behaving, but
it was several months ago that I tried this.  I can try again this
weekend.

> You can easily set the timeout to 120.0 or 180.0 seconds and it'll work just as well, I've been optimizing things a bit so I got it down to 60 seconds.

Can you share what your optimizations are?

Thanks.

**Comment by virtadpt** [comment]
The same hardware is running both Searx and YaCy in my rack.

In my experience, it does not.  I usually use one of my bots to submit search requests, and I typically get a response in about five seconds at most.  The bottleneck seems to be the uplink from the bot to the XMPP server I use for C&C.

Optimizations are mostly turning off search engines in Searx and increasing the cache timeout on my local DNS in the rack.  Nothing to write home about, really, just doing stuff on my network I didn't do when I originally built it out.

**Comment by chaosmonk1** [comment]
> The same hardware is running both Searx and YaCy in my rack.

I see.  Is it possible to run a single Searx instance on a server, to be
used by multiple other machines, each running its own YaCy instance?  My
instinct is no, unless there is a way for Searx to check port 8090 on
the client IP instead of localhost.  If the roles were reversed, and
YaCy were to aggregate from Searx, then Searx and YaCy could be running
on additional machines.  If this is impossible though, your setup sounds
like a good plan B.  Thanks for the information.

**Comment by virtadpt** [comment]
It definitely is.  I'm running it that way (two YaCy instances, one Searx instance) in production.  [It took a bit of tinkering.](https://github.com/asciimoo/searx/issues/1762)

**Comment by Orbiter** [comment]
supplementing with other search engine results is implemented and named "heuristics".
See `/ConfigHeuristics_p.html` servlet.
