### ISSUE TITLE
alternative to opening port 8090 on router?

### ISSUE THREAD

**Issue by chaosmonk1** [yacy/yacy_search_server#322]
Although I know how to configure my router, and after doing so I appear to be reachable by other peers, it is an appreciable hurdle for most potential users, and even for users who know how to configure a router, this is only an option when they are at home and connected to their own network.

Other peer-to-peer software I have used does not require such a step.  I don't know much about this topic, so I apologize if this is a dumb question, but is there a reason that YaCy must use a port that is typically inaccessible?  Is it because the administration interface is accessible at the same port, and requiring router configuration is form of gatekeeping to ensure that the user is paying attention and likely has set up an admin password?  Are there plans to ever change this aspect of YaCy so that it can work out-of-the box and/or while connected to a network that the user does not administrate?

Thanks for clarifying.

**Comment by LoveIsGrief** [comment]
Have you activated UPnP on your router?

**Comment by chaosmonk1** [comment]
> Have you activated UPnP on your router? 

Yes, and YaCy works at home, where I administrate my own network.  But
at libraries, coffee shops, my university, or anywhere else that I do
not administrate the network, this is not an option.  Most people I know
would not even know how to configure their own router.  This means that
for most people in most situations, it is fairly easy to use YaCy, but
difficult or impossible to contribute.  My question is whether YaCy will
always suffer from this limitation, or it will eventually be addressed.

**Comment by LoveIsGrief** [comment]
I'm not sure, but does bittorrent really work in libraries and coffeeshops / public networks? It would be worth testing to confirm it does. If it does, maybe ask on stackoverflow, hackernews or reddit how that's achieved and post back here. Maybe somebody interested could then have an idea of how to implement it.

**Comment by frankenstein91** [comment]
The VPN service provider Mullvad also offers port forwarding. This should work in Starbucks.

**Comment by frankenstein91** [comment]
as there is no new feedback
