### ISSUE TITLE
SOLR wide open to WAN

### ISSUE THREAD

**Issue by ipforums** [yacy/yacy_search_server#323]
SOLR is wide open to WAN even if authentication is required for search and admin portal access.  I think this is a massive security hole that can cause privacy issues / denial of service.  It looks like a known but unreported issue.  I've seen several IPs sending SOLR queries that'd caused 50% CPU utilization lasting for hours.  So I think fixing this is quite important.  For now I switched to Robinson mode...  Amazingly enough after the switch I'm prompted for credentials when accessing SOLR.  

http://xxx.xxx.xxx.xxx:8090/solr/select?core=collection1&q=*:*&start=0&rows=3
https://xxx.xxx.xxx.xxx:8443/solr/select?core=collection1&q=*:*&start=0&rows=3

**Comment by Scarfmonster** [comment]
I believe sorl being open to the public is by design. YaCy performs searches on solr indexes of remote peers. To do that, if you run in public mode, the sorl interface has to be open. You cannot both use the global index and not contribute to it, and you shouldn't be able to. I also don't see how this could possibly be a security issue, unless you can access administrative interfaces this way.

**Comment by ipforums** [comment]
If I have 10 million records in my solar index and 1000 people run a select all query against my SOLR server at the same time what is going to happen?  I'll get extremely high CPU utilization, I might run into bandwidth problems any crawls that I have will halt.  If I have a any other jobs running, those jobs will likely die as well.  My server might run out of RAM and if that happens OS might crash or hang...  Additionally it's a privacy problem because I may choose to crawl a number of websites, but that doesn't mean I want to share my entire index with everyone who asks.  I might want to share pieces of my index and only with those that are a part of Yacy network.  It should be up to the person running a Yacy node to decide.

 I don't know the details of Yacy architecture, From what I saw so far index is transferred in chunks and I very much doubt it requires SOLR being open to the public.  If it does it's a not a good design decision, someone took a shortcut =D.  I can understand that with the project of this size.  It's similar to having SQL server or another database engine exposed without any authentication whatsoever to the internet.  Usually you'd want a web service of some type (servlet in Java terms?) in front of you database.
