### ISSUE TITLE
A website for public instances

### ISSUE THREAD

**Issue by LoveIsGrief** [yacy/yacy_search_server#326]
Hi,

I want to run a public instance of YaCy this year, but want to see how other public instances are doing. Unfortunately, there doesn't seem to be a list / website / webpage listing all the public instances like [peertube](https://instances.joinpeertube.org/instances) or [fediverse.network](https://fediverse.network/) does.

I wouldn't mind starting such a website myself, but is there an API one can access to build the list dynamically or to get health stats from the instance?

Cheers

**Comment by ipforums** [comment]
Once you install YACY and run a node, you should see IPs of all participants. Simply append port 8090 or 8443 to each of the IPs and you'll gain access to their instance.  Assuming they haven't locked it down that is...

**Comment by LoveIsGrief** [comment]
I'll need a way to programmatically build a list of public instances. Is there an API (local or not) that I can use e.g `http://localhost:8090/network.json` or even dbus or something?

**Comment by Low012** [comment]
Replacing the **.html** with **.xml** for the Network pages (http://localhost:8090/Network.html) will give you a machine readable view of the network data displayed on the respective page. The wiki with the documentation seems to be broken at the moment, but you can just try to replace the **.html** with **.xml** or **.json** whereever you see the API symbol in the upper right.

BTW: Search results can also be retreived as JSON or RSS:

Regular: http://localhost:8090/yacysearch.html?query=test
JSON: http://localhost:8090/yacysearch.json?query=test
RSS: http://localhost:8090/yacysearch.rss?query=test

**Comment by LoveIsGrief** [comment]
Thank you. I'll try running it in a docker and report back when I have results

**Comment by onlyjob** [comment]
I would also like the web page with list of public instances.

http://search.yacy.net/ is not great as it throws error "`The search service is not available right now. Please try again.`" quite often.

Is there a DNS server where all the .yacy instances are registered? If so then one could make an _haproxy_ frontend to query them (e.g. `server-template node 1-200 yacy.service.consul:8090 check resolvers consul init-addr none`). We could leverage Consul to monitor nodes availability.

**Comment by onlyjob** [comment]
For example, https://searx.info/ have a nice "[Public instances](https://searx.space/)" link at the bottom of the page. I think it would be great to have something like this.

**Comment by Houkime** [comment]
Actually how this works with searx is that there is a github repository with a yaml list of all instances that decided to be public.
They just add themselves there with a pull request, and then a website polls this list.
So it is not about automatic collecting of IP's of servers that did not lock down their interfaces, but rather about voluntary going public.

https://github.com/searx/searx-instances

So if one wants to replicate this for yacy, one needs a repo and a website. (it probably can be even github pages page)

**Comment by sjehuda** [comment]
Please make a List of Public Instances page.
By the way, is there a list of public instances somewhere?

**Comment by frankenstein91** [comment]
> By the way, is there a list of public instances somewhere?

maybe you can use https://yacy.searchlab.eu/Network.html?page=1&maxCount=1000

**Comment by Orbiter** [comment]
Since the beginning of YaCy every YaCy instance presented a network list with all peers and distinguished them with public ('senior') and not-accessible (junior) peer lists.

**Comment by sjehuda** [comment]
Yes, but we want an end-user style list which we can click on `https://` hyperlinks that lead to publicly open instances that will let us use YaCy from their web interface.

**Comment by sjehuda** [comment]
@onlyjob 
> For example, https://searx.info/ have a nice "[Public instances](https://searx.space/)" link at the bottom of the page. I think it would be great to have something like this.

https://farside.link/
I've opened a ticket https://github.com/benbusby/farside/issues/30

**Comment by dchmelik** [comment]
I have this problem also.  I used to use YaCy and recommend search.yacy.net to people as a Free/Libre Software (FLS) search engine but now know of no main public search to recommend or fix their broken instances of this that had been added in web browsers.

**Comment by okybaca** [comment]
Shouldn't be too difficult to do. Do you speak Java?
Everything is probably ready for that. In `/Network.html?page=1&maxCount=1000` you got already a list of senior peers, which is public. The only decision is IMO, how to sort the list (probably combination of "Links" count and probably some parameter indicatin speed of peer (not sure about which one - QPH can be used as a rough measure)).
Then a newly created list "Other YaCy instances" could be linked from the bottom of search portal page and from anywhere...

**Comment by okybaca** [comment]
Not sure if that's such a bad idea. 

Not everyone has the oppurtunity to run own node. You search from
smartphone, outside of your NATed network, recommending to people, etc...

Peer list, already included in YaCy, is cool but not very understandable at
first glance. Some easy list such as "top nodes to try" would help the
beginners to test and start. And to bring more attention to yacy itself.

Btw, SearX metasearch has already a module for yacy, which could be used to
mix your own peer results with other engines and/or peers in a experimental
setup.  And is good as a front-end as well.

**Comment by LoveIsGrief** [comment]
I agree with @okybaca : the idea is to have one website like https://instances.joinpeertube.org/instances where one can see all the instances. Is that currently possible with yacy? https://yacy.searchlab.eu/ is a public instance, but there's no obvious way to find which other instances exist.

**Comment by okybaca** [comment]
The list of running instances is here on that peer: https://yacy.searchlab.eu/Network.html?page=1&maxCount=1000. 
To create more easy-to-understand list wouldn't be so difficult, so do it, if you can.

**Comment by lolcatw** [comment]
> The list of running instances is here on that peer: https://yacy.searchlab.eu/Network.html?page=1&maxCount=1000. To create more easy-to-understand list wouldn't be so difficult, so do it, if you can.

@okybaca this now gives me a near empty page with japanese characters everywhere.

**Comment by okybaca** [comment]
hi, that url was just an example. in fact, every instance of yacy does have
such list, based on it's own p2p network bootstraping. so use another one,
idealy your own. 

why demo instance https://yacy.searchlab.eu/ switched to chinese (or what)
is just a mystery ;-)

**Comment by okybaca** [comment]
the best way is to run your own ;-)
