### ISSUE TITLE
YaCy uploads seed.txt but then won't download it

### ISSUE THREAD

**Issue by dchmelik** [yacy/yacy_search_server#328]
I configured YaCy ([DavidChmelik.com:8090](http://DavidChmelik.com:8090/) ) to upload seed by every method.  Each said 'SaveSeedList: Seed upload failed (IO error): Server returned status: HTTP/1.1 404 Not Found.'  However you can see that seems false as seed uploaded: [DavidChmelik.com/~yacy/seed.txt](http://DavidChmelik.com/~yacy/seed.txt) ... and my webserver logged normal web-browser downloads of seed.txt successful, so problem seems with YaCy (do I need an additional port open?)  Though I did see webserver log YaCy requesting from LAN IP address of router and saying 404.  I also uploaded seed to a remote server which uploaded fine, downloaded fine with web browser, but YaCy won't download from it (however will only discuss that server on IRC.)  I was able to FTP & scp with the username:password... though would rather use file path (verified that also.)  I'd have asked on forum, but freenode IRC #yacy topic lists a nonexistent English forum, German/Deutsche forum with broken search (but I need to find thread on how to reverse proxy such as to search.DavidChmelik.com:80) and YaCy.net links forum with no sign-up (SearchLab.eu.)  I have another issue (related to why I didn't link my 8443 URL) but not as pressing...

**Comment by frankenstein91** [comment]
could you please post your upload config page? (removing passwords)

**Comment by dchmelik** [comment]
Actually I got it working some weeks ago (had typographical error in configuration) then became one of the higher-level peers.  However now my main web/YaCy hardware server won't turn on.  YaCy had been halting or would run for a while then not complete login, anyway.  So this particular issue is fixed, but after I repair/replace the server, I might have some other issues... don't know what happened to the forums & chat (links to those seems outdated.)
