### ISSUE TITLE
Translation management

### ISSUE THREAD

**Issue by comradekingu** [yacy/yacy_search_server#331]
Would love to see [Weblate](https://weblate.org/nb/hosting/) used. It makes sorting out issues easier.
Hoping to start a new Norwegian Bokmål (nb_NO) translation.

**Comment by Orbiter** [comment]
That is a pay-service and would create a non-free dependency

**Comment by comradekingu** [comment]
@Orbiter It can be self-hosted, but it even provides gratis hosting for libre software (see link). It isn't non-free in a technical aspect either, as it is copylefted libre software.
