### ISSUE TITLE
is there a design documentation?

### ISSUE THREAD

**Issue by Qiyamah** [yacy/yacy_search_server#336]
A documentation talking about what parts it is composed of and features of each part?

Thanks

**Comment by Orbiter** [comment]
YaCy is a complex piece of software. To read all about the DHT architecture, read this scientific analysis about it: https://www.esat.kuleuven.be/cosic/publications/article-2459.pdf

This does of course not at all cover all the spider/parsing activity. To get a climpse of it, please crawl through the data at https://yacy.net/material/
