### ISSUE TITLE
javaw not found

### ISSUE THREAD

**Issue by jeffythedragonslayer** [yacy/yacy_search_server#340]
After installing YaCy on Windows 10 (with the checkbox for installing Java (Oracle JRE) checked), I am getting the error:

Windows cannot find 'javaw.' Make sure you typed the name correctly, and then try again.

**Comment by jeffythedragonslayer** [comment]
I was able to fix this and run YaCy by downloading Java from https://www.java.com/en/download/, so it appears to be an issue with YaCy windows installer not installing Java.

**Comment by Orbiter** [comment]
This is a known issue and therefore the installation instructions at https://yacy.net/download_installation/#on-windows ask you to install java yourself at the beginning of the process
