### ISSUE TITLE
[Bug] Docker yacy stops responding to port 8090 after a certain amount of time

### ISSUE THREAD

**Issue by LoveIsGrief** [yacy/yacy_search_server#341]
**Command**:

```
docker run \
 -d \
 --name yacy \
 -p 8090:8090 \
 -p 8443:8443 \
 --log-opt max-size=200m \
 --log-opt max-file=2 \
yacy/yacy_search_server
```

If I run `curl localhost:8090` a few times it works. But after some time (I haven't been able to pin down exactly how much), it just stops responding and times out.

`docker logs -f --tail 10 yacy` happily continues spitting out logs about other anonstufe's, but nothing about connection timeouts or local connection attempts.

Is there some way I could activate more verbose logs?

**Comment by jrruethe** [comment]
I am having this exact same problem, it seems to stop responding for me after about 8 minutes or so. I have been attempting to debug it but have been unsuccessful, it doesn't appear to be correlated to memory or cpu usage that I can tell. If you find any leads or have any solutions, please share them!

**Comment by LoveIsGrief** [comment]
Unfortunately the debug flag to [startYacy.sh](https://github.com/yacy/yacy_search_server/blob/master/startYACY.sh) doesn't activate debugging at all.

**Comment by maxze** [comment]
Has anyone been able to find a fix for this? I mean, restarting the docker container a few times seems to work for a while, but that's not really a usable solution.

**Comment by LoveIsGrief** [comment]
It seems like in order to activate debug logs, it's necessary to modify `/opt/yacy_search_server/DATA/LOG/yacy.logging`.

One can copy it from this repo https://github.com/yacy/yacy_search_server/blob/master/defaults/yacy.logging , modify it and then bind it using volumes. The logs can then be more verbose and help debugging the issue.

This is the diff for mine

```diff
78,80c78,80
< org.apache.http.level = OFF
< org.apache.commons.httpclient.level = OFF
< httpclient.wire.level = OFF
---
> org.apache.http.level = INFO
> org.apache.commons.httpclient.level = INFO
> httpclient.wire.level = INFO
```

[yacy.logging.txt](https://github.com/yacy/yacy_search_server/files/4498811/yacy.logging.txt)

I mount the whole LOG directory in order to tail the logs.

```bash
docker run \
   `# Run container in background` \
   --detatch \
   `# Remove container once it stops` \
   --rm \
   --name yacy \
   `#Bind the current directory to the LOG directory` \
   -v $(pwd):/opt/yacy_search_server/DATA/LOG \
   -p 8090:8090 -p 8443:8443 \
   --log-opt max-size=200m \
   --log-opt max-file=2 
     yacy/yacy_search_server

# Wait for timeout on curl and print logs
echo waiting...
while curl --connect-timeout 1 localhost:8090 &> /dev/null ; do 
  sleep 10 
done
# Print current date
ddate=`date`
echo $ddate
# Print last lines of the logs
tail yacy00.log
# you can add your own notification command here
xmessage "Yacy is not unresponsive. Check the logs at $ddate"
# or use notify-send or whatever else (a twitter, etc.)
```

**Comment by maxze** [comment]
Thank you, @LoveIsGrief . I'll try this as well but I unfortunately won't get a chance to really take a look at it before the next weekend. It would be nice if you would let me know about your findings if you have the time to.

**Comment by LoveIsGrief** [comment]
It seems like after a minute or so of inactivity the server stops accepting requests. I can't seem to find the right logger to activate in order to debug. Maybe somebody else will find it

**Comment by LoveIsGrief** [comment]
I updated the script, but can't find the right log. Not even sure if there'll be one at this point :/

Might have to actually run this in a debugger >_<

```bash
#!/bin/bash
# At least a minute is good
sleep_time=${1:-120s}

cd ~/docker/yacy

docker run \
    `# Run container in background` \
    --detach \
    `# Remove container once it stops` \
    --rm \
    --name yacy \
    `#Bind the current directory to the LOG directory` \
    -v "$(pwd):/opt/yacy_search_server/DATA/LOG" \
    -p 8090:8090 -p 8443:8443 \
    --log-opt max-size=200m \
    --log-opt max-file=2 \
      yacy/yacy_search_server

trap "docker kill yacy" EXIT

echo waiting... $sleep_time
sleep $sleep_time

while curl -s --max-time 2 localhost:8090 &> /dev/null
do
    echo "sent it `date`: $?"
    sleep $sleep_time
done

echo "status $?"
echo

date
tail yacy00.log
```

**Comment by Kornexl** [comment]
I have the same problem.
Running as docker container  or native program on Ubuntu 18.04
The webinterface stops responding after some minutes (5-20).
The crawler and all other process continue running.
I can't find any entries in the logs (debug enabled) belonging  to this stop.
yacy is runnung as "Search portal for your own web pages"

**Comment by Orbiter** [comment]
I am trying to fix this for some time now. So far I cannot find a cause for the locking.
Just to give it a try I made some maybe-tweaks in https://github.com/yacy/yacy_search_server/commit/264bab67001cd7974237e4730af92af0b905668f

**Comment by Orbiter** [comment]
This is a kind of double to https://searchlab.eu/t/yacy-web-interface-hangs-after-some-time/265 and it looks very good with the most recent bugfix. Please update your docker container and try again!

**Comment by LoveIsGrief** [comment]
A late response, but it's working for me now. Ran it for an hour and could still use the interface.

Hopefully it won't crop up again. Thanks for fixing!
