### ISSUE TITLE
index export is incomplete

### ISSUE THREAD

**Issue by DotDotJames** [yacy/yacy_search_server#343]
Hi -- the index exports from IndexExport_p.html to either XML or JSON are incomplete, e.g., for an index with 165406 documents, only 137760 docs were exported. This behavior has been consistent for different configurations -- OpenJDK 8 on Debian, OpenJDK on Ubuntu, etc.

The export settings were the defaults for URL, and usually around 10% of the docs in the index.

Setting mod, known bug, something else?

**Comment by virtadpt** [comment]
Can confirm on Arch (latest).  Thought it was supposed to be like that for some reason, guess it's not?

**Comment by sendbits** [comment]
yes, for some scenarios, managing independent crawls via multiple nodes and importing into master is easier than either cluster or grid config for our use cases / server config - disparity on export makes that problematic :man_shrugging:

**Comment by sendbits** [comment]
The index export gap appears for any Linux distro or JRE combo tried so far:

{CentOS, Debian, Ubuntu} x {OpenJDK 8, Open JDK 11}

Haven't had chance to test against Zulu or other Java environments.

**Comment by lrehmann** [comment]
Same issue, "The local index currently contains 37,440 documents." -- 'Full Data Records' export with no parameters indicates "Finished export of 12383 Documents to file" -- 'Full URL List' export leads to similar results. 
`
YaCy version: 1.922/9975
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian`

**Comment by Orbiter** [comment]
This actually works as designed! The reason that an export is smaller than the index size is, because the index also contains error documents which are visible in the host browser - but error documents are never exported, that would not make sense.
See commit message - the commit now gives an information about the expected size of the export.

**Comment by lrehmann** [comment]
thank you so much for the update!
