### ISSUE TITLE
Yacy and Searx together possible?

### ISSUE THREAD

**Issue by star-buck** [yacy/yacy_search_server#35]
Hi,
is it possible to have searx using yacy as meta-source?

**Comment by Scarfmonster** [comment]
If searx supports fetching results through opensearch you can use http://localhost:8090/yacysearch.rss?query={searchTerms}

**Comment by Scarfmonster** [comment]
Actually, I looked into it a bit further and it seems searx already supports yacy as one of the resources. In that case I'd recommend asking more on the searx repository.

**Comment by Orbiter** [comment]
it looks like searx already supports YaCy: https://github.com/asciimoo/searx/blob/master/searx/engines/yacy.py
If there is an issue connecting YaCy and searx, please report details and decide if that should be an issue of YaCy or searx. Please test this. If there is no problem, please close this issue.

**Comment by star-buck** [comment]
thanks for the info, ill report back if any questions come up.
