### ISSUE TITLE
API endpoints always respond with 401 Unauthorized

### ISSUE THREAD

**Issue by rkbennett** [yacy/yacy_search_server#354]
Running yacy/yacy_search_server docker image

Issue: any attempt to curl anything that ends in a _p.html always results in an 401 Unauthorized, even when providing the credentials via the -u switch.

Expected result, API functions properly when receiving credentials via curl

Aside: The docs seem kind of light on this, and didn't really even see much on this in the forums

**Comment by rkbennett** [comment]
Update: It appears all authentication, in general, doesn't work when using curl or wget

**Comment by virtadpt** [comment]
It's still happening.  I just installed YaCy from source (Git commit 9a5694261a95c50e5e669a39868e1a9bbe56f93a) and neither cURL nor anything else I've tried has been able to successfully use the API.  It always returns an HTTP 401.

**Comment by Orbiter** [comment]
I will check this.
Anyone here with a copy-paste example to reproduce this?

**Comment by virtadpt** [comment]
I have a few.  Hang on.

**Comment by virtadpt** [comment]
A formerly-working agent that, when YaCy's API broke hosed my entire setup for a solid day:

```
{
  "post_url": "http://{% credential leandra %}:8090/Crawler_p.html?crawlingMode=url&crawlingDepth=2&range=domain&indexText=on&crawlingURL={{ message }}",
  "expected_receive_period_in_days": "365",
  "content_type": "form",
  "method": "post",
  "emit_events": "true",
  "no_merge": "false",
  "output_mode": "merge",
  "user_agent": "{% credential user_agent %}",
  "basic_auth": [
    "{% credential yacy_user %}",
    "{% credential yacy_pass %}"
  ]
}
```
(Note: I'd been using this agent with that URL construction for a good three years, averaging about 150 runs per day.)

Test URL: https://www.mymove.com/broadband/guides/att-modems-and-routers/

Result:
![yacy_agent_run](https://user-images.githubusercontent.com/639730/103111663-5a13e980-4604-11eb-9f62-fb4dd5c3c7a8.png)

**Comment by virtadpt** [comment]
An evocation of `curl` with the same URL, test URL to index, and credentials.  Admin password elided.
Command: `curl -XPOST --basic --user admin:[[[ redacted ]]] -v http://leandra:8090/Crawler_p.html?crawlingMode=url\&crawlingDepth=2`

Output:
```
* Trying 192.168.0.130:8090...
* Connected to leandra (192.168.0.130) port 8090 (#0)
* Server auth using Basic with user 'admin'
> POST /Crawler_p.html?crawlingMode=url&crawlingDepth=2 HTTP/1.1
> Host: leandra:8090
> Authorization: Basic YWRta[[[ redacted ]]]b1o=
> User-Agent: curl/7.73.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< WWW-Authenticate: Digest realm="The YaCy access is limited to administrators. If you don't know the password, you can change it using <yacy-home>/bin/passwd.sh <new-password>", domain="", nonce="aTKPY8RAJkkWL/U3IMdrm3UwNRGlItDy", algorithm=MD5, qop="auth", stale=true
< Cache-Control: must-revalidate,no-cache,no-store
< Content-Type: text/html;charset=iso-8859-1
< Content-Length: 1252
< Server: Jetty(9.4.35.v20201120)
< 
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 401 Unauthorized</title>
</head>
<body><h2>HTTP ERROR 401 Unauthorized</h2>
<table>
<tr><th>URI:</th><td>/Crawler_p.html</td></tr>
<tr><th>STATUS:</th><td>401</td></tr>
<tr><th>MESSAGE:</th><td>Unauthorized</td></tr>
<tr><th>SERVLET:</th><td>net.yacy.http.servlets.YaCyDefaultServlet-245a060f</td></tr>
</table>
<br/><hr /><small>YaCy 1.922  - <i> powered by Jetty </i> - </small><br/>                                
<br/>                                
<br/>                                
<br/>                                
<br/>                                
<br/>                                
<br/>                                
<br/>                                
<br/>                                
<br/>                                
<br/>                                
<br/>                                
<br/>                                
<br/>                                
<br/>                                
<br/>                                
<br/>                                
<br/>                                
<br/>                                
<br/>                                

</body>
</html>
```

**Comment by virtadpt** [comment]
Git commit of yacy_search_server running: 32ca669bfbbf4f881fa98d097c01f5fa90f4078b
If I log into my YaCy instance with the same credentials used in the above two examples (which work) and submit the URL manually:
![yacy_go_boom](https://user-images.githubusercontent.com/639730/103111943-bd9f1680-4606-11eb-91b8-21e0e3edb87e.png)
I've saved a copy of the yacy00.log file from this particular test run for analysis because I'm not sure what I should be looking for in there.  If you want it let me know.

**Comment by virtadpt** [comment]
Just updated to commit 256fa3d9859bcd1922165dba8218361bc3f7aa69.  Same problem.

**Comment by Orbiter** [comment]
Did you try with digest auth? You are forcing basic auth and that is not allowed in YaCy for non-localhost access since some time. I did not implement that but I believe we should stick to that.

**Comment by virtadpt** [comment]
No, I haven't.  I'll give that a try.  That should probably be in the wiki.
Is wiki.yacy.net stable yet?  Last time I tried to look through it, it wasn't returning anything to HTTP requests.

**Comment by virtadpt** [comment]
Hmm.  Digest authentication works with cURL, it seems.  I need to figure out to do it programmatically.  Thanks!

**Comment by Orbiter** [comment]
The reason to ban basic authentication was weak security - the password can be obtained from the http stream. Thats a problem of the authentication method, not a problem of the YaCy implementation. Therefore digest was implemented and basic banned. If digest works for you, then we should stick to that.

**Comment by virtadpt** [comment]
It works now, with a little creative use of cURL and a Shell Agent.
