### ISSUE TITLE
garbage-collecting indexes?

### ISSUE THREAD

**Issue by onlyjob** [yacy/yacy_search_server#360]
My crawler fetched pages it was not suppose to fetch so I've added exclusions to blacklist and  deleted URLs from indexes. Then I have verified that deleted/blacklisted URLs do not appear in search.

However trying a random URL on the "View URL Content" page (`http://localhost:8090/ViewFile.html?viewMode=parsed&url={URL}`) still show content and structure of deleted documents.

_How can I garbage-collect local indexes to physically remove deleted documents?_

I estimate that those documents account for 20...30 GiB of disk space -- a non-negligible amount of wasted disk space that would be great to reclaim... Thanks.

**Comment by hamburghammer** [comment]
I just removed a bunch of indexes to free some disk space but I had to realize that the documents are still inside the DB. 
Is there a Solr query that I can use to remove them manually until a proper solution is found?

**Comment by Orbiter** [comment]
There is an index deletion function, did you try that?

**Comment by otteresk** [comment]
Hi hamburghammer,
have you deleted documents from the Solr database (/IndexDeletion_p.html) and can still find them with a Solr query? That would be strange and needing further investigation.
If you deleted documentsand don't see the free disk space increasing: That's normal. Entries are just "marked" as deleted.
To release disk space you can "optimize" the Solr (/IndexControlURLs_p.html) to one segment.
Please be aware that this takes some time and temporarily even more disk space.

**Comment by hamburghammer** [comment]
@Orbiter Ah I see. I was confused to not see the results of the deletion immediately.
@onlyjob thank you for your detailed explanation.
With the `/IndexControlURLs_p.html` to "optimize" the Solr segments I managed to reduce the disk usage. Now I am back to 40 GB DB size with hopefully better queries. Thanks a lot. This Project is truly amazing.

**Comment by Orbiter** [comment]
Great! I added a hint and the link to optimization so it will be easier for all users to understand the process.
