### ISSUE TITLE
Maximum of System-Load (for Local Crawl) is hard-limited to 8.0

### ISSUE THREAD

**Issue by onlyjob** [yacy/yacy_search_server#363]
I'm running YaCy on a busy server with normal load average greater than 10.
Server have a lot of resources to spare and average load is mostly due to IOWAIT time on some local HDDs allocated to a different task.

To operate YaCy I had to adjust _Maximum of System-Load_ values (in _System Administration_ --> _Performance Settings of Queues and Processes_) by multiplying default values by 10.

However _Maximum of System-Load_ value for _Local Crawl_ is being automatically reset to `8.0` which effectively stops crawling almost entirely.

How can I adjust or disable the hard-coded limit for _Local Crawl Maximum of System-Load_?

Thanks.

**Comment by onlyjob** [comment]
Maximum of System-Load value for Local Crawl resets when I click **Set** button on `Crawler_p.html` page... This is unexpected, un-intuitive, unnecessary and very inconvenient.

**Comment by lflare** [comment]
Note, this issue is still present. The following line of code may be relevant to solving this. https://github.com/yacy/yacy_search_server/blob/9c38b1254ecd7693b2d49ff9c5b25533496b47f9/htroot/Crawler_p.java#L786

**Comment by Orbiter** [comment]
We still need to set the load in the process because a demand for higher
crawl speed may require to increase the maximum load limit. However,
following the criticism in the bug, we do never reduce the load limit
again.
