### ISSUE TITLE
Issue when attempting to upload seed file

### ISSUE THREAD

**Issue by VitaminKay** [yacy/yacy_search_server#368]
Hello, I am facing the following issue when trying to upload my seed file to become a principal peer (I am already a Senior peer):

My YaCy host is located on the LAN at 192.168.201.20, running YaCy on port 8090, and running Apache on port 80. I have YaCy set to simply scp the seed from the local machine into the web directory, this works (file appears). However, after selecting the submit button next to upload method (after selecting Scp) I am given the following error:
`SaveSeedList: Seed upload failed (IO error): Unable to download seed file 'http://yacy.redacteddomain.blah/yacy/seed.txt'. Client can't execute: yacy.redacteddomain.blah duration=0 for url http://yacy.redacteddomain.blah/yacy/seed.txt`

I have hand verified that the seed file shows up and is accessible from not only the open internet, but to the host machine running YaCy on that web address. So why am I receiving this error? I additionally tried several other web servers I have access to and received similar results, sometimes receiving: 
`Save Seed List: Seed upload failed (IO error): areturned status: HTTP/1.1 404 NOT FOUND`

Here is a copy of my seed upload settings page:
![image](https://user-images.githubusercontent.com/47240191/84851238-f8e8d900-b016-11ea-9faa-ba9c3dcf05a2.png)

**Comment by bAndie91** [comment]
why do you upload the file to the same machine as it is? yacy runs on 192.168.201.20 and you set up yacy to upload to 192.168.201.20. the same machine, is not it? whould not it better to let yacy save the file to a local path and set up apache to serve that file on the desidered url? i guess the apache part is already done, provided that the DocumentRoot is `/var/www/html`. I guess yacy tries to download the file on the URL you gave once it uploaded it to see whether it works or not; do can it download? does the domain in the url resolve properly even on the very host it's running on?

**Comment by VitaminKay** [comment]
Closing this issue, after a restart, the local save function began to work. I now have principal peer status.
