### ISSUE TITLE
Negative seek offset

### ISSUE THREAD

**Issue by yacylover** [yacy/yacy_search_server#372]
Hi,

using v1.922/9964 during crawling the following exception is thrown:

`
W 2019/11/25 19:06:53 ConcurrentLog java.io.IOException: Negative seek offset java.io.IOException: Negative seek offset at java.io.RandomAccessFile.seek(RandomAccessFile.java:572) at net.yacy.kelondro.io.CachedFileWriter.seek(CachedFileWriter.java:143) at net.yacy.kelondro.blob.Heap.add(Heap.java:153) at net.yacy.kelondro.blob.Heap.insert(Heap.java:356) at net.yacy.kelondro.blob.BEncodedHeap.insert(BEncodedHeap.java:395) at net.yacy.kelondro.blob.BEncodedHeap.update(BEncodedHeap.java:413) at net.yacy.kelondro.blob.Tables.update(Tables.java:406) at net.yacy.search.Switchboard.storeDocumentIndex(Switchboard.java:3473) at net.yacy.search.Switchboard.storeDocumentIndex(Switchboard.java:3355) at net.yacy.search.Switchboard$6.process(Switchboard.java:1043) at net.yacy.search.Switchboard$6.process(Switchboard.java:1039) at net.yacy.kelondro.workflow.InstantBlockingThread.job(InstantBlockingThread.java:72) at net.yacy.kelondro.workflow.AbstractBlockingThread.run(AbstractBlockingThread.java:82) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522) at java.util.concurrent.FutureTask.run(FutureTask.java:277) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) at java.lang.Thread.run(Thread.java:818)
`

Are some of my BLOBs corrupted? It occurs during bootstrapping YaCy, too. 

[Full stacktrace](https://pastebin.com/eKBkYHW9)

[Vid of occurrence](https://youtu.be/RbSkLHxApAU)

Please fix

Best

Steve

**Comment by okybaca** [comment]
mentioned [in the forum](https://community.searchlab.eu/t/database-broken-after-restart/1155) as well.
deleting the cache files helped me, but should be solved automaticaly, so it doesn't prevent start.
however, i'm not able to reconstruct the conditions and it didn't happen later to me.
