### ISSUE TITLE
Continously seing a troyan download blocked by antivirus

### ISSUE THREAD

**Issue by Pablo-No** [yacy/yacy_search_server#373]
I've started using YaCy today, I love the idea and I love Open Source too, but almost every 15 minutes I see that my antivirus has blocked the download of a trojan, the url is **PLEASE DON'T USE IT** http:// 24.255.187.175 / yacy / hello.html
I don't know what could be causing it instead of yacy or something who is vulnerating yacy's security, I don't know what to do and I'm seriously concerned about this
Does anyone know what's causing this and how to stop it?
I'm also posting this on SearchLab, yacy's forum.

**Comment by frankenstein91** [comment]
https://www.virustotal.com/gui/url/afc44b8dc982432a736e1b169435ef67c1860c02e80beded5a5264d3c5756185/detection

Maybe a false positive

**Comment by frankenstein91** [comment]
I think as a Yacy community we have little control here. If there is a real virus here, the Abuse Mail of the operator would be the right contact. Unfortunately we are not able to contact a Yacy operator.
But the best protection for yourself would be an IPtables rule.
```
iptables -A INPUT -s 24.255.187.175 -j DROP
iptables -A OUTPUT -s 24.255.187.175 -j DROP
```

**Comment by frankenstein91** [comment]
After almost a month, are there still questions from your side or can we close the ticket? Since the individual nodes are operated by unknown people, we cannot intervene.
