### ISSUE TITLE
Do not share blacklist by default / Freigegebe Sperrlisten nicht als die Vorgabe.

### ISSUE THREAD

**Issue by aleksejrs** [yacy/yacy_search_server#374]
When I create a blacklist, it is [shared]. It should not be.
Als ich eine neue Sperrliste angebe, ist sie [freigegeben]. Es soll so nicht sein.

**Comment by reger24** [comment]
agreed .... and changed it
ja, kann ich zustimmen, ist wohl besser anders herum
