### ISSUE TITLE
Consider using AGPL

### ISSUE THREAD

**Issue by XaviDCR92** [yacy/yacy_search_server#379]
Being essentially a web application, has the GNU Affero General Public License ever been considered for YaCy? According to the additional clause provided by the AGPL, it ensures modified versions of YaCy running on peer servers must provide a way to download the modified source code so others can benefit. Other web applications I know use it e.g.: [Invidious](https://github.com/iv-org/invidious).
If already considered, which are the reasons why the AGPL was discarded for YaCy?

**Comment by Orbiter** [comment]
GPL/LGPL was more or less randomly selected about 16 years ago. We are sticking to that.
