### ISSUE TITLE
Use YaCy with TorBrowser

### ISSUE THREAD

**Issue by J053Fabi0** [yacy/yacy_search_server#380]
How can I use YaCy with the TorBrowser? It can't load any localhost webpage.

**Comment by frankenstein91** [comment]
The easiest thing to do would be to publish your Yacy peer on the Internet and thus further strengthen the Yacy network.

Other options are: running a hidden service on the Tor network, or changing the Tor Browser to allow it to access local pages.

I think @TheTorProject could help you with the last two options.

**Comment by Orbiter** [comment]
In theory it should be possible to use the torproxy in a chain from a browser to YaCy and then to the torproxy (tell YaCy to use a proxy). But this works only in intranet mode - `.onion` links appear as intranet addresses to YaCy.
