### ISSUE TITLE
Epub parser

### ISSUE THREAD

**Issue by traverseda** [yacy/yacy_search_server#381]
I'm using yacy in intranet mode with a large amount of epub files. Any change of this getting epub parser support in the next couple of months? Unfortunately my java skills are weak, but if not then I'll look for another solution.

**Comment by Orbiter** [comment]
Epub are, as far as I know, just zipped html files. Or one html file and some metadata. We already have a zip parser.

Can you please try the following, as an experiment: take one of your epub files and make two copies where you rename one with `.tar.gz` extension and one with `.zip` extension. Then try to index them with intranet mode and a path to the files as crawl start `file:///<path>/<to>/<files>/`

I am curious if this works..
If yes then we can try to make the parser 'sensible' for epub files.

**Comment by renannprado** [comment]
@Orbiter is there an up to date list of parsers somewhere? I've found in the below page a list of supported parsers [0], but looking at what you just said, there's more than this, but I couldn't find a complete list of the parsers.

[0] https://wiki.yacy.net/index.php/En:FAQ

**Comment by traverseda** [comment]
@Orbiter Sorry, I missed your last comment. Now that I see it I'll run that test once I'm off work.

**Comment by Orbiter** [comment]
just open /ConfigParser_p.html in your peer, there is the whole parser list

**Comment by reger24** [comment]
@Orbiter you are absolutely right - epub = zip containing xhtml and other pictures etx.
here are some example (epub's)
https://github.com/IDPF/epub3-samples/releases/tag/20170606

**Comment by reger24** [comment]
extension "epub" and  mime "epub+zip" added to zipParser, tested in intranetmode worked for the offical sample epubs https://github.com/IDPF/epub3-samples/releases/tag/20170606
