### ISSUE TITLE
Bug (Blocker) when running YaCy @ Windows 10

### ISSUE THREAD

**Issue by yacylover** [yacy/yacy_search_server#382]
Hi,

I just discovered a strange bug when running newer YaCy builds in Windows 10. After a few minutes of a running a YaCy instance, the webinterface becomes unavailable (The page loads indefinitely). No crawls and no other tasks are running at this moment. This doesn't occur on Windows 8, Linux and on the Mac. I also tried several JREs, without any luck. Antivirus or Personal Firewall Programs aren't installed, only the standard one (Windows Defender) from M$.

Can one of our devs look in this issue please?

Best

LA_FORGE

**Comment by yacylover** [comment]
It even occurs under MacOS :-(
Verson 10.14 (Mojave)
Java 12.0.2

**Comment by Orbiter** [comment]
I cannot reproduce this. In case this happens again, make a kill -3 on the yacy process and paste the thread dump which occurs after the kill in the log at DATA/LOG/yacy00.log here.

**Comment by yacylover** [comment]
Hallo Michael, ich bins Stefan ;-) 

vielen Dank für den Befehl + Syntax - wieder was gelernt! Ich hab mal die yacy.conf gelöscht und alles andere. Nur den Solr-Index und die BLOBS habe ich gelassen. Außerdem habe ich die Static IP unter Server Access Settings rausgenommen. Bis jetzt ist es nicht mehr aufgetreten. Wie empfiehlst du XMS und XMX zu einzustellen bei 96 GB RAM für YaCy? Ich habe mehr und mehr die Vermutung, dass es eine "Zu-wenig-RAM-Geschichte" ist und Jetty dann irgendwann im Deadlock hängt, weil im Log garnichts diesbezüglich zu erkennen ist und der Peer ganz normal weiterläuft und auch DHT Transfers macht. Wenn es erneut auftritt poste ich den tread dump hier.

**Comment by yacylover** [comment]
PS. @devs bitte schaut euch [den Fehler](https://github.com/yacy/yacy_search_server/issues/383) mal an. Wenn das gefixt werden kann, kann ich YaCy auf der Arbeit einführen und promoten.

**Comment by virtadpt** [comment]
It happens on Linux, also:  I'm running Yacy v1.922 with OpenJDK v11.0.8.u10-1 (headless), Linux kernel v5.9.6 (64-bit).  I've just upgraded from Yacy v1.92 from source.

**Comment by virtadpt** [comment]
> I cannot reproduce this. In case this happens again, make a kill -3 on the yacy process and paste the thread dump which occurs after the kill in the log at DATA/LOG/yacy00.log here.
I just did this `sudo kill -3 81888` (the PID of the Yacy process on my server as I type this) - no thread dump in the `yacy00.log` file on my server.  Grepping my LOG/ directory the only reference to /thread/i I can find is in a logfile dated three hours ago, and it's not a thread dump at all ("HeadReader close HeapFile citation.index.20201124184421808.blob").  Do you have any suggestions?

**Comment by yacylover** [comment]
@Orbiter  auch nach RAM erhöhen tritt es leider immer noch auf :-(

Hier der Thread Dump:

https://pastebin.com/CHFT99Tu

**Comment by yacylover** [comment]
Second Thread Dump taken in context of the same error (Webinterface stops responding after a few minutes past bootstrap of YaCy):

https://pastebin.com/175Ey800

**Comment by yacylover** [comment]
Third Thread Dump in context of the same error:

https://pastebin.com/C4bWpqae

**Comment by Orbiter** [comment]
Hi Stefan, ich versuche das zu fixen, stehe aber momentan aufm Schlauch. Bin dran!

**Comment by yacylover** [comment]
Hallo Michael. Vielen Dank!! Wenn ich noch irgendwie helfen kann sag bescheid.

**Comment by yacylover** [comment]
Gibt es eine Möglichkeit Jetty zu killen und neuzustarten? Ich frage deshalb, weil der Bootstrap von YaCy bei meiner Indexgröße über 2 Stunden dauert, trotz ultraschneller SSD!

**Comment by Orbiter** [comment]
It looks very good with the latest modifications as communicated in https://searchlab.eu/t/yacy-web-interface-hangs-after-some-time/265
This is also a double to https://github.com/yacy/yacy_search_server/issues/341

> Gibt es eine Möglichkeit Jetty zu killen und neuzustarten? Ich frage deshalb, weil der Bootstrap von YaCy bei meiner Indexgröße über 2 Stunden dauert, trotz ultraschneller SSD!

I was working on that option as well but might be superfluous if the recent fix proves to work well!

**Comment by yacylover** [comment]
Outstanding work! Thank you very much

**Comment by virtadpt** [comment]
Hi.  I tried that and it didn't seem to work.  I cranked the memory allocation up to 32 gigabytes of RAM and it ran only slightly longer - I got about ten minutes of responsiveness out of it.  Disk space is probably not an issue (YaCy is running on a server with 48TB of storage, and only 6TB are in use in total on that box).

YaCy is configured for Robinson Mode so I don't think the effect is due to any other servers out there.

The YaCy instance in question has been online for the last three years, and this only started happening when I upgraded.  I'm considering downgrading just so that I can have access to my indices again.

Do you have any suggestions?

**Comment by virtadpt** [comment]
Followup: I wiped my old install of YaCy, cloned the repo, and rebuilt the server.  I've been able to restore a dump of my index and get YaCy back online.  Aside from the API ignoring authentication (see ticket #354) it seems to be working.
