### ISSUE TITLE
WARC file import: Only one record of the whole WARC-File is processed

### ISSUE THREAD

**Issue by yacylover** [yacy/yacy_search_server#383]
When trying to Index a WARC-File (Tested on Linux and Windows Versions of YaCy) deposited on a local webserver (eg. http://192.168.178.36/tas.warc.gz ) only one dataset (maybe the first) of the whole WARC file is indexed & imported and then the import process terminates.

Please fix!!

You can use the WARC file I created to reproduce the error:

https://anonfiles.com/l3Geo2m5p1/tas.warc_gz

**Comment by Orbiter** [comment]
fixed in https://github.com/yacy/yacy_search_server/commit/d359d521a1efef8fd6681ec884f44c2b9929a29c
