### ISSUE TITLE
Yacy starts doing things on startup

### ISSUE THREAD

**Issue by songproducer** [yacy/yacy_search_server#386]
I didn't start yacy but I can hear the hard drive is doing stuff.

>ps aux | grep yacy

>leo         1339 10.3 43.7 120725404 7160984 ?   SNl  15:41   6:41 /usr/bin/java -Xms15000m -Xmx15000m -server -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Dsolr.directoryFactory=solr.MMapDirectoryFactory -classpath .:lib/J7Zip-modified.jar:lib/apache-mime4j-0.6.jar:lib/bcmail-jdk15on-1.60.jar:lib/bcpkix-jdk15on-1.60.jar:lib/bcprov-jdk15on-1.60.jar:lib/chardet.jar:lib/common-image-3.3.2.jar:lib/common-io-3.3.2.jar:lib/common-lang-3.3.2.jar:lib/commons-codec-1.14.jar:lib/commons-collections4-4.1.jar:lib/commons-compress-1.20.jar:lib/commons-fileupload-1.4.jar:lib/commons-io-2.7.jar:lib/commons-lang-2.6.jar:lib/commons-logging-1.2.jar:lib/commons-math3-3.4.1.jar:lib/fontbox-2.0.15.jar:lib/guava-18.0.jar:lib/httpclient-4.5.12.jar:lib/httpcore-4.4.13.jar:lib/httpmime-4.5.12.jar:lib/icu4j-63.1.jar:lib/imageio-bmp-3.3.2.jar:lib/imageio-core-3.3.2.jar:lib/imageio-metadata-3.3.2.jar:lib/imageio-tiff-3.3.2.jar:lib/jakarta-oro-2.0.8.jar:lib/jaudiotagger-2.2.5.jar:lib/javax.servlet-api-3.1.0.jar:lib/jcifs-1.3.17.jar:lib/jcl-over-slf4j-1.7.25.jar:lib/jetty-client-9.4.17.v20190418.jar:lib/jetty-continuation-9.4.17.v20190418.jar:lib/jetty-deploy-9.4.17.v20190418.jar:lib/jetty-http-9.4.17.v20190418.jar:lib/jetty-io-9.4.17.v20190418.jar:lib/jetty-jmx-9.4.17.v20190418.jar:lib/jetty-proxy-9.4.17.v20190418.jar:lib/jetty-security-9.4.17.v20190418.jar:lib/jetty-server-9.4.17.v20190418.jar:lib/jetty-servlet-9.4.17.v20190418.jar:lib/jetty-servlets-9.4.17.v20190418.jar:lib/jetty-util-9.4.17.v20190418.jar:lib/jetty-webapp-9.4.17.v20190418.jar:lib/jetty-xml-9.4.17.v20190418.jar:lib/jsch-0.1.54.jar:lib/json-simple-1.1.1.jar:lib/jsonic-1.3.10.jar:lib/jsoup-1.12.1.jar:lib/jwat-archive-common-1.1.1.jar:lib/jwat-common-1.1.1.jar:lib/jwat-gzip-1.1.1.jar:lib/jwat-warc-1.1.1.jar:lib/langdetect.jar:lib/log4j-over-slf4j-1.7.25.jar:lib/lucene-analyzers-common-6.6.6.jar:lib/lucene-analyzers-phonetic-6.6.6.jar:lib/lucene-backward-codecs-6.6.6.jar:lib/lucene-classification-6.6.6.jar:lib/lucene-codecs-6.6.6.jar:lib/lucene-core-6.6.6.jar:lib/lucene-grouping-6.6.6.jar:lib/lucene-highlighter-6.6.6.jar:lib/lucene-join-6.6.6.jar:lib/lucene-memory-6.6.6.jar:lib/lucene-misc-6.6.6.jar:lib/lucene-queries-6.6.6.jar:lib/lucene-queryparser-6.6.6.jar:lib/lucene-spatial-extras-6.6.6.jar:lib/lucene-suggest-6.6.6.jar:lib/metadata-extractor-2.11.0.jar:lib/metrics-core-3.2.2.jar:lib/noggit-0.6.jar:lib/org.restlet.jar:lib/pdfbox-2.0.15.jar:lib/poi-3.17.jar:lib/poi-scratchpad-3.17.jar:lib/slf4j-api-1.7.25.jar:lib/slf4j-jdk14-1.7.25.jar:lib/solr-core-6.6.6.jar:lib/solr-solrj-6.6.6.jar:lib/spatial4j-0.6.jar:lib/stax2-api-3.1.4.jar:lib/weupnp-0.1.4.jar:lib/woodstox-core-asl-4.4.1.jar:lib/xml-apis.jar:lib/xmpcore-5.1.3.jar:lib/xz-1.8.jar:lib/yacycore.jar:lib/zookeeper-3.4.10.jar: net.yacy.yacy
leo        21645  0.0  0.0   6384  2524 pts/0    S+   16:46   0:00 grep --color=auto yacy

**Comment by Orbiter** [comment]
If you installed YaCy as debian package, it is automatically started as daemon, like any other daemon.

In all other cases YaCy should not be started automatically.

**Comment by songproducer** [comment]
I didn't install YaCy as a Debian package, but I did install the YaCy grid crawler, loader, MCP, search and parser. I suspect it is these that have installed a service.

I can't find any services called YaCy though.

**Comment by songproducer** [comment]
Ok. Any ideas how I can stop original YaCy from starting automatically?

**Comment by virtadpt** [comment]
What services do you have running that might start Yacy?

`systemctl | grep -i yacy`

**Comment by Orbiter** [comment]
https://wiki.yacy.net/index.php/En:DebianInstall#Managing_YaCy might help, if you have a debian service running:
`/etc/init.d/yacy stop`

To uninstall the debian version: `apt-get purge yacy`
