### ISSUE TITLE
i can't set max ram?

### ISSUE THREAD

**Issue by Tarcaxoxide** [yacy/yacy_search_server#387]
so i gave yacy 10240MB (10GB) of ram but in the System Status it says the Ram max is 533.5MB (0.5335GB).
and i know i have enough ram cause i have 47GB available to me so i definitely know its not that.

**Comment by Tarcaxoxide** [comment]
let me know if there is any specific information that could help.
the only thing that i can point out without know what you might need is that i am running gentoo linux.

**Comment by Orbiter** [comment]
The actual amount of RAM taken from the system is managed by the JVM. It is possible that you give YaCy more memory than it actually demands. Therefore I consider this correct.

**Comment by Tarcaxoxide** [comment]
> The actual amount of RAM taken from the system is managed by the JVM. It is possible that you give YaCy more memory than it actually demands. Therefore I consider this correct.

ok because its still saying
"pause reason: resource observer: not enough memory space"

**Comment by Tarcaxoxide** [comment]
i'm sorry to be re-opeing this but i just noticed something that might also retain to this issue??
i've noticed that local crawls keep pausing by themselves.
sometimes when i'm flipping through the pages i'll just end up being paused.

**Comment by Orbiter** [comment]
Please check if in http://localhost:8090/PerformanceMemory_p.html the "simulate short memory status" is NOT switched on and please check which memory strategy is provided in the checkbox right below.
