### ISSUE TITLE
Please make one Dockerfile for arm64 architecture

### ISSUE THREAD

**Issue by manalejandro** [yacy/yacy_search_server#388]
Hi, i have created one docker image based on the [Dockerfile](https://github.com/yacy/yacy_search_server/blob/master/docker/Dockerfile) but need to change the FROM image with arm64v8/openjdk:16-buster, tested and works perfectly on Raspberry Pi4 with arm64 architecture, thanks

**Comment by Orbiter** [comment]
I'm on it, but the Raspberry Pi OS Lite version I am using from https://www.raspberrypi.org/software/operating-systems/ identifies itself as
```
$ uname -a
Linux node06 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l GNU/Linux
```
which is a 32bit arm

So far I don't know where to get the arm64 buster version. I will work on a docker image that fits in here.

Can you please meanwhile point me to the exact image that you want to use on your RPi4?

**Comment by manalejandro** [comment]
Sure, you can download it from the official repository

https://downloads.raspberrypi.org/raspios_arm64/images/

Thanks and regards

**Comment by Orbiter** [comment]
ah!
would https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2020-08-24/2020-08-20-raspios-buster-arm64-lite.zip be ok for you as well?

**Comment by manalejandro** [comment]
Yes, the only thing that differentiates lite version is that does not have graphical environment

**Comment by Orbiter** [comment]
ok I just pushed `yacy/yacy_search_server:aarch64-latest` - please test

**Comment by manalejandro** [comment]
Great, i don't have to compile more images anymore :smiley: 

Works perfectly as you can see in https://yacy.manalejandro.com, thanks a lot :+1:

**Comment by Orbiter** [comment]
dockerfile is in https://github.com/yacy/yacy_search_server/commit/13e42c2dd27894043892a2600679cbecfba05339
