### ISSUE TITLE
Indexing SPA web apps

### ISSUE THREAD

**Issue by andrewheadricke** [yacy/yacy_search_server#391]
Is it possible to index/scan SPA applications with Yacy? Frameworks like Vue and Mithril don't actually have any HTML, its all rendered from Javascript, as far as I can tell Yacy cannot index these types of sites.

Is there an API for manually adding indexes into Yacy? i'm thinking about creating a selenium style renderer for SPA sites and feed the content into Yacy manually with the corresponding URLs.

**Comment by Orbiter** [comment]
Right, this is a problem with legacy YaCy. In YaCy Grid we have a virtual Browser as part of the crawler which runs all the Javascript of the crawled web page to get the dynamic content. This is a very CPU and network-intensive task, much heavier than the crawling in legacy YaCy.

I am planning to integrate the YaCy Grid crawler abilities into legacy YaCy in future releases, so then that would be possible. Until then you would need to try out YaCy Grid.

**Comment by andrewheadricke** [comment]
Thanks, i hadn't heard of yacy grid. 

Yeah I don't think I would enable a virtual browser crawler for all sites, I would prefer to use it sparingly just on websites i'm interested in. Then let the indexes i've created propagate through the p2p network.

Rather than embedding a virtual browser maybe consider a simple indexing API, so others can extend the index with their own crawlers.

**Comment by Orbiter** [comment]
An API for that requires a data format to hand-over externally crawled web pages. We have that in the shape of WARC-files. Just create WARC files with whatever tool you prefer (i.e. with wget, see https://archiveteam.org/index.php?title=Wget_with_WARC_output ) and the import them with the WARC importer.

I consider to make the import more convenient using the SURROGATE process (like: just put the warc file into DATA/SURROGATE/IN/).

**Comment by Orbiter** [comment]
I actually checked that the surrogate process takes these files! Should work!

**Comment by andrewheadricke** [comment]
Are you saying legacy Yacy already supports WARC import via `data/surrogate/in`? Or is this a Yacy grid feature?

**Comment by Orbiter** [comment]
Yes, legacy YaCy supports the import of WARC via data/SURROGATE/in

**Comment by andrewheadricke** [comment]
What's the best way to debug the warc import? I tried using the `DATA/SURROGATES/IN` and the web form in the admin interface, there is no feedback and I can't find any information in the logs.
