### ISSUE TITLE
Please sign this software (esp. Windows version)

### ISSUE THREAD

**Issue by Jon-guy30** [yacy/yacy_search_server#395]
I have a small request to make, why isn't this software signed? I'm not seeing any GPG keys anywhere. Singing would give this project an additional level of trust, and it's free. Two projects I recommend are: GPG4Win and Minisign. https://jedisct1.github.io/minisign/ 
Minisign in even more lightweight and easier to use than GPG. It only does signing, not encryption. One doesn't need an expensive certificate for file signatures anymore. In this modern cybersecurity landscape in my opinion all software should be signed. 

Another small thing, why aren't the tags in the releases page updated, since this software is actively developed? One might think it's old software as I first thought, but it's actually not.

Thank you for this interesting project, and happy new year!

**Comment by Orbiter** [comment]
Code signing has been done with the Debian  release but dropped together with that release in favour of docker releases. 

As a better replacement I recommend to build the code from GitHub yourself.
