### ISSUE TITLE
Make it for android please

### ISSUE THREAD

**Issue by Evething48** [yacy/yacy_search_server#396]

**Comment by Orbiter** [comment]
The yacy_search_server - the name says that - is a server technology. Thats not the only reason why YaCy cannot be implemented as Android application, but a good one. Sorry!

**Comment by Evething48** [comment]
yes I just want to know don't say harshly like that!

Pada tanggal Sel, 12 Jan 2021 16:54, Michael Christen <
notifications@github.com> menulis:

**Comment by Orbiter** [comment]
No harshness intended.
We actually had an android search client, which is now a bit outdated but maybe works, here:
https://github.com/yacy/yacy_search_androidclient
This thing maybe needs someone who cares about it.
