### ISSUE TITLE
Support crawling of password protected websites

### ISSUE THREAD

**Issue by winux1** [yacy/yacy_search_server#400]
I think ability to index a password protected website would be a good feature to support. What do you think about it? Is it possible?

**Comment by Orbiter** [comment]
a long time ago we decided that this does not fit in any use case where someone who searches does not know the same passwords as the one used to crawl the sites. But even if this would be the case then YaCy would need to share the same authentication system to prevent that the indexing YaCy instance is a security risk for the crawled target. That means either
- YaCy would need a tight integration with the target host (which is either not doable or too far to go), or
- YaCy (or another indexer) should be integrated into the target system in between password protection and content

The second option is the only way to go and it can be done - without any changes to YaCy.
