### ISSUE TITLE
extensive logging for REJECTED urls

### ISSUE THREAD

**Issue by onlyjob** [yacy/yacy_search_server#414]
During normal crawling Yacy floods logs with many `REJECTED` URLs. All of them are valid, rejected due to exclusion filter or other reason.

Is it possible to suppress/disable writing REJECTED urls to log? 

I've checked `yacy.logging` and tried to reduce verbosity level of some classes but nothing seems relevant to `REJECTED` URLs...

Please advise.

**Comment by okybaca** [comment]
You can use "grep" tool on CLI, when filtering the logs, [as descibed in FAQ](https://yacy.net/faq/#something-seems-not-to-be-working-properly-what-should-i-do).
A lot of lines in the log are overwhelming, and the log rotates quickly, if you're crawling. 
I'd suggest the option of separating the crawl.log (entries from the crawler and indexer and p2p.log (entries about peer pings and RWI transfers). Then the most important entries would remain in yacy00.log and would be available for the inspection.

**Comment by okybaca** [comment]
solved with #616
