### ISSUE TITLE
extending to semantic search by using sigmakee

### ISSUE THREAD

**Issue by jfferson** [yacy/yacy_search_server#421]
Hi,

Regarding how wanted and evident but of complex implementation are semantic technologies, I am making notice of a reliable open source project for introducing semantics and ontology to softwares. Some relevant details for the implementation on yacy are that the code is entirely written in Java, does have a class for integration with a digital language vocabulary, called WordNet and one way it works is by outputting taken inputs to theorem provers (E and Vampire) and sending commands regarding logical processing and output. An studied use that is relevant to yacy is of word disambiguation, written on article talking about connecting WordNet to sigmakee and as noted there is already a class for using WordNet within sigmakee. For Disambiguation purposes the class com.articulate.sigma.wordNet.WSD can be used

**Comment by jfferson** [comment]
sorry, closed because I failed to consider there is no open implementation for the disambiguation

**Comment by thkoch2001** [comment]
I'm not sure whether this is a real issue or spam generated by a bot, thus closing. Please try to rephrase if this is a real request.
