### ISSUE TITLE
Netscan - Abuse message from my hoster

### ISSUE THREAD

**Issue by xundeenergie** [yacy/yacy_search_server#424]
Yesterday i tried yacy again. Installed it, started the service and tried a little... 

Then i got an abuse-message from my hoster. Something did a netscan on all 10.* IP-adresses on port 8090.
The start of the flooding was exact the start of yacy service. The port is the configured Port for yacy...

Is this "normal" behaviour of yacy or is there something wrong?

**Comment by Orbiter** [comment]
yes, thats happening, thank you for reporting.

The IP scan comes from latest experiments where I try to run YaCy in a kubernetes cluster and where YaCy is trying to do a auto-discovery of scaled YaCy instances within that cluster. I had no idea that this behaviour results in abuse-warnings.

So the obvious reflex would here to remove that function. However, how should a peer-to-peer system do an auto-discovery in intranets then? I will consider a flag to switch this on on demand and let it be off by default.

**Comment by Orbiter** [comment]
Code was introduced in https://github.com/yacy/yacy_search_server/commit/198826c362cd31aa573f15b171ad7714fd1ab4e5
..see `scanForOtherYaCyInIntranet()`.
I will implement a flag to switch this on only by request.
