### ISSUE TITLE
Is it possible to proxy indexing? [question]

### ISSUE THREAD

**Issue by nonetrix** [yacy/yacy_search_server#425]
To my understanding when yacy indexes a site it just sends a https get request from your network, I'm not really a big fan of the idea of my computer randomly sending https requests exposing my IP to random websites, and probably other information.

Would it be possible for when it indexes a website to do it though a proxy or VPN or even Tor?

**Comment by Orbiter** [comment]
Yes, just use a VPN and YaCy also just sees a VPN
