### ISSUE TITLE
increase prominence of passwd.sh

### ISSUE THREAD

**Issue by CouldBeThis** [yacy/yacy_search_server#427]
As some others (eg #409)  have, I missed the instruction to set password. took a while searching around to find it. Like in #409 I was also misled thinking it's some sort of java issue. I am wondering if the info can be placed somewhere more prominent. The instructions sound like they are completed in the prior step so I guess I did not continue scrolling. 

Ideally to me would be redirect unauthorized users to page with meaningful error. 

But other options would be: 

- Make error more meaningful (not sure if possible)

- Put note on main search interface (may not be a good idea for all use cases)

- Some sort of first run script that would take care of it. But people would still need to know to run it so does this solve anything??

- In the banner that runs terminating `>> YaCy started as daemon process. Administration at http://localhost:8090 <<`

- ./startYACY.sh check and if needed prompt user 

- add some sort of ⚠️ icon or other attention-grabbing visual to download/installation page where the information currently resides. 

- add "troubleshooting" section before the install instructions are completed, where it will be seen.

**Comment by okybaca** [comment]
solved in [#544](https://github.com/yacy/yacy_search_server/issues/544#issuecomment-1780059559)
