### ISSUE TITLE
change default user agent and make agentName parameter useful

### ISSUE THREAD

**Issue by iwconfig** [yacy/yacy_search_server#429]
hello, I call `/Crawler_p.html` to crawl urls directly. I want to set another user agent string as default and not rely on `agentName` parameter to `/Crawler_p.html`. Here's the thing:

1. I cannot find how, and I suspect it's not possible, to set another user agent as default and thus NOT use `yacybot` at all whatsoever.
2. even if I choose not to succumb to my misery, passing `agentName=googlebot` to `/Crawler_p.html` does absolutely nothing.
3. however if I use my mouse, go to "Advanced crawler" in the web UI, manually set "googlebot" as my preferred user agent and click "Set New Crawl Job", it works as expected 🎉
4. the problem with (3) is that
	1. its not automatic
	2. even if I call it directly with parameters, it doesn't execute automatically; I have to click "Set New Crawl Job".
	3. OK but wait there's more:
		- say I'd settle with doing (4.ii), you would think all is well then but ohoho no! IT DOESN'T DO ANYTHING WITH `agentName`!!

---

Please help me. :slightly_smiling_face:

**Comment by kromonos** [comment]
Any updates on this bug? I really would love to set this too.

**Comment by Orbiter** [comment]
> 2. even if I choose not to succumb to my misery, passing `agentName=googlebot` to `/Crawler_p.html` does absolutely nothing.

you must pass `agentName=Googlebot` not `agentName=googlebot` (Uppercase 'G') to the get call.
