### ISSUE TITLE
WARC index import doesn't work in docker

### ISSUE THREAD

**Issue by raspher** [yacy/yacy_search_server#431]
Well, it works but not as expected. To have it work I've to manually put WARC file to yacy/SURROGATES path. This results in images not indexed at all

```
I 2021/12/08 07:59:00 SWITCHBOARD * Not Condensed Resource 'https://akudama.wbijam.pl/grafika/newsy/07_logo.gif': indexing of media files not wanted by crawl profile

I 2021/12/08 07:58:59 SWITCHBOARD * *Indexed 415 words in URL https://akudama.wbijam.pl/pierwsza_seria-08.html [gAgR6BTC5z5g] Description: Akudama Drive - wszystkie odcinki anime online. MimeType: text/html | Charset: UTF-8 | Size: 4050 bytes | LinkStorageTime: 27 ms | indexStorageTime: 3 ms
```

What does not work? Well, all webui part. I cannot use any method available. Tried .WARC.GZ and .WARC.

**OS**: Windows 10
**Yacy inside docker**: YES
**YaCy version**: 1.925/9000

Is there any minimum RAM required for such process? Maybe my network is too slow to get data from Internet Archive, but import from file should work.

**Comment by Orbiter** [comment]
this works as designed, images are not indexed. However, this does not mean that YaCy is not able to find images that is coming from war files because it searches for img tags inside your html.

This is not related to memory settings or available memory. Image files have no text inside - there cannot be anything indexed.

**Comment by raspher** [comment]
Dude, did you try ever import warc files? This doesn't work! It's not about images not indexed, but importing on windows 10

**Comment by raspher** [comment]
Idk where issue is, but via the Webui importing doesn't work.

**Comment by Orbiter** [comment]
ok but the issue started with the words "it works but not as expected." and then the reference to images, as if that was the only thing that does not work.

Please be very specific:

- what have you done, with every step
- what happened then
- what did you expect and did not work
