### ISSUE TITLE
Is log4j-over-slf4j-1.7.25.jar active while running server?

### ISSUE THREAD

**Issue by JJenkx** [yacy/yacy_search_server#432]
Is log4j-over-slf4j-1.7.25.jar active while running server? Is Yacy server still safe?

**Comment by Orbiter** [comment]
sure is log4j-over-slf4j active! This is the lsf4j api which catches all the log4j api calls by implementing the log4j api.
It _implements_ the log4j api, it is not _the log4j_ api.
If you want to see this by first hand, look inside the code of log4j-over-slf4j:
https://github.com/qos-ch/slf4j/tree/master/log4j-over-slf4j/src/main/java/org/apache/log4j

Many libraries in YaCy depend on log4j, but log4j is not inside the packaged application; instead slf4j bundles all these calls and forwards them to native Java logging.

Just look into our jar library, which we use to bundle the application: https://github.com/yacy/yacy_search_server/tree/master/lib

There is no log4j inside.
