### ISSUE TITLE
Memory reserved for JVM can only be 5 digits long.

### ISSUE THREAD

**Issue by ZeroCool940711** [yacy/yacy_search_server#434]
Hi there, seems like the `Memory reserved for JVM` value on the `Performance_p.html` page can only be set to a maximum of 5 digits, meaning you can only have it set to a maximum of 99,999MB or 97.6GB of RAM, some of us might want to run yacy on a server that has more than that amount of RAM that we can allocate for Yacy but we will only be able to use a fraction of it, would be nice if this field could allows us to set more than that, it also seems like its just a client side issue with the field itself allowing only a maximum lenght of 5, if you inspect the page and you go to `<input name="Xmx" id="Xmx" type="text" size="5" maxlength="5" value="122880">` you can change the `maxlenght` value to something bigger and it will accept the changes on the server side and the new configuration will be saved, I also have to point out that some time ago this was not a problem, I remember the last time I used yacy which was a couple of months ago and I was able to set there a value that was bigger than 5 digits without any issue, so, it was a recent change. Hope you guys can change it back or increase it a bit as its not something that probably will be easy to do and has no effect for normal people but will be useful for those that might need it.

**Comment by virtadpt** [comment]
This.  I have 256 gigs of RAM in my YaCy server, and not being able to use it all is kind of limiting.

**Comment by Orbiter** [comment]
oh wow, ok!
