### ISSUE TITLE
Latest gradle dist zip is not working

### ISSUE THREAD

**Issue by Dalethium** [yacy/yacy_search_server#450]
I am not sure if it's on my end or not, but the latest yacy build is leading to empty responses from servlets. I am running with authentication for all pages enabled if that matters.

yacy_v1.925_20220125_10192.zip <-- this build IS functional
yacy_v1.925_20220127_10212.zip <-- this build is not.

It's worth noting that it appears to still crawl based on the logs, but even with setting all the log settings to "all/fine" I don't actually see any errors.

```
D 2022/01/27 14:24:47 FILEHANDLER * YaCyDefaultServlet: Resource /yacy/[pageaccessed].html=file:///F:/Yacy/htroot/yacy/[pageaccessed].html
D 2022/01/27 14:24:47 FILEHANDLER * YaCyDefaultServlet: uri=/yacy/[pageaccessed].html resource=file:///F:/Yacy/htroot/yacy/[pageaccessed].html
```

This is as much as I get. 

It is running on windows, if that helps.

Additionally, I tried installing both the zip in ``yacy_search_server\build\distributions`` and the one in ``yacy_search_server\build\distributions\legacyDistFiles`` (the latter being notably larger) -- neither worked, both were freshly built.

I am not sure if this is on my end or my fault, but I thought it was worth reporting.

Oh, and, if I refused to login, jetty served a functional error page:

```
URI: | /Crawler_p.html
-- | --
401
Unauthorized
net.yacy.http.servlets.YaCyDefaultServlet-2ec11381

```

**Comment by reger24** [comment]
There was a issue with the legacy tar archive *tar.gz" (potentially also effecting the zip) on the lib directory which was fixed in last commit https://github.com/yacy/yacy_search_server/commit/4a55bb751516bcd97505e6a573effe7ac0e594e8

Tried both zip's -> fresh install (unzip and call startYACY.bat)  also enabled authentication

result: works fine here on Win 
- can not reproduce the issue (with latest revision 10214)
- mabe give it one more shot

**Comment by Dalethium** [comment]
I'll give this a try after work and let you know!

**Comment by Dalethium** [comment]
Sorry for the wait @reger24! The newest build worked! It also seems to have fixed a crash I was having. I'll close this now :)

**Comment by reger24** [comment]
OK, 
Thanks for the feedback
