### ISSUE TITLE
Moby Lexicon resource link

### ISSUE THREAD

**Issue by Dalethium** [yacy/yacy_search_server#455]
https://archive.org/details/mobythesauruslis03202gut
https://www.gutenberg.org/ebooks/3202
https://en.wikipedia.org/wiki/Moby_Project

These are the details I could find on the moby project linked on ``DictionaryLoader_p.html`` -- I recommend perhaps we update the url to the Wikipedia page? The page we link seems to have been down for more than half a dozen years.

**Comment by reger24** [comment]
- updated link in DictionaryLoader_p.html to "https://www.gutenberg.org/ebooks/3202"
- as the activation of this feature relay's not on a actual download but on a provided/modified files in addon/synonyms/mobythesaurus_en_yacy imho no more action needed.

Thanks for the info.
