### ISSUE TITLE
PLEASE don't forget to CLOSE ISSUE when topic is fixed, done or answered

### ISSUE THREAD

**Issue by reger24** [yacy/yacy_search_server#457]
The github issue system intends that issues are closed by author of the issue,
so the author can indicate that problem has been fixed or response was sufficient.

Therefore please don't forget to close a issue if it has been handled, to prevent that it is closed premature by the YaCy team.

**Comment by thkoch2001** [comment]
Hi @reger24 
I've just been added to the project and make a triage of the issues list. In the spirit of your request I'm closing this issue. :-)
If you're still active with YaCy I'd love to chat.
It might not be realistic to wait for issue reporters to close their issues.
