### ISSUE TITLE
Update java version to at least 11

### ISSUE THREAD

**Issue by thkoch2001** [yacy/yacy_search_server#465]
The build.gradle file says:

    java.sourceCompatibility = JavaVersion.VERSION_1_8
    java.targetCompatibility = JavaVersion.VERSION_1_8

However Debian ships already with Java 11 as the minimum version. This should normally not be a problem, but I wonder whether there is still a motive in 2022 not to update at least to Java 11?

On the other hand I saw some hundreds of build failures in Eclipse with Java 17. So it might be worth to check at least the upgrade to Java 11 and prepare already for Java 17.

**Comment by thkoch2001** [comment]
I looked into the "hundreds of build failures in Eclipse with Java 17" and found the answere here: https://github.com/eclipse/eclipse.jdt.ls/issues/1050#issuecomment-625793780

> You simply need to exclude xml-api from your dependencies, when compiling against JDK > 1.8

The error message in eclipse was:

> "the package org.xml.sax is accessible from more than one module"

Still the main issue remains that you might want to consider upgrading to newer Java.

**Comment by Orbiter** [comment]
backlog.

for now I want to stick to Java 8

**Comment by Swissbite** [comment]
@Orbiter Didn't you resolve this issue with your commit 6bd5f49c412be8edaadc5bc707dcd2a521207da5?

**Comment by Orbiter** [comment]
Yes
