### ISSUE TITLE
Consider keeping ant

### ISSUE THREAD

**Issue by thkoch2001** [yacy/yacy_search_server#467]
I'm sorry to be late to this as you just finished porting your build system to gradle in #377.

The motivation of not committing dependencies in the Git repository is great but could have been achieved also with [ivy](https://ant.apache.org/ivy/), if I'm not mistaken.

For Debian packaging gradle is at the moment unfortunately not available. The Debian gradle package is still stuck at version 4.4.1 because afterwards gradle started to use Kotlin which needed to get packaged first for Debian. (More details in Debian bug [#926714](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=926714))

Still the Debian Java team [recommends to avoid Gradle](https://wiki.debian.org/Java/Packaging/Gradle) due to frequent incompatible changes:

> [...] Gradle is also known for frequent incompatibilities which is why upstream recommends to depend on a certain version of Gradle to avoid that kind of breakage. Packaging multiple versions of Gradle is not very Debian-like though because it leads to code duplication, more maintenance burden and possibly more security risks.
> 
> You will have to patch the build.gradle file most of the time, to remove unneeded plugins or make the build system Debian compliant, e.g. prevent any downloads from the internet at build time and use system libraries instead. [...]
> 
> If you have a choice, we recommend to use a different build system like Ant or Maven which are better supported in Debian and are more stable when it comes to Debian Java packaging.

Could you consider keeping the ant build around? I could help with providing the necessary ivy integration to get rid of committed jars.

**Comment by thkoch2001** [comment]
I've started a branch to show how Ant+Ivy would look like:
https://github.com/thkoch2001/yacy_search_server/commit/7d292eae17227e9579d614e96fe87b88ebcc5b32

There are two things left to do:
- add Ant code to download Ivy as can be mostly copied from the Ivy documentation: [example build.xml](https://ant.apache.org/ivy/history/2.5.0/samples/build.xml)
- make sure that the downloaded artifacts match exactly what we got now in lib/ by fine-tuning the transitive dependencies

Especially the latter would take some time. Therefor I'd kindly get some feedback beforehand whether you'd consider merging a PR like this. Thank you!

**Comment by thkoch2001** [comment]
I've finished the ivy.xml file for the lib/ folder in my branch:
https://github.com/thkoch2001/yacy_search_server/commits/use_ivy

I need to check now how to do the libt/ folder. It would probably be easiest to move the content of the libt/ folder to the lib/ folder. I expect that ivy does usually manage all dependencies in one folder.
I should then also use ivy to generate a classpath and thus get rid of the jars list in build.xml.

**Comment by Orbiter** [comment]
ant works for the linux release and also for the docker image.
I still want to revert the deletion of the gradle build, but for now ant works so far.
We handle Windows and Mac releases in separate issues.
