### ISSUE TITLE
consider abandoning GitRevTask

### ISSUE THREAD

**Issue by thkoch2001** [yacy/yacy_search_server#474]
The libbuild/ folder contains a small java class and ant task used to make three properties available to the ant build:

- branch - only echoed during build but not further used
- releaseNr - used as the YaCy revision nr
- DSTAMP - date of the HEAD commit and used apparently as build Date, which is semantically wrong

It seems, that this is a lot of code and infrastructure compared with what it is actually used for. Could we just set a version number in a property file committed to git and remove the whole libbuild folder and related stuff?

**Comment by Orbiter** [comment]
we can abandon this process.
However, using a date suffix for releases is in my opinion the most transparent way to communicate the production process of "Nightly" releases, created by a CI script. A runner is now in place, so we could do that.
