### ISSUE TITLE
ant compile, test lead to dirty worktree

### ISSUE THREAD

**Issue by thkoch2001** [yacy/yacy_search_server#477]
If I have a clean worktree (`git status` says "nothing to commit, working tree clean") than I should still have a clean worktree after executing `ant compile`, `ant test` or any similar build step.

Right now,

- `ant compile` changes the file `source/net/yacy/peers/operation/yacyBuildProperties.java` which is under version control and
- `ant test` writes many `/TEST-*.txt` files.

Rationale:

Developers should use `git diff` and `git status` often to produce clean, small and understandable commits. Any pollution in the output of these commands potentially leads to low quality commits.

**Comment by Orbiter** [comment]
I removed this in the last days
