### ISSUE TITLE
Unable to access yacy 403

### ISSUE THREAD

**Issue by soredake** [yacy/yacy_search_server#48]
```
HTTP ERROR: 403

Problem accessing /Status.html. Reason:

    proxy use not allowed (see Advanced Settings -> HTTP Networking -> Transparent Proxy; switched off).

Powered by Jetty://
```

**Comment by reger24** [comment]
Looks like you access YaCy with a proxy request but haven't switched the transparent proxy feature on
(see page http://localhost:8090/Settings_p.html?page=ProxyAccess )
Without a little bit story about, when and how you receive the error msg not much chance to assist.

**Comment by Orbiter** [comment]
usage, not a bug
