### ISSUE TITLE
Missing some mp3 files when search

### ISSUE THREAD

**Issue by EvgeniyDoctor** [yacy/yacy_search_server#481]
I have my local website that available only in my home network. I crawl a folder that has 56 mp3 files + thumbs.db. No sub directories. But when search "filetype:mp3" I see 42 files only. Where is 14 more mp3 results? Can you explain this to me, developers?

For example, I have 2 Tiesto's track in this folder:
- Tiesto - Secrets.mp3
- Tiesto & Dzeko - Halfway There (feat. Lena Leon).mp3

If I search "Tiesto", I see only the last one. Why there is no "Tiesto - Secrets.mp3" in the search results?

I use yacy in intranet mode. If I open this link in my website, there will be 57 files. If I check this link in "Index Administration", I see 57 entries as a plain text. I tried "Advanced Crawler" and crawler in "Load Web Pages, Crawler" with all checked checkboxes. So, what's wrong?

**Comment by frankenstein91** [comment]
Can you check `file *` for that folder? Maybe they aren't seen as mp3

**Comment by frankenstein91** [comment]
after one year of no feedback 

I will close the problem
