### ISSUE TITLE
Noindexing parts of page

### ISSUE THREAD

**Issue by Starkmann** [yacy/yacy_search_server#49]
I would need a possibility to not index a part of a page, for example the footer.
https://en.wikipedia.org/wiki/Noindex#Noindexing_part_of_a_page

I would sponsor this feature if it is not existing.

**Comment by Marx1st** [comment]
I second this feature! It would be great to have a filter eg. "if <div id=content> exists, only index that...

**Comment by Marx1st** [comment]
There are several solutions for Apache Nutch. Maybe those can be used for implementing this in Yacy?

https://github.com/BayanGroup/nutch-custom-search

And there is the OpenSearchServer project. There you can add XPATH excludes for the HTML crawler, etc.

http://www.opensearchserver.com

**Comment by luccioman** [comment]
Indeed the "Custom Search Tools For Nutch" you mention seems to offer many possibilities. But maybe a bit complex... 
What about including first only CSS style selectors support in YaCy, in the form of exclude/include filters to the advanced crawler? Don't you think this could already cover many use cases?

**Comment by Quix0r** [comment]
Isn't this done with current `master` and ignoring a comma-separated list of CSS classes?

**Comment by Starkmann** [comment]
Seems like #158 is duplicate of this issue. 

As far as I understand the commit we can enter a list of css classes which we want to ignore. That's great news.

**Comment by Starkmann** [comment]
For me it can be closed.

**Comment by luccioman** [comment]
Ok I close it, thanks for your feedback @Starkmann
