### ISSUE TITLE
SevenZip/J7Zip code does not get built from source and has no license information

### ISSUE THREAD

**Issue by thkoch2001** [yacy/yacy_search_server#491]
The code under `libbuild/J7Zip-modified` is apparently the source code for `lib/J7Zip-modified-1.0.2.jar`. There are at least 4 problems here:

a. The source code does not get built by the built system. So there is no (easy) way to make changes or to even assure that the jar file indeed contains what the source code intends.
b. There is no information about license and copyright of the code.
c. There is no information why the code was copied and modified in the first place and whether and how we can go back to the upstream project.
d. We don't know about security issues in the code that are already fixed in the upstream project. Extracting files downloaded from untrusted places has caused security issues before in other projects.

My preferred solution would be to review, why the code was forked in the first place and whether we can somehow use the upstream project now. Probably we could upstream a patch to make the upstream project usable for YaCy.

Alternatively (maybe even better) would be to delete the SevenZip parser. Is SevenZip still relevant enough to warrant the maintenance cost for this code?

**Comment by Orbiter** [comment]
the 7zip library was the only one which is not available from maven. I recently removed the library and the parser from the code.
