### ISSUE TITLE
Telegram Channel/Groupe Support

### ISSUE THREAD

**Issue by hermann-san** [yacy/yacy_search_server#492]
Hi, 
it would be great to have support for public Telegram channels and groups. Nowadays it has become somewhat popular to have a public support group or info channel on Telegram.
I guess it would probably require a Telegram bot which would have access to the channels and groups and could store an export on the YaCy Server, where YaCy could fetch it from (with a YaCy component to be developed).
Regarding the results, most of the channels are even accessible via a browser (without login)

A solution without a telegram bot would be a Telegram export of a complete channel or group (everything (or selected timeframe) to one or several html files (depending on the size of the export)
This may work without additional code development but may be limited in functionality.  In order to get to the results, the export would need to be stored somewhere. There result would be a single,  large html file (i.e. no direct link to the telegram message itself). Updates would be manual.

There is a RSS Bridge where the latest messages of a channel can be fetched. The RSS-bridge  is also available on Yunohosts and supports many more Websites (like Twitter, Mastodon, Facebook, Reddit9, Wordpress, Youtube etc.). It could be used with the YaCy index import export RSS function for getting updates from those pages.
I've tried it with Twitter and it works fine, but with Telegram, I don't get the parsed sentences or any content from the posts. The entries are crawled, but not in a proper way. However, I can see the content of the posts in the plaint text view of the Results for Local Crawling. It's just not visible in parsed sentences and also I can't find these posts with a local Yacy search
https://github.com/rss-bridge/rss-bridge

**Comment by frankenstein91** [comment]
What is wrong with the IRC? 
IRC can even bridged to xmpp and matrix.

**Comment by frankenstein91** [comment]
How about just extend the IRC to matrix?

https://matrix.to/#/!beCIqmmCpcQxJKmKSX:matrix.org?via=tchncs.de&via=matrix.org&via=matrix.nogafam.es

**Comment by hermann-san** [comment]
I'm already on Matrix, but it's very hard to convince most of the 700 million users on Telegram.  Matrix needs to become even better then it is right now.  Bridges need to be improved. There is even a Telegram to Matrix bridge, but it's not perfect. 
It's simply hard to fight against a billionaire who has vast amount of resources and the open source community is not able to organize and setup huge crowd funding's to further develop Element or other FOSS alternatives.  

Either way, I hope that it's at least possible to fix the YaCy RSS Telegram issue. I just can  get new channel postings via the RSS-bridge into YaCy, even though that should already work, as of today.  It appears as a regular RSS feed. Other RSS imports into YaCy work fine for me, but not Telegram imports

**Comment by frankenstein91** [comment]
And which RSS feed URL do you use?

**Comment by hermann-san** [comment]
2  examples
https://rss-bridge.ggc-project.de/?action=display&amp;bridge=Telegram&amp;username=landluftbio&amp;format=Atom
https://rss-bridge.ggc-project.de/?action=display&amp;bridge=Telegram&amp;username=blocktrainer01&amp;format=Atom

**Comment by frankenstein91** [comment]
Does it work like that:

`https://rss-bridge.ggc-project.de/?action=display&bridge=Telegram&username=blocktrainer01&format=Atom`

Somehow on Android your link wasn't working with the `amp;` in the URL. I'm currently not able to test it out with yacy RSS import.

Also there will be an update to the bridge. https://matrix.to/#/!PuqITHCyThkDMUHoMK:ggc-project.de/$4qOP0A9iMzDBYXYIK9MScknR76WCMRnPWdhAB_Gah6E?via=tchncs.de&via=ggc-project.de&via=matrix.org

**Comment by hermann-san** [comment]
@frankenstein91 thanks for looking into this. Unfortunately it's still not working. Here is the result of one of the posts.

![grafik](https://user-images.githubusercontent.com/7679654/180672214-ee3d4667-50c5-42ee-b2aa-44a6fe8db4cc.png)

**Comment by frankenstein91** [comment]
Looks like the text is generated/loaded with JavaScript.
@Orbiter: we had talked about rendering JavaScript/Flash in a headless browser. I'm not sure if we had changed something after that discussion. Do you remember?

**Comment by Orbiter** [comment]
headless browser is possible and used in searchlab.eu / YaCy Grid but it is really a pain. This thing crashes all the time and is extremely ressource intensive.

I am sorry to say but crawling of chat/social media/any kind of communication channel is too off-topic for YaCy.
If you can achieve that with a headless browser extension in the future of YaCy, we can do that.
