### ISSUE TITLE
[Features Request] Ignore robots.txt

### ISSUE THREAD

**Issue by RuikangSun** [yacy/yacy_search_server#493]
robots.txt may protect privacy like excluding `example.org/admin/`, however, **some sites only allow superpower search engine bots like Google bot or Bing bot**. These sites include [bilibili](https://www.bilibili.com/robots.txt)(a Chinese site like YouTube) and [douyin](https://www.douyin.com/robots.txt)(Chinese version of TikTok).
For privacy protection and fair use of contents, I totally agree to respect robots.txt. However **in case that only superpower bots are allowed, for libre knowledge, I don't think it is fair to fully obey robots.txt.**
Similar discussion: #275 which didn't take bot discrimination in consideration.

**Comment by frankenstein91** [comment]
Okay two questions:
Who decides what libre knowledge is?
How to prevent missus of this function?

Alternative to a feature request: Try to reach there administrators and ask them for adding Yacy to there list. I know it's more easy to get in touch with a open source project... But in that way they would a) not notice any thing and don't learn about alternative search engines or b) they will use there reverse Proxy and block the User agent of Yacy. In case of b I think we will get a 2nd request to allow changing the User agent of Yacy.

**Comment by RuikangSun** [comment]
> Okay two questions: Who decides what libre knowledge is? How to prevent missus of this function?
> 
> Alternative to a feature request: Try to reach there administrators and ask them for adding Yacy to there list. I know it's more easy to get in touch with a open source project... But in that way they would a) not notice any thing and don't learn about alternative search engines or b) they will use there reverse Proxy and block the User agent of Yacy. In case of b I think we will get a 2nd request to allow changing the User agent of Yacy.

Software developer cannot prevent abuse of this function and the developer shouldn't be the one who prevent abuse. Spider softwares like scripy usualy provide opinions like `ROBOTSTXT_OBEY=false`. So the users should be the rulekeeper instead of developers.

**Comment by Orbiter** [comment]
Crawling with a different user agent (i.e. googlebot) is possible with YaCy since quite some time - but only for non-p2p mode. For the named reasons, mostly because YaCy is otherwise not usable for professional users.
I will probably make that option also available for the p2p mode.

**Comment by Orbiter** [comment]
I actually forgot that I already enabled an option to choose googlebot-behavior for all network types:
- when you do a crawl start, look out for the section "Robot Behaviour"
- use the checkbox to switch to 'googlebot'

YaCy will then not ignore robots.txt, but use the rules for googlebot.

I believe that will enable everyone so far as it makes sense.

**Comment by Anonymous941** [comment]
Open source software, especially GPL software, is not supposed to limit the user.  This is a feature similar to DRM.

**Comment by frankenstein91** [comment]
@Anonymous941 explain your point. I see no similarities to a DRM. It's only respectful to the content creator and content hoster

**Comment by Anonymous941** [comment]
@frankenstein91 If someone wanted to use this maliciously, they could easily modify the source code to ignore robots.txt and most open-source software like HTTrack allows ignoring that file.  While, in most circumstances, it's disrespectful to ignore it, I can think of a few uses:

* If the site has a misconfigured robots.txt file
* Penetration testing
* OSINT
* The site owner not liking crawling and thinking that disallowing every page is a good idea

**Comment by frankenstein91** [comment]
> * If the site has a misconfigured robots.txt file
> 
In this case, the best thing would be to notify the administrator of the website and improve it for all search engines.

> * Penetration testing
> 
I don't see how Yacy could be used for this purpose.

> * The site owner not liking crawling and thinking that disallowing every page is a good idea
Here you act against the will of the content creator and the operator, for me clearly no sign of respect. It would be respectful to educate the administrator and the content creator, as well as the editors. And if you do it well, the corresponding file will change according.

**Comment by Anonymous941** [comment]
> In this case, the best thing would be to notify the administrator of the website and improve it for all search engines.

For major sites, this is not possible as it is extremely difficult to get in touch with someone in change of the site.

> I don't see how Yacy could be used for this purpose.

It's can actually be extremely useful, it can be used to find pages on sites such as government sites or large work websites that could be potential security vulnerabilities by crawling a site and searching for something like "login" or "passwords".  It can also sort by file extension so I could imagine searching for strange ones might expose something like a list of logins.

> Here you act against the will of the content creator and the operator, for me clearly no sign of respect. It would be respectful to educate the administrator and the content creator, as well as the editors. And if you do it well, the corresponding file will change according.

Sites such as Quora think this is a good idea, and sometimes it's necessary to crawl anyway.

---

I agree that, in most cases, ignoring robots.txt isn't a good idea, but it's not the job of open source software developers to enforce things like that as they don't know how it could be used.

**Comment by frankenstein91** [comment]
> but it's not the job of open source software developers to enforce things like that as they don't know how it could be used.

But the goal and the task is to keep the project usable for as many people as possible. If our project would not adhere to these "soft" rules, then operators would block us differently. On my former website I blocked some user agents via web server. This is not about side benefits, but the large network of peers that make up the index of our search engine. 



> Crawling with a different user agent (i.e. googlebot) is possible with YaCy since quite some time - but only for non-p2p mode. For the named reasons, mostly because YaCy is otherwise not usable for professional users.
> I will probably make that option also available for the p2p mode.

How should a other peer check the URL without knowing wich useragent was used for the crawling? I think it is not good for P2P mode.

**Comment by Anonymous941** [comment]
I guess I'll have to compile a version that doesn't impose restrictions on the user.
