### ISSUE TITLE
Not work on win11

### ISSUE THREAD

**Issue by p6002** [yacy/yacy_search_server#497]
Just downloaded Yacy from here:
https://yacy.net/download_installation/
Afer installation, app cannot be open. 
Clicking shortcut on desktop shows:
"windows cannot find javaw file, make sure name is correct..."

**Comment by frankenstein91** [comment]
Did you install Java on your system before?

**Comment by p6002** [comment]
No, I just follow instructions on the web page.

**Comment by frankenstein91** [comment]
![Screenshot_20220831-133032](https://user-images.githubusercontent.com/2527348/187668868-9b601cb3-ebd7-4588-9c9f-3d98ebaa4df3.png)
Than please read them again.

**Comment by frankenstein91** [comment]
does it work with installed java?

**Comment by frankenstein91** [comment]
@thkoch2001 I think we can close it for now because missing feedback?
