### ISSUE TITLE
Can you make you yacy crawler really work ? Its full of problems and bugs since years

### ISSUE THREAD

**Issue by bubul01** [yacy/yacy_search_server#501]
I don't know why this software is still used by many people with new commentaries on forums etc, because it never work good in fact.

First, yacy is not good to install with very low memory like it said , you can install it with low memory but the problem is it will dont work, you can crawl with low memory, only thousands of pages and it will stop working.

Even with lof more of memory, ive tried with 24gb of memory with millions of urls, it dont work, when i search in local index, even with crawling stopped, often if never find anything on my local index , when i read log of search from other it take more than 10 seconds, often 15 second to show results (only 10 or 11). In fact, it seem it don't change anything with more of 16gb of memory, when crawling multiple website, it become very slow and adding memory only make yacy use more memory and its very slow.

Often it crash without reason, if i restart, i need sometimes to delete index freeworld and import old backup because if not it never load , it start loading and crash or never finish loading (it show the icon loading but after one day it load and load ...), or it load and stop responding and you need to kill java process and restart. I've this problem multiple times, it use the maximum of memory for days and never respond normally, i've tried to change memory garbage collect setting, but it don't change anything, always the same problem. 

I changed a lof of setting with a 1to ssd kingston dedicated to yacy but it never work good, the search dont work with many urls, the crawling is very slow (never more at maximum of 100 / 200ppm , even with speed set in advanced settings to 0ms it dont change anything) , i tried a lot of setting and it never change anything, always the same probleme, even with a lof of different host to crawl (30+) , always the same low "speed" of crawling.

What the point to make a so bad search engine, it work on only with thousands of pages maximum (i think not more of 10000 ), its very slow, it can't crawl a lof of websites (its show empy results when adding urls ), it can't crawl javascript, it's written in java so it cant be fast and use a lot of memory, the results are very slow, this software is very bugged, there's no new update, the last major update from years is on the download page, you now have a lot of donation but never any update, why make donation for a software so bugged ?

**Comment by frankenstein91** [comment]
Maybe a little food for thought from my side as to why you might be disappointed with the speed, it's throttled a bit on purpose. We don't want to become a DDOS machine for small websites. But also for the own Internet, the search engine should not be a burden and rather run in the background.

**Comment by yacylover** [comment]
![grafik](https://user-images.githubusercontent.com/12348172/193315729-375b28d9-feca-4119-a8ec-36998683afbf.png)

Before you start to criticise and blame it all on YaCy, it is indispensable to include all parameters of all involved systems. Java as well as Solr has its architectural flaws. You need to address them using long term IT expertise (at least 15 years). Then you can start to criticise. Above screenshot shows crawler traffic of 1,1 TB achieved in only 5 weeks without a single crash or a thread in deadlock.
