### ISSUE TITLE
Only a warning  com.hazelcast.spi.impl.operationservice.impl.Invocation. Minor

### ISSUE THREAD

**Issue by smokingwheels** [yacy/yacy_search_server#503]
`W 2022/09/28 16:41:42 com.hazelcast.spi.impl.operationservice.impl.Invocation [192.168.1.20]:5701 [YaCyP2P] [4.2] Retrying invocation: Invocation{op=com.hazelcast.cp.internal.operation.RaftQueryOp{serviceName='hz:core:raft', identityHash=202548218, partitionId=0, replicaIndex=0, callId=6789, invocationTime=1664354504244 (2022-09-28 16:41:44.244), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, op=com.hazelcast.cp.internal.raftop.metadata.GetRaftGroupOp{serviceName='hz:core:raft', targetGroupId=CPGroupId{name='METADATA', seed=0, groupId=0}}, groupId=CPGroupId{name='METADATA', seed=0, groupId=0}, policy=LEADER_LOCAL}, tryCount=250, tryPauseMillis=500, invokeCount=220, callTimeoutMillis=60000, firstInvocationTimeMs=1664354423832, firstInvocationTime='2022-09-28 16:40:23.832', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 08:00:00.000', target=null, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=null}, Reason: com.hazelcast.spi.exception.WrongTargetException: WrongTarget! local: Member [192.168.1.20]:5701 - 75f3d9c5-8368-4c29-8fe2-26e36dd00091 this, expected-target: null, partitionId: 0, replicaIndex: 0, operation: com.hazelcast.cp.internal.operation.RaftQueryOp, service: hz:core:raft`

Windows 11
Java 19
old I7 laptop 16 GB 
YaCy 1.925/9749
Pihole Pi-hole [v5.12.2](https://github.com/pi-hole/pi-hole/releases/v5.12.2) FTL [v5.18.1](https://github.com/pi-hole/FTL/releases/v5.18.1) Web Interface [v5.15.1](https://github.com/pi-hole/AdminLTE/releases/v5.15.1)

There is DNS Requests to Domain **phonehome.hazelcast.com** being answered.

I tried blocking it but this still happened.

`W 2022/09/28 16:53:11 com.hazelcast.spi.impl.operationservice.impl.Invocation [192.168.1.20]:5701 [YaCyP2P] [4.2] Retrying invocation: Invocation{op=com.hazelcast.cp.internal.operation.RaftQueryOp{serviceName='hz:core:raft', identityHash=2060613243, partitionId=0, replicaIndex=0, callId=75713, invocationTime=1664355193392 (2022-09-28 16:53:13.392), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, op=com.hazelcast.cp.internal.raftop.metadata.GetRaftGroupOp{serviceName='hz:core:raft', targetGroupId=CPGroupId{name='METADATA', seed=0, groupId=0}}, groupId=CPGroupId{name='METADATA', seed=0, groupId=0}, policy=LEADER_LOCAL}, tryCount=250, tryPauseMillis=500, invokeCount=230, callTimeoutMillis=60000, firstInvocationTimeMs=1664355109089, firstInvocationTime='2022-09-28 16:51:49.089', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 08:00:00.000', target=null, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=null}, Reason: com.hazelcast.spi.exception.WrongTargetException: WrongTarget! local: Member [192.168.1.20]:5701 - 75f3d9c5-8368-4c29-8fe2-26e36dd00091 this, expected-target: null, partitionId: 0, replicaIndex: 0, operation: com.hazelcast.cp.internal.operation.RaftQueryOp, service: hz:core:raft`

Thanks.

**Comment by Orbiter** [comment]
> There is DNS Requests to Domain **phonehome.hazelcast.com** being answered.

wow, that is evil
https://docs.hazelcast.com/imdg/4.2/phone-homes

Allright most peolple nowadays may not react that alarmed, but I don't care. We cannot use phoning-home software in YaCy.

Hazelcast was interesting for the possible purpose to interconnect local YaCy instances, but this is not acceptable.
We should ban hazelcast. I will remove it as soon as possible, or you can remove it if you want to!

**Comment by smokingwheels** [comment]
I would not now where to start to remove it but I will have a look.
I will hold off in pushing My YaCy Tripple Java Combo for bit until its sorted.
Thanks for the quick reply.

**Comment by smokingwheels** [comment]
I tried removing from the lib but yacy wont start.
I tried a file with the same name but still wont start.

**Comment by smokingwheels** [comment]
[https://twitter.com/smokingwheels/status/1575061801532010496](https://twitter.com/smokingwheels/status/1575061801532010496)

**Comment by Orbiter** [comment]
Thats a good tool, if you encounter any other phone-home please let me know.
I will remove then hazelcast as soon as its possible (timing is bad for me right now...)

**Comment by smokingwheels** [comment]
add [metadata.google.internal](metadata.google.internal) to the list.

**Comment by Orbiter** [comment]
removed hazelcast, see also https://github.com/yacy/yacy_search_server/issues/504

I don't know what is calling [metadata.google.internal](https://github.com/yacy/yacy_search_server/issues/metadata.google.internal),  please open another issue if you found out what it calles
