### ISSUE TITLE
Blue peer stats banner not displaying on Status Page in Firefox. Minor issue. 

### ISSUE THREAD

**Issue by smokingwheels** [yacy/yacy_search_server#506]
Ubuntu 18.04
Firefox 105.0
see 
[https://twitter.com/smokingwheels/status/1575867016455417860](https://twitter.com/smokingwheels/status/1575867016455417860)

**Comment by Orbiter** [comment]
I cannot reconstruct the problem. The banner is there in Firefox and Chrome.
If you can still reconstruct the problem, please have a look into the log to see if there is any hint, an exception for example when you open the servlet.

**Comment by smokingwheels** [comment]
Only in Firefox.

**Comment by okybaca** [comment]
Closed for a lack of information to reconstruct the issue.
