### ISSUE TITLE
Crawler Queue inflates with iso Download links crawling goes very slow.

### ISSUE THREAD

**Issue by smokingwheels** [yacy/yacy_search_server#510]
Crawler Queue inflates with iso, apk, dmg, zip Download links and crawling goes very slow.

I have tried this but it still happens. I have also tried blocking it with the pihole but its after the fact.

This is after I Terminated the crawler with the Local Crawler at 0.
<html>
<body>
<legend style="box-sizing: border-box; font-family: sans-serif; border: 0px; padding: 0.3em 0.8em; display: block; width: auto; margin: 0px; font-size: 1.2em; line-height: 16px; color: white; text-align: left; background-color: rgb(101, 172, 42); border-radius: 3px; font-weight: bold; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Thread Pool Settings:</legend>

Thread Pool | maximum Active | current Active
-- | -- | --
Crawler Pool |   | 167
Robots.txt Pool |   | 167
httpd Session Pool |   | 6
Changes take effect immediately

</body>
</html>

A list of the URL's

[https://twitter.com/smokingwheels/status/1576481972930908162](https://twitter.com/smokingwheels/status/1576481972930908162)

**Comment by Orbiter** [comment]
see commit comment

**Comment by smokingwheels** [comment]
Thanks.
Here is mine.
Will keep testing with the pihole.

`parser.mime.deny=
parser.extensions.deny=iso,apk,dmg,zip,mp4,mp3,pdf,rpm,webm,deb,exe,gz,sql,exe,msi,dll</a>,dll”`
