### ISSUE TITLE
Is it possible to have a log file that is bigger? 

### ISSUE THREAD

**Issue by smokingwheels** [yacy/yacy_search_server#512]
I think there is a setting somewhere I will have a search,,
So I can extract all the errors and block domains quicker when the crawler slows down.

It would also be useful if I could log the IndexCreateLoaderQueue_p results. 
Can I use wget and append?
I will try.

Also in the web interface I can't seen to get more than 1000 lines.

Also just a current status page. About 10 hours of playing.
[https://twitter.com/smokingwheels/status/1577070969990311936](https://twitter.com/smokingwheels/status/1577070969990311936)

**Comment by Orbiter** [comment]
it's now 10000 lines.
