### ISSUE TITLE
To be able to Ramp the crawler up when first started to limit DNS requests.

### ISSUE THREAD

**Issue by smokingwheels** [yacy/yacy_search_server#513]
To be able to Ramp the crawler up when first started to limit concurrent DNS requests.
To start at say 500 PPM wait 5 seconds then 1000 PPM etc

I have NBN 25 connection with 5 piholes and a startup peak I hit 4000 PPM which causes "concurrent errors max 150" on all 5 pholes.

The all the piholes take requests from one DNSasq server to share the load.

The crawler was set at 30000 now at 8517 and seems to be ok at the starting of a crawl.

I've been getting DNS hits in the range of 35000 for 10 min on an old i7 running Ubuntu 18.04.
I will also try it on my old i7 laptop running Windows 11 Java 19.

Windows 11 notebook is ok because its a slow one. But 10 years old i7
[https://twitter.com/smokingwheels/status/1577116157823229958](https://twitter.com/smokingwheels/status/1577116157823229958)

At  start of a crawl after restarting yacy.
[https://twitter.com/smokingwheels/status/1577111283744538625](https://twitter.com/smokingwheels/status/1577111283744538625)

**Comment by Orbiter** [comment]
I understand that the number of concurrent DNS requests may be an issue and should be limited. This is a valid addition to the crawler settings. Please be patient for implementation.

**Comment by Orbiter** [comment]
implemented a throttling

**Comment by smokingwheels** [comment]
Cool here is the result. Its 8:46 am
[https://twitter.com/smokingwheels/status/1577822197070336000](https://twitter.com/smokingwheels/status/1577822197070336000)
