### ISSUE TITLE
Crawler Loader (50) | 50 |  wont set immediately. Restart needed. Then interface gets messed up, comes good in 15 mins. 

### ISSUE THREAD

**Issue by smokingwheels** [yacy/yacy_search_server#515]
System a 1GB in the cloud with my DNS server.

YaCy version: yacy_v1.926_202210041610_e931b80cf
Uptime: 0 days 00:32
Java version: 11.0.16
Processors: 1
Load: 1.54
Crawler Loader (50) | 50 |  wont set immediately. 
Tried 10000 till it ran out of memory. Needed reboot to set this large number also. 
Then interface gets messed up, comes good in 15 mins.

 [https://twitter.com/smokingwheels/status/1577334987493634048](https://twitter.com/smokingwheels/status/1577334987493634048)

<html>
<body>

Local Crawler | 46,601 |  
-- | -- | --
Limit Crawler | 0 |  
Remote Crawler | 0 |  
No-Load Crawler | 0 |  
Loader (50) | 50 |  

</body>
</html>

Running good now.

[https://twitter.com/smokingwheels/status/1577341039555522560](https://twitter.com/smokingwheels/status/1577341039555522560)

**Comment by Orbiter** [comment]
If a system runs out of memory anything may happen. This is very difficult to fix without more hints what made the interface go into that situation. Please observe and if possible post a log with exceptions, if any, at such time.

**Comment by smokingwheels** [comment]
I will try and post a log next time.

**Comment by smokingwheels** [comment]
Just had email from my host.

Our monitoring system indicated an issue with the hardware node hosting the instances listed in this email. A sudden reboot has been detected. Our engineering team is currently investigating the issue that caused this, but we expect no impact on data and/or configurations.

I will open if it happens again.
