### ISSUE TITLE
is the Build Pipe running without Cleanup ? (old Libs exist)

### ISSUE THREAD

**Issue by pr0vieh** [yacy/yacy_search_server#521]
the Releases shipped via release.yacy.net is not starting up at Upgrade by me 
i removed the the Old Libs in the Libs folder and now its running
has the Pipeline Cleaned up the Working Directory ?

both Windows Build and Linux Build Affected 

![image](https://user-images.githubusercontent.com/61424/194729341-35a8bf89-8eb2-4c44-8daf-c16cd0b07f36.png)
i have not marked all only some examples

**Comment by Orbiter** [comment]
Fix this by moving your DATA folder to a new release
