### ISSUE TITLE
A question. Can I run a few copies of yacy on the P2P network pre loaded with content to speed up its use? 

### ISSUE THREAD

**Issue by smokingwheels** [yacy/yacy_search_server#529]
From memory a long time ago.
I have run 2 yacy's with the same content and it sorts it out.

The idea may take off.
I would be setting up each instance to start with on a new computer. 
Later on it would just be a download and setup run by the user.

Would the P2P network take care of duplicate content from each instance I run?
Each peer name would have to be different, easy done using QB64 program to give randomly generated peer name at setup on the new hdd site with the java install.

Are there any other issues you or anyone might see I might come across?

**Comment by Orbiter** [comment]
Let me try to sort this out line by line

>I would be setting up each instance to start with on a new computer.

so I consider that every instance you start has the same content that has not yet been delivered to a p2p network

> Later on it would just be a download and setup run by the user.

I do not understand this. There is no "download" and what context does "setup run" has?

> Would the P2P network take care of duplicate content from each instance I run?

so the instances you have would distribute their content to the same DHT targets as long as they see the same network. And yes duplicates would overwrite each other with the effect that the information is there only once... as it would be without duplication of the content in the first place

> Each peer name would have to be different, easy done using QB64 program to give randomly generated peer name at setup on the new hdd site with the java install.

peer names are considered as "decoration", they do not have any functional impact.

> Are there any other issues you or anyone might see I might come across?

duplicate content in several peers do not have a special impact, the result should be the same as if you have only one peer in an ideal world.

**Comment by smokingwheels** [comment]
Cool ok thanks for the reply. 
yes my language is an experimental one my Mum taught me before I started at normal school.

I have been progressing today did a backup of my Mobile yacy index on my laptop.

Up loaded the export in 6 mins to My nextcloud server for remote retrieval to a faster computer larger to be imported to its index.

The peer on my Mobile computer.
 I might well decide to trash the current content so I can index a different subject matter and keep the amount of data to transfer over a mobile hotspot to a minimum allowing fast updates to my main index in my office or base computer systems.
The piholes are wonderful there still working 3 of them out of 5.
 I don't have to fix anything until Im left with 1 out of 3 working.

I personally have a real first time medical side effect in using the drugs mental health have given me over the past 20 years.
I am going to be studied by all sorts of specialists and Dr to find out what to do next.

I have been recording and documenting all the things I have done to help myself.

A Question. How many bug reports do I have on the old yacy bug report site and is it possible to download all the ones I made a long time ago. My memory gives me a figure of about 130 reports.

**Comment by smokingwheels** [comment]
Just tried it semi remotely not leaving my mobile computer in the kitchen.

I transfered my exported file via ssh directly to the import folder it took about 30 mins. to complete and show up the results.

I guess that **means I can do research anywhere in the world** and 
**I can build up my personal yacy search server index that is shared with the world.**
[https://twitter.com/smokingwheels/status/1583338441085194241]
(https://twitter.com/smokingwheels/status/1583338441085194241)

**Comment by smokingwheels** [comment]
I have tried yacy on a mobile phone and I cant do an advanced search on my results.
I can get to the status page ok.
I can't start a crawl from my mobile.

**Comment by smokingwheels** [comment]
I crawl on my mobile computer then transfer xml dump to base computer to the import folder after a short delay all my results are in a backup yacy to be shared with others.
When crawling on mobile computer I have the default settings no to add to the global index while crawling so there is no duplicates to sort out.
works well.
