### ISSUE TITLE
I can't start yacy installed from https://release.yacy.net/yacy_v1.926_202210060010_32e6a5f90.exe

### ISSUE THREAD

**Issue by kotenok2000** [yacy/yacy_search_server#532]
i installed it to f:\yacy
http://localhost:8090/ gives connection_refused
[log.txt](https://github.com/yacy/yacy_search_server/files/9896352/log.txt)

**Comment by kotenok2000** [comment]
I tried to install java 8 from https://adoptopenjdk.net/ but it didn't help

**Comment by pr0vieh** [comment]
Check #521
