### ISSUE TITLE
YaCy in Python?

### ISSUE THREAD

**Issue by swetepete** [yacy/yacy_search_server#534]
Is there any way for the index / distributed hash table YaCy makes to be in some kind of universal format, but scripts for crawling visited pages or for acting as a crawling server could be implemented in any language, such as Python? As long as it produced the same indexing output would it be fine?

**Comment by frankenstein91** [comment]
I don't have tried it yet... But it should be possible to add and modify the solr database via Python and make the changes visible to yacy.

**Comment by swetepete** [comment]
Wonderful, thank you 🤞

**Comment by ArneBab** [comment]
Can this be closed then?

**Comment by Orbiter** [comment]
I actually gave chatGPT a try just to find out if that thing knows anything about YaCy. It produced the following code:

```
import requests

def search_yacy(query, start=0, count=10):
    yacy_api_url = "http://localhost:8090/solr/select"
    params = {
        "q": query,
        "start": start,
        "rows": count,
        "wt": "json"
    }

    response = requests.get(yacy_api_url, params=params)

    if response.status_code == 200:
        search_results = response.json()
        return search_results
    else:
        print(f"Error: {response.status_code}")
        return None

def main():
    query = input("Enter your search query: ")
    search_results = search_yacy(query)

    if search_results:
        print("Search results:")
        for result in search_results["response"]["docs"]:
            print(f"Title: {result['title'][0]}")
            print(f"URL: {result['url']}")

if __name__ == "__main__":
    main()
```

This is really interesting since the url is right to access the embedded solr, the query parameters are right and the evaluation also looks right. However, I did not try this.
