### ISSUE TITLE
Just upgraded yacy on windows now have java not hiding the command window.

### ISSUE THREAD

**Issue by smokingwheels** [yacy/yacy_search_server#538]
Its tailing the log file in the command prompt. 
Win 11 
Java 11

Thanks in advance.
Pic
[https://twitter.com/smokingwheels/status/1590117944700592129](https://twitter.com/smokingwheels/status/1590117944700592129)

**Comment by frankenstein91** [comment]
From which version did you upgrade?
To which yacy version did you upgrade?

**Comment by smokingwheels** [comment]
from github release yacy_v1.926_202210060010_32e6a5f90
to github release     yacy_v1.926_202210250010_309adb814 
Its ok on linux

**Comment by smokingwheels** [comment]
I have a pic of the cmd output with an error. today.

[http://cloud-party.undo.it/index.php/s/NwLmL3qqekBEDw8](http://cloud-party.undo.it/index.php/s/NwLmL3qqekBEDw8/download)
