### ISSUE TITLE
Autocrawler: configuration options are unclear

### ISSUE THREAD

**Issue by 71ae** [yacy/yacy_search_server#548]
Autocrawler can be configured in Advanced Crawler -> Autocrawl (reachable via /Autocrawl_p.html). It has a couple of configuration options (in brackets the default values):
* Enable Autocrawler (n)
* Deep crawl every (50)
* Rows to fetch at once (100)
* Get hosts by query (*:*)
* Shallow crawl depth (0 to 2) (2)
* Deep crawl depth (1 to 5) (3)
* Index text (y)
* Index media (y)

What do these configuration options actually mean? Especially "Deep crawl every"? Every what? Seconds or minutes? Or new documents in the index? Or every # of executed searches? The related config element in the init file (or in System Administration -> Advanced Properties) appears to be "autocrawl.ratio". A ratio of "what" is taken here?

Further more, this has a config element "autocrawl.days". What is this meaning now? Number of days after the last autocrawl was run? Days where documents should still considered as fresh and not re-fetched then?

And a last aspect: The wiki (https://wiki.yacy.net/index.php/En:CrawlStart_p) mentions that for regular recrawling (autocrawl) Bookmarks should be created and special folders set for them. Is this still relevant, or outdated?

Thanks a lot for your clarification.

**Comment by zutto** [comment]
Hi,

Commenting may be a bit of clarity here on at least 2 of the configuration values, as I was tinkering with this. I updated in the PR#650 the `Deep crawl every` UI value a bit, as that was very unintuitive.. I think it still is, but I couldn't think of anything better from the top of my head on the spot.

--

- The `Deep crawl every` (autocrawl.ratio) basically means deep crawl every [Nth documents found in the queue](https://github.com/yacy/yacy_search_server/blob/master/source/net/yacy/crawler/data/CrawlQueues.java#L613). Anything that does not match this deep crawl, will be a shallow crawl.
- - So as an example: rows to fetch: 100, deep crawl every 100 means one document out of the 100 will be deep crawled.
- - rows to fetch: 100, deep crawl every 10 means every 10th document will be deep crawled.
- The `Recrawl only older than # days` (autocrawl.days) limits the solr search to filter out days [`autocrawl.days-now`](https://github.com/yacy/yacy_search_server/blob/master/source/net/yacy/crawler/data/CrawlQueues.java#L592) basically, so anything that is older than this `autocrawl.days` will be up for crawling if the other filters (such as the host query) matches.
- The Rows to fetch at once means how documents to query from the solr.

**Comment by okybaca** [comment]
fixed with #650, right?
