### ISSUE TITLE
Can't crawl localhost webserver, why not?

### ISSUE THREAD

**Issue by ThomasFreedman** [yacy/yacy_search_server#550]
I just installed the yacy search crawler / indexer / search engine on my laptop to play around & evaluate it for an IPFS project.

The install is easy enough, but it refuses to crawl & index the content of my local nginx webserver. Seems like an odd default configuration to prohibit that. I get this response:

Crawling of "http://localhost/" failed. Reason: denied_(the host 'localhost' is local, but local addresses are not accepted: 127.0.0.1)/

I've been looking but can't find any info on why this occurs or if there are any workarounds. Interestingly, the yacy forum search doesn't provide useful info on this either.

**Comment by Orbiter** [comment]
You must switch on "Intranet Indexing" in `ConfigBasic.html`.
This is there to protect your privacy. If you would able to do intranet indexing in P2P mode, your private data could be exposed and it would generate an index of pages that other people cannot retrieve through their browser.

**Comment by ThomasFreedman** [comment]
Thank you, problem solved. I chose the "Search portal for your own web pages" as that seemed to fit. 

Regarding the security implications of the intranet choice, I need to be sure ONLY the specific local URL is crawled. However I want to publicize the index to other nodes in my "federated" network of nodes to provide a truly decentralized & distributed search of those nodes.

The map of results produced by the crawler (once I was able to crawl localhost) does appear to do that, despite the references to many offsite URLs, and that is exactly what I want.

**Comment by datenritter** [comment]
This doesn't make much sense to me. First of all, you can chose "Search portal for your own web pages" but still decide if you want "robinson mode" or not in the network settings.

At least robinson mode should allow you to crawl local addresses (192.168...) as there is no risk of information leak and creating an index with local and remote information combined is probably one of the main reasons to run your own search engine.

Edit: Oh, so you have to switch the "network" to "defaults/yacy.network.allip.unit" manually. Well. That's... confusingto say the least. :\
