### ISSUE TITLE
Index Size Slowly Decreasing

### ISSUE THREAD

**Issue by ISJ-439** [yacy/yacy_search_server#555]
Hello,

I have some static sites im indexing, any idea why it dips lower? 

![image](https://user-images.githubusercontent.com/10002986/215524427-5888c093-0ca3-45d0-bf80-151b84501125.png)

Thank you.

**Comment by smokingwheels** [comment]
Maybe duplicate content between peers?

At least 12 years ago, I had 3 peers and crawled the same content and from my memories now, each peer slightly reduced index after sometime of running after a crawl.

**Comment by okybaca** [comment]
@ISJ-439, do you have any observation of conditions under whose it happens, or some [lines from log](https://yacy.net/faq/#something-seems-not-to-be-working-properly-what-should-i-do) to find a clue? Otherwise it's hard to debug.

**Comment by Orbiter** [comment]
There is no function in YaCy which deletes URLs from the index except when the user wants to delete the index. My only explanation for normal operation would be if existing URLs with status code 200 are replaced with the same URL with failure status codes. I don't know for sure if the statistic does only count URLs with status code 200, but it's actually possible.
