### ISSUE TITLE
Startup script incompatibility with MacOS

### ISSUE THREAD

**Issue by HenryLoenwind** [yacy/yacy_search_server#574]
In startYACY.sh, line 146, there's this code:

```sh
YACY_PARENT_DATA_PATH="`echo $parameter | cut -d' ' -f1`"
```

This will terminate any string passed to the -s (startup folder) parameter at the first space character.

However, in startYACYMacOS.sh, there's this code:

```sh
"`dirname $0`"/startYACY.sh -s "'Library/Application Support/net.yacy.YaCy'"
```

Yes, there's a space character there. So instead of accessing `~/Library/Application Support/net.yacy.YaCy/DATA/SETTINGS/yacy.conf`, it tries to access `~/Library/Application/net.yacy.YaCy/DATA/SETTINGS/yacy.conf`, which obviously doesn't exist. So memory settings have no effect, and YACY always starts with only 600MB of RAM.

---

For me replacing line 146 with just `YACY_PARENT_DATA_PATH=$parameter` and quoting all usages of `$CONFIGFILE` (lines 190, 195, 200, 206, 210) as well as removing the doubled quoting in startYACYMacOS.sh worked to fix this. However, I don't know what that would do on the other supported platforms.

PS: Lines 229 and 231 also need `\"`s around `$parameter`.

---

PS/BTW: I was running into OutOfMemory exceptions in the log with just 4300 entries in the index, but no indication that something could be wrong anywhere else---aside from the number of entries in the index not going up. Is that normal? (no indication and the default memory not being enough for anything)

**Comment by okybaca** [comment]
Wouldn't it be sufficient to add an escape character "\" just in front of space in filename? 
e.g.: Application\ Support

**Comment by HenryLoenwind** [comment]
> Wouldn't it be sufficient to add an escape character "\" just in front of space in filename? e.g.: Application\ Support

No. No matter how you escape the parameter to `-s`, it gets cut on the space (`cut -d' '` is *very* single-minded). Not cutting and then adding more escapes (notice how the original already tries to double-escape the parameter?) might be possible, but I think fixing the code to properly handle values with spaces makes more sense.

BTW: I'm not sure why that `cut` was put there in the first place. It doesn't make sense to *me*. No matter the reason for a space in the parameter, cutting it like that destroys it. There is not a single case I can think of where throwing away everything after a space would yield a correct value. Maybe the original intent was to *trim* the string?

Also, here are my diffs; I just remembered I can simply rename them to ".log" to post them...
[startYACYMacOS.sh.diff.log](https://github.com/yacy/yacy_search_server/files/11366766/startYACYMacOS.sh.diff.log)
[startYACY.sh.diff.log](https://github.com/yacy/yacy_search_server/files/11366767/startYACY.sh.diff.log)

**Comment by HenryLoenwind** [comment]
Sure. I'll do that tomorrow.

**Comment by okybaca** [comment]
were you able to make a PR?

**Comment by joestr** [comment]
Seems like an easy fix. I will do that tomorrow.

**Comment by joestr** [comment]
@okybaca incorporated the changes from @HenryLoenwind

**Comment by HenryLoenwind** [comment]
Oh, sorry. My MacBook had a hardware issue and I had completely forgotten about this when I got it handled. mea culpa, my bad.
