### ISSUE TITLE
DATA directory not created when running ./startYACY.sh

### ISSUE THREAD

**Issue by stonymf** [yacy/yacy_search_server#587]
Hi, I'm trying to get yacy running on Ubuntu 20.04. I have Java installed and cloned this repo.

When I run `./startYACY.sh`, it gives me the message "YaCy started as daemon process. Administration at http://localhost:8090" but I get a Bad Gateway response when loading it, and when I type `./stopYACY.sh` I get the message 

```Invalid YaCy DATA folder path : DATA
Please fill the YACY_DATA_PATH environment variable with a valid YaCy DATA folder path.```

**Comment by smokingwheels** [comment]
@stonymf 

Did you Compile the source in the yacy folder?


The source code is bundled with every YaCy release. 
You can also get YaCy from https://github.com/yacy/yacy_search_server by cloning the repository.

**git clone https://github.com/yacy/yacy_search_server**

Compiling YaCy:

    **You need Java 11 and ant**
    See ant -p for the available ant targets

**cd yacy_search_server**

**ant clean dist**

**Comment by MoritzMoreira** [comment]
I get exactly the same behaviour, not with cloning but just extracting the compressed yacy file. The DATA folder disappeared on system restart, the daemon process runs, but no connection in browser. Do I have to compile in this case, and if so, how can I do that?

**Comment by okybaca** [comment]
Which 'compressed yacy file', exactly? 

If you download just the source code from github, you need to compile, of
course.

If you download compiled distribution zip from https://release.yacy.net or
https://download.yacy.net, you need not to compile anything.

**Comment by smokingwheels** [comment]
@MoritzMoreira 
Try this.

cd yacy_search_server

ant clean dist

**Comment by okybaca** [comment]
yes, that's compilation. 
(and you need some tools to compile the whole thing)

my question is, whether there is an error in distribution file. 

which file did you use?
