### ISSUE TITLE
Version not shown in git build

### ISSUE THREAD

**Issue by okybaca** [yacy/yacy_search_server#590]
When building yacy out of source code from github a later runing it, the version in /Network.html?page=1&maxCount=1000 is shown as "dev/0000". 

The number of version is not included. According to the source code it used to be SVN revision number. Now, after switching to github, it's just zeroes. And since a lot of peers uses github version (official release didn't happen for a long time), version information is useless now.

**Comment by joestr** [comment]
I'm not entirely sure, but I suspect that the Regex Matching is a bit off.

**Comment by joestr** [comment]
It seems that some version strings are formatted like `1.92410069` which could be parsed via the provided RegEx as `1.924/10069`. Some releases use the ReleaseStub like `yacy_v1.926_202302051002_3230df6e2` which **cannot** be parsed and results in `dev/0000`.

**Comment by joestr** [comment]
Early snapshot
![image](https://github.com/yacy/yacy_search_server/assets/20691668/d4262769-c221-48a4-87a3-7367ce9663b4)

**Comment by okybaca** [comment]
Seems perfect! Great work, @joestr!
