### ISSUE TITLE
iPad OS

### ISSUE THREAD

**Issue by GreimersStefan** [yacy/yacy_search_server#599]
Dear Developer

What s about iPad OS when I use the macOS with the app? Is there still an alternative methode now to use yacy on iPad OS?

This means for example searchrequests as "swiss helikopter fly rent service" used in the swiss intranet network.

Kind regards
Steven

**Comment by Orbiter** [comment]
I do not understand your request, which should usually have the format i.e.:

- I want to do ...
- I expected the following behavior ...
- Instead I got this other behavior ...

Please reformulate.

**Comment by okybaca** [comment]
closed for a lack of input from reporter's side
