### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by yacylover** [yacy/yacy_search_server#6]
Test

System Status
System
YaCy version 1.82/9000
Uptime: 45 days 09:37
Processors: 8
Load: 2.74
Threads: 137/17, peak:982, total:8262748
Protection
password-protected [Configure]
Address
Host: []:6070 | SSL: enabled (port 8443)
Public Address: http://sokrates.homeunix.net:6070
YaCy Address: http://endeavour.yacy
Proxy
Transparent off   URL off
Remote: not used
Auto-popup on start-up
Enabled [Disable]
Tray-Icon
Experimental
Memory Usage
RAM used:	62.88 GB
RAM max:	67.98 GB
DISK used:	(approx.) 378.92 GB
DISK free:	1,302.15 GB

**Comment by Orbiter** [comment]
This is not a bug and not a bug report.
