### ISSUE TITLE
solr not updating

### ISSUE THREAD

**Issue by Snarkly** [yacy/yacy_search_server#601]
I just uninstalled an old version of yacy and then installed the new version of yacy but it did not update solr. Instead of updating solr to 8.11.2 it just installed an old version of solr 6.6 I took a screenshot for you. 
![Yacy2a](https://github.com/yacy/yacy_search_server/assets/8492776/424a27cb-3cbf-4eb8-ae82-cb4103aacf76)

**Comment by okybaca** [comment]
And what is the issue/problem?

**Comment by Orbiter** [comment]
updates are only done in single steps. Unfortunately I missed to use solr 7 and thus we cannot upgrade from 6 to 8.
This won't fix. Sorry!

**Comment by okybaca** [comment]
as a workaround, you can export the index and import it into new version [as described in the forum](https://community.searchlab.eu/t/index-migration-to-solr-8-8-1/668/17)

**Comment by pr0vieh** [comment]
It is unacceptable to run on an implementation that is 10 years old
- First of all, security aspect
- Performance aspect
- and what will we say in 10 years? Oh, that's okay, the 20-year-old thing still works, terrible idea

**Comment by okybaca** [comment]
if you mean updating solr, yacy recently migrated to solr 8.X and there is definitely a [plan to move to solr 9.X](https://community.searchlab.eu/t/update-to-latest-yacy-version-to-migrate-solr-index-to-8-11-2-preparation-for-ai-integration/1477). which is not an easy task, as orbiter [wrote in the forum](https://community.searchlab.eu/t/update-to-latest-yacy-version-to-migrate-solr-index-to-8-11-2-preparation-for-ai-integration/1477).
