### ISSUE TITLE
Integrate DHT crawler to search the whole BitTorrent DHT network

### ISSUE THREAD

**Issue by mx5kevin** [yacy/yacy_search_server#609]
Project:

https://btdig.com/

https://github.com/btdig/dhtcrawler2

https://en.wikipedia.org/wiki/BTDigg

There is a search engine with which users can search the whole BitTorrent DHT network decentralized way but its running in a centralized server. It would be useful for everyone if we integrate it to prevent the project from becoming unavailable when the central server goes down. Everyone should have an easy-to-run web interface on their computer.

**Comment by Orbiter** [comment]
It's maybe better to use a specialized search service for specialized protocols. YaCy wants to support http/https primary and there are few exceptions to sources that can also be accessed by a web browser, like ftp and file paths. It might be tempting but no.
