### ISSUE TITLE
takes longer to upload peer seed

### ISSUE THREAD

**Issue by dchmelik** [yacy/yacy_search_server#613]
I reinstalled YaCy 1.92 on search.davidchmelik.com recently (after years) but now it's taking over a week and still hasn't uploaded peer seed, when last time it didn't take over a day or maybe hour to do this.  I know there are newer git commits but I want to use a stable normally-numbered version.

**Comment by okybaca** [comment]
does it say something in the logfile? 
what are the seed settings?

**Comment by dchmelik** [comment]
> does it say something in the logfile?

I don't know

> what are the seed settings?

The're not well-documented but I fixed it now.

**Comment by okybaca** [comment]
> The're not well-documented but I fixed it now.

Can you share, what setting did help? 

Proposed yacy.conf documentation is
[here](https://github.com/yacy/yacy_net_homepage/blob/2cd7b5e9c2ace309d8e81b5368448983cc061961/docs/operation/yacy_conf.md).

If you have any additions or recommendations, I'd be thankful, if you add them.

**Comment by dchmelik** [comment]
> an you share, what setting did help?

Just setting the upload details & method & URL and pressing the necessaru three submit/upload buttons, which seems excessive.

**Comment by okybaca** [comment]
> Just setting the upload details & method & URL and pressing the necessaru three submit/upload buttons, which seems excessive.

Could it be described as a bug? What do you think would be neccessary to fix that?

**Comment by dchmelik** [comment]
> Could it be described as a bug? What do you think would be neccessary to fix that?

No; it's just complicated.  I've always used yacy/htroot/seed.txt, which regardless which method is used, you'd think could be used to automatically generate URL so one need not press submit/upload more than once, unless you've saved details for more than one method, only in which case should you have to select one then press a second button.
