### ISSUE TITLE
Can we make a 1.930 official release?

### ISSUE THREAD

**Issue by okybaca** [yacy/yacy_search_server#637]
"Official" release of YaCy hadn't been made for quite a while. 
Latest release available on [yacy.net](https://yacy.net/download_installation/) is 1.924 while 1.930 is available on github and has plenty of improvements (and a new version on both solr and Java). People still download and use 1.924 and Mac and Windows folks are condemned to use the old version. Not everyone is able to compile own brew out of github sources.
How the official release can be made, @orbiter?
I understand that making Windows and Mac release can be quite a process. But could you at least describe that and make a sort of checklist, so it becomes more easy? Or, if there is some trouble, ask for help of others?
I'm also not sure what are other "official" release packages. Docker? Debian package (as descried [here](https://yacy.net/installation/debianinstall/))? Who admins that and how?
The best way would be to have a releasing process described in release.md or something, so anyone could be guided to do that and @orbiter doesn't have so much overhead, while working on other projects.
There are also a lot of questions or bugs under [releasing](https://github.com/yacy/yacy_search_server/issues?q=is%3Aopen+is%3Aissue+label%3Areleasing) label in issues.

**Comment by smokingwheels** [comment]
I have been testing Amazon Java, Linux and Windows.
With Windows You can possibly have a msi silently installed.
Has anyone else tested the Amazon java?
More info on. [Java](https://aws.amazon.com/corretto/?filtered-posts.sort-by=item.additionalFields.createdDate&filtered-posts.sort-order=desc)

**Comment by okybaca** [comment]
Yes, great, @Orbiter !
But what about Windows and Mac release? How to build them?

Only difference between automatic github build and official release is code signing by 'official' key, is that so? 
(then, nodes using 'only accept signed files' in autoupdate won't be updated).

**Comment by okybaca** [comment]
And, also, there is option to 'tag' releases on github, which was used in the past, but ended with 1.92. Some people call for that: https://github.com/yacy/yacy_search_server/issues/348 . For example for various solr versions, it may be useful to be able to go back for a tagged older release.
