### ISSUE TITLE
JSON api returns empty result for items (Python 3.5)

### ISSUE THREAD

**Issue by songproducer** [yacy/yacy_search_server#64]
Can't work out how to get the description for search results, as items array is empty when it comes into Python. Not sure if this is a bug with Python or the way Yacy returns JSON requests.

query':query, 'contentdom':'text', 'maximumRecords': '1'

**Comment by Scarfmonster** [comment]
YaCy seems to return proper JSON for me, so it's most probably how you read the json in Python.

Take note that "items" is inside the first object of the "channels" array.

**Comment by songproducer** [comment]
Thanks, you're right, I didn't realise the search result was coming up empty!
