### ISSUE TITLE
When peer is overloaded with a search queries. Thread dump.

### ISSUE THREAD

**Issue by smokingwheels** [yacy/yacy_search_server#645]
See Thread dump.
[http://cloudparty.evils.in/index.php/s/5SZ8BydDxgn85qi](http://cloudparty.evils.in/index.php/s/5SZ8BydDxgn85qi)

Log files
[http://cloudparty.evils.in/index.php/s/io2w92kWydzFb4x](http://cloudparty.evils.in/index.php/s/io2w92kWydzFb4x)

**Comment by okybaca** [comment]
Thanks for posting!
But what is the problem description? What is expected behavior and what does it do instead?

**Comment by smokingwheels** [comment]
Just a bit of a load test on my server. 
I assigned **100 GB** of memory for java and used Wget to perform a search at 1 second intervals.
Not really a problem just sharing the information about the load test.

YaCy Version: yacy_v1.930_202404051704_de941c6fe
Assigned   Memory = 104857600000
Used       Memory = 61442964000
Available  Memory = 43414636000

Although there is errors like this. 
E 2024/05/19 07:04:34 org.apache.solr.handler.RequestHandlerBase org.apache.solr.common.SolrException: Error while processing facet fields: InterruptedException

The yacy servers have limits if you search too often it wont harm the other peers.  

W 2024/05/19 07:04:34 LOCAL_SEARCH * ACCESS CONTROL: CLIENT FROM 1.1.1.1: 26/3s, 479/60s, 600/600s,  requests, disallowed global search
W 2024/05/19 07:04:34 LOCAL_SEARCH * ACCESS CONTROL: CLIENT FROM 1.1.1.1 : 26/3s, 479/60s, 600/600s,  requests, disallowed remote snippet loading


This issue forum has 65535 character so I had to host the files on my nextcloud server.

**Comment by Orbiter** [comment]
I checked the dump and also the log and found it interesting "somehow", which means that I did a lot of code review especially for the search request that a peer does to it's own Solr index. However, I appeared to me that there is now room for performance enhancements.

But, ...

Meanwhile I had another experiment running for some time: I trained a ChatGPT GPT to become an expert for YaCy. The result is posted here https://community.searchlab.eu/t/yacy-support-gpt-chatgpt-assistant/1622 where I test the GPT with parts of your thread dump from this issue. ChatGPT gave me interesting hints on how to enhance the configuration of Solr.
I did not test so far if this is actually helpful, but I will do.

**Comment by Orbiter** [comment]
I now make a code change according to the recommendation from the ChatGPT evaluation:
https://github.com/yacy/yacy_search_server/commit/71a6074cc570df0f9df95bcd24b4325ea01aedf1
Should not do any harm and maybe we see a positive effect.

**Comment by smokingwheels** [comment]
I ran a test and the changes have lowered CPU average load.
[https://youtu.be/nKd1uOj9omQ](https://youtu.be/nKd1uOj9omQ)

I got upto about 30 Hz on my ramdrive peer synced with a nextcloud server with a ramdrive.
see [https://help.nextcloud.com/t/snap-setup-of-nc-25-a-ramdisk-experiment-on-old-recycled-hardware-with-new-hdd/156423/3](https://help.nextcloud.com/t/snap-setup-of-nc-25-a-ramdisk-experiment-on-old-recycled-hardware-with-new-hdd/156423/3) if intrested.

That ChatGPT evaluation: well I use it for lots of things.
