### ISSUE TITLE
Limiting access to Administration Panel in YaCy

### ISSUE THREAD

**Issue by winicius87** [yacy/yacy_search_server#653]
I do not want anyone to access the administration panel. I still want to be a Senior/Principal peer.

How do I do that?

I would like to make the Administration panel inaccessible by everyone.

When I want it accessed I can login to the machine and enable the Administration panel.

**Comment by okybaca** [comment]
Setting the administrator password?
https://eldar.cz/yacydoc/faq.html#passwords

some administration pages are accessible to everyone, but only those showing
the status of the host. The pages with lock icon (basicaly, pages that
allow to change something or to control the host) are accessible only after
logon. 

you can eliminate the administration/log in buttons in the 'portal design'
section, but the administration is still accessible, only not linked.

**Comment by okybaca** [comment]
did that help?

**Comment by Orbiter** [comment]
The YaCy administration panel is protected by the password where there are either secrets or values can be changed. All other places are visible on purpose.
