### ISSUE TITLE
which check

### ISSUE THREAD

**Issue by jzacman** [yacy/yacy_search_server#667]
Hi, I have installed yacy in my system but when I tried to run the startYacy.sh file It always returned a message saying that my Java installation was not in **PATH**. After reinstalling my Java and made sure it was in **PATH** I studied the .sh file itself and I noticed that it was using the command which. To my surprise I didn't have _which_ installed and that was the hole issue. Once I installed it all worked fine. So my Request is to add a check to the executable to verify if _which_ is installed.

Please.
Salutations.

**Comment by okybaca** [comment]
Hi, thanks for feedback! Which... eh... what system did you use?  ;-)

**Comment by okybaca** [comment]
maybe `which` command could be replaced (or boosted) with UNIX standard `type` or rather
`command -v`, as suggested here:
https://unix.stackexchange.com/questions/126134/is-there-an-alternative-to-the-which-command

https://pubs.opengroup.org/onlinepubs/9699919799/utilities/command.html#

could you confirm, that `command -v java` gives a proper java executable on
your platform?

**Comment by jzacman** [comment]
Thank you pretty much 
```
$command -v java
/data/data/com.termux/files/usr/bin/java
```
commnad outputs the same as which
I am installing yacy server in my android phone via termux terminal emulator. Is quite an enjoyable thing.

**Comment by okybaca** [comment]
nice, that could be the solution!

unfortunately, `command` command doesn't work on debian, so it will be
rather some ifs than just replacement. 

but android is worth of that.

**Comment by okybaca** [comment]
try this fix:
https://github.com/yacy/yacy_search_server/pull/670
does that work for you?

**Comment by okybaca** [comment]
> I am installing yacy server in my android phone via termux terminal emulator. Is quite an enjoyable thing.

would you write just a few lines mini-howto on how you did get it run on android? so we could put it as an instruction in the documentation... 
it's pretty cool to have yacy working on android!

**Comment by jzacman** [comment]
Sure thing okubaca

First download and install termux app in your android device from this link (choose your proper processor architecture)

[https://github.com/termux/termux-app/releases](https://github.com/termux/termux-app/releases)

Second open the app and update the repositories and install the latest Java and ant with this command:

```
pkg update && pkg upgrade && pkg install openjdk-21 ant -y
```

Then clone the repository and build the application:

```
git clone --depth 1 https://github.com/yacy/yacy_search_server.git
cd yacy_search_server
ant clean all
```

To start YaCy, run
`./startYACY.sh`
Upon starting yacy, the browser must launch the search page automatically. Remember to allow termux to **Acquire wakelock** by clicking on the notification so it doesn't pause. And for a better experience, open the appropiate port on your router's **portforward** page.

Stop YaCy on the console with
`./stopYACY.sh`

Of course it needs _which_ so for now the second step should be: 

Second open the app and update repositories and install the latest **Java ant and _which_** with this command:

```
pkg update && pkg upgrade && pkg install openjdk-21 ant which -y
```

Here it is a quick guide. I hope is cool. Have an awesome day.

**Comment by okybaca** [comment]
oh, great, thanks, that's comprehensive!

i'm sure, it will help other android/people!

**Comment by jzacman** [comment]
no problem

**Comment by okybaca** [comment]
android installation guide docs PR: https://github.com/yacy/yacy_net_homepage/pull/41

which issue fixed in PR: https://github.com/yacy/yacy_search_server/pull/670

thanks @jzacman !
