### ISSUE TITLE
YaCyDefaultServlet potential absolute path traversal

### ISSUE THREAD

**Issue by oneafter** [yacy/yacy_search_server#669]
Recently, I discovered a potential absolute path traversal vulnerability. When modifying the value of the htDocsPath field in yacy.conf to a certain absolute path, specifically using the root directory, and deploying yacy on a local area network with server address 192.168.200.61, the client directly requests 192.168.200.61:8090/etc/password and returns the content of/etc/password from the server.

<img width="501" alt="yacy1" src="https://github.com/user-attachments/assets/916a0d23-4b0f-4b22-8864-136889d7cf59">
<img width="1303" alt="yacy2" src="https://github.com/user-attachments/assets/44dfd7dc-eace-4803-95fc-ba72a9bd4da1">

**Comment by joestr** [comment]
This does not work if YaCy is properly configured with a proper `htDocsPath`. Deliberately modifying a configuration to allow such behaviour is unwanted, yes, but not a flaw in itself.

In the end configuring your system to allow a vulnerability is of poor taste. The system does what it has been configured to do: Serving content from `/` and that's exactly what YaCy does.

**Comment by okybaca** [comment]
Maybe a warning in the config file comment would be sufficient. 

Or a check, whether root (`/`) is not set as a htDocsPath. 

Maybe even check whether it is yacy subdir -- but, on the other hand, in
some configuration (Docker, I guess; or a standard place in some
distribution package), the htDocsPath could be outside the yacy directory.
