### ISSUE TITLE
Enhancement Request: weather and movie widgets

### ISSUE THREAD

**Issue by jawz101** [yacy/yacy_search_server#75]
As a casual user, it would be nice to provide information that isn't purely tech sites.  One thing that would be nice is a way to see a nice visual if I type in "weather <cityname>", "movies <cityname>", "sunset <cityname>", "convert 3 pounds to kilograms."

And get some quick answers.  While it might be fluff compared to the main purpose of this project, it would give a casual usefulness to the program.

**Comment by gj12** [comment]
You can wrap your own portal/client around yacy and use the wrapper to display widgets.
