### ISSUE TITLE
Less GC 

### ISSUE THREAD

**Issue by linkerlin** [yacy/yacy_search_server#79]
I have try using G1GC ,and got a good performance.
set javacmd=%javacmd% -Djava.net.preferIPv4Stack=true **-XX:+UseG1GC** -Djava.awt.headless=true -Dsolr.directoryFactory=solr.MMapDirectoryFactory -Dfile.encoding=UTF-8 -Djsse.enableSNIExtension=false

**Comment by luccioman** [comment]
Hi @linkerlin thank you for reporting this, but could you give more details? 
Were you trying to solve some performance issue related to a specific YaCy operation?

**Comment by linkerlin** [comment]
When yacy got a lot of web-pages in a small-memory box, yacy will not response any web requests.
Using G1GC will resolve the problom.
