### ISSUE TITLE
Use Neo4j as storage or/and use mapdb 

### ISSUE THREAD

**Issue by linkerlin** [yacy/yacy_search_server#82]
[MapDB](http://www.mapdb.org/)
[Neo4j ](https://neo4j.com/)

MapDB will save a lot of memory by move data out of java-heap.
Neo4j is much flexiable then lucene.

**Comment by linkerlin** [comment]
MapDB can use mmap or random access file to move data from managed-heap to disk(with caches which controlled by OS.
It will dreamily optimize yacy's memory usage.

**Comment by luccioman** [comment]
Maybe @linkerlin , but what you propose would involve quite a huge refactoring... Optimization of memory footprint would still have to be measured and confirmed as YaCy already has similar internal mechanisms to map memory with disk backups.

**Comment by luccioman** [comment]
If such a refactoring would be on the charts, to my mind higher level projects such as [Apache Gora](https://gora.apache.org/) or [Spring Data](http://projects.spring.io/spring-data/) would be interesting to consider as they would allow to switch more easily between data storage solutions...

**Comment by sudheesh001** [comment]
@luccioman is right, I don't think the effort involved in this is worth looking into this, maybe Gora is a good solution
