### ISSUE TITLE
Simplify the inclusion of the jar files in build by including all jars in buildpath

### ISSUE THREAD

**Issue by sudheesh001** [yacy/yacy_search_server#89]
As of now we are specifying the jars manually in the build path definition. This can be done to include all the elements in the `lib/` directory which would be more elegant.

``` XML
 <!-- define the classpath that should be used for compiling -->
    <!-- when changing paths here, please also update the paths in /addon/YaCy.app/Contents/Info.plist -->
    <path id="project.class.path">
      <pathelement location="${build}" />

      <fileset dir="${lib}">
         <include name="**/*.jar"/>
      </fileset>
    </path>
```

@Orbiter Your views on this ?

**Comment by thkoch2001** [comment]
ivy should be able to generate a classpath, see #467

**Comment by Orbiter** [comment]
yes, I removed all extra build paths and moved the java files from htdocs to the common build path
