### ISSUE TITLE
yacy server listen yo 127.0.0.1 not 0.0.0.0

### ISSUE THREAD

**Issue by nikdavnik** [yacy/yacy_search_server#92]
I installed yacy in my debian machine. Now it is listening to 0.0.0.0:8090.
I would like to make it listen to 127.0.0.1:8090 (or any other ip, but not 0.0.0.0)

I changed 
port = 8090 to port = 127.0.0.1:8090 but no luck

How can I configure it?

**Comment by luccioman** [comment]
Hello @nikdavnik the port setting is only supposed to contain a port number. 
But I am not sure to understand your question : if your YaCy peer is reachable at URL `http://0.0.0.0:8090` it should also be reachable at `http://127.0.0.1:8090` and on any other IP at `http://otherIP:8090...`
0.0.0.0 is only a pseudo IP address.

By the way, another setting might interest you : [staticIP](https://github.com/yacy/yacy_search_server/blob/Release_1.90/defaults/yacy.init#L477) lets you to define the external IP used by others to reach your peer.

Best regards

**Comment by nikdavnik** [comment]
I know that 0.0.0.0 is listening to any availables interfaces, but I dont want it.
I want yacy to listen ONLY 127.0.0.1.
How can I configure it?

Thank you
David

**Comment by luccioman** [comment]
Ok @nikdavnik , you have at least two possibilities :
 - setting the [serverClient](https://github.com/yacy/yacy_search_server/blob/Release_1.90/defaults/yacy.init#L381) property in your yacy.conf settings file to `serverClient=127.0.0.1` : this will not truly bind only to 127.0.0.1, but will effectively reject any connection coming from anything else than localhost
 - modifying the [Jetty9HttpServerImpl.java](https://github.com/yacy/yacy_search_server/blob/master/source/net/yacy/http/Jetty9HttpServerImpl.java#L73) source code  by adding a `connector.setHost("127.0.0.1");` and `sslConnector.setHost("127.0.0.1");` instructions will do exactly what you want

I just checked these solutions worked, but there may be other options using for example Jetty environment variables. But for now I didn't found one working with current YaCy code.

**Comment by sudheesh001** [comment]
I agree with what @luccioman has mentioned here. @nikdavnik Please do try it out and let us know, I think this issue is good to close.

**Comment by frankenstein91** [comment]
no feedback... so I will close it now

**Comment by Orbiter** [comment]
implemented a host setting in https://github.com/yacy/yacy_search_server/commit/055a2eaa250e97cbac21e42316db27b76e9c8798

To use this, you have to change the setting manually in the configuration.
