### ISSUE TITLE
An idea that will need more testing and thought. For a Yacy Front End App.

### ISSUE THREAD

**Issue by smokingwheels** [yacy/yacy_search_server#95]
Light weight I Frame program pointing to you own Yacy Web Server.
The EXE file is 1.5 MB for the web server. 
You can scale the Iframe to suite the device.

Results so far
Windows Tested Ok. XP and 7
Linux Ubuntu 14.04 there some Error 258? when compiling. Not reported as yet.
Mac osx Unknown    
Android App is Possible but its beyond me at the moment.

What do you think? 

 [Source](https://github.com/smokingwheels/Yacy_front_end/)

**Comment by sudheesh001** [comment]
@smokingwheels Is this for a load test on yacy ?
Can you explain more about the `iframe` part that you're talking about ?

**Comment by smokingwheels** [comment]
@sudheesh001 No it is not a load tester. `Iframe` is a inline web page, a front end redirecting to your yacy server or other web server.
You could use a $5/Month Debian/Ubuntu Headless VM running an apache2 web server in the cloud to host it, with 1 TB of Data.
`Iframe` Experiment with something like This Site [Iframe Generator HTML 5](http://codegena.com/generator/iframe-code-generator) 
With this Iframe generator you can scale the output to `%` Older Generator [Older Iframe Generator](http://www.iframe-generator.com/)

Thanks for asking the questions.

**Comment by Nic-Wow** [comment]
Ubuntu Phone would also be neat. I don't have one or I would test it but still would be neat.
