### ISSUE TITLE
cannot connect to yacy server for query on http://search.yacy.net/

### ISSUE THREAD

**Issue by nikhilrayaprolu** [yacy/yacy_search_server#99]
![screenshot from 2016-12-28 20-21-21](https://cloud.githubusercontent.com/assets/15216503/21524415/e34a1a12-cd3b-11e6-8e30-5cf3782d38c5.png)

**Comment by sudheesh001** [comment]
Looks more like a temporary problem. Seems to be working correctly and search.yacy.net is live. Please reopen in case of repeat and give a live link to the test server.

**Comment by dchmelik** [comment]
I have this problem also.
